//Code Generated By Project A.L.I.C.E Developer Toolkit
//Class File Generated: 01/18/2026 4:27 PM
//Source Journal Line: { "timestamp":"2026-01-10T20:01:43Z", "event":"BuyAmmo", "Cost":11251 }

using System;
using System.Collections.Generic;

namespace ALICE_Events
{
    public class Event_BuyAmmo : Event_Base
    {
        public Event_BuyAmmo()
        {
            Name = "BuyAmmo";
        }

        public void Logic()
        {
            if (Manager.WriteVariables && WriteVariables)
            {
                try
                {
                    Variables_Clear();
                    Variables_Generate();
                    Variables_Write();
                }
            }

            //GameState.Logic_BuyAmmo((BuyAmmo)GetEvent());

            TriggerEvent();
        }

        public void Variables_Generate()
        {
            BuyAmmo Event = (BuyAmmo)Manager.GetEvent(Name);

            Variables.Clear();

            #region Custom Variables

            #endregion

            #region Event Variables
            Variable_Craft("Cost", Event.Cost.ToString());
            #endregion
        }
    }

    #region BuyAmmo Event
    public class BuyAmmo : Base
    {
        public decimal Cost { get; set; }
    }
    #endregion
}


//Journal Reader Code Chunk.

// else if (EventName == "BuyAmmo")
// {
//     var Event = JsonConvert.DeserializeObject<ALICE_Events.BuyAmmo>(RawLine);
//     Manager.UpdateEvents(EventName, Event);
//     Manager.BuyAmmo.Logic();
// }
