//Code Generated By Project A.L.I.C.E Developer Toolkit
//Class File Generated: 11/12/2018 1:27 AM
//Source Journal Line: { "timestamp":"2018-10-29T01:11:03Z", "event":"MissionCompleted", "Faction":"The Fuel Rats Mischief", "Name":"Mission_Massacre_Conflict_War_name", "MissionID":429329381, "TargetFaction":"Constitution Party of Fuelum", "KillCount":72, "DestinationSystem":"Fuelum", "DestinationStation":"Wollheim Vision", "Reward":2157547, "FactionEffects":[ { "Faction":"The Fuel Rats Mischief", "Effects":[ { "Effect":"$MISSIONUTIL_Interaction_Summary_lockdown_down;", "Effect_Localised":"$#MinorFaction; have less signs of imposing a security lockdown.", "Trend":"DownGood" } ], "Influence":[  ], "Reputation":"UpGood" }, { "Faction":"Constitution Party of Fuelum", "Effects":[ { "Effect":"$MISSIONUTIL_Interaction_Summary_lockdown_up;", "Effect_Localised":"Further terrorist actions could see the $#MinorFaction; considering a security lockdown ", "Trend":"UpBad" } ], "Influence":[  ], "Reputation":"DownBad" } ] }

using System;
using System.Collections.Generic;

namespace ALICE_Events
{
    /// <summary>
    /// Object Data Class
    /// </summary>
    public class MissionCompleted : Base
    {
        public string Faction { get; set; }
        public string Name { get; set; }
        public string LocalisedName { get; set; }
        public decimal MissionID { get; set; }
        public string TargetType { get; set; }
        public string TargetType_Localised { get; set; }
        public string TargetFaction { get; set; }
        public decimal KillCount { get; set; }
        public string DestinationSystem { get; set; }
        public string DestinationStation { get; set; }
        public decimal Reward { get; set; }
        public string MaterialsReward { get; set; }
        public string FactionEffects { get; set; }

        //Default Constructor
        public MissionCompleted()
        {
            Faction = Str();
            Name = Str();
            LocalisedName = Str();
            MissionID = Dec();
            TargetType = Str();
            TargetType_Localised = Str();
            TargetFaction = Str();
            KillCount = Dec();
            DestinationSystem = Str();
            DestinationStation = Str();
            Reward = Dec();
            MaterialsReward = Str();
            FactionEffects = Str();
        }
    }

    /// <summary>
    /// Event Logic & Data Storage Class
    /// </summary>
    public class Event_MissionCompleted : Event
    {
        //Variable Generation
        public override void Generate(object O)
        {
            try
            {
                var Event = (MissionCompleted)O;

                Variables.Record(Name + "_ID", Event.MissionID);
                Variables.Record(Name + "_Faction", Event.Faction);                
                Variables.Record(Name + "_Type", Event.Name);
                Variables.Record(Name + "_Donation", Event.Donation);
                Variables.Switch(Name + "_Commodity", Event.Commodity_Localised, Event.Commodity);
                Variables.Record(Name + "_Count", Event.Count);
                Variables.Switch(Name + "_Target", Event.Target_Localised, Event.Target);
                Variables.Switch(Name + "_TargetType", Event.TargetType_Localised, Event.TargetType);
                Variables.Record(Name + "_TargetFaction", Event.TargetFaction);
                Variables.Record(Name + "_KillCount", Event.KillCount);
                Variables.Record(Name + "_DestinationSystem", Event.DestinationSystem);
                Variables.Record(Name + "_DestinationStation", Event.DestinationStation);
                Variables.Record(Name + "_Reward", Event.Reward);
            }
            catch (Exception ex)
            {
                ExceptionGenerate(Name, ex);
            }
        }
    }
}