//Code Generated By Project A.L.I.C.E Developer Toolkit
//Class File Generated: 01/18/2026 4:27 PM
//Source Journal Line: { "timestamp":"2025-11-12T09:17:26Z", "event":"Commander", "FID":"F2812796", "Name":"Snowythefox" }

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using ALICE_Ships_Datalink_Interface;
using ALICE_Command_Interface;
using ALICE_Internal;

namespace ALICE_Events
{
    public class Event_Commander : Event_Base
    {
        public Event_Commander()
        {
            Name = "Commander";
        }

        public void Logic()
        {
            if (Manager.WriteVariables && WriteVariables)
            {
                try
                {
                    Variables_Clear();
                    Variables_Generate();
                    Variables_Write();
                }
            }

            //GameState.Logic_Commander((Commander)GetEvent());

            TriggerEvent();
        }

        public void Variables_Generate()
        {
            Commander Event = (Commander)Manager.GetEvent(Name);

            Variables.Clear();

            #region Custom Variables

            #endregion

            #region Event Variables
            Variable_Craft("FID", Event.FID.ToString());
            Variable_Craft("Name", Event.Name.ToString());
            #endregion
        }
    }

    #region Commander Event
    public class Commander : Base
    {
        public string FID { get; set; }
        public string Name { get; set; }
    }
    #endregion
}


//Journal Reader Code Chunk.

// else if (EventName == "Commander")
// {
//     var Event = JsonConvert.DeserializeObject<ALICE_Events.Commander>(RawLine);
//     Manager.UpdateEvents(EventName, Event);
//     Manager.Commander.Logic();
// }
