//Code Generated By Project A.L.I.C.E Developer Toolkit
//Class File Generated: 01/18/2026 4:27 PM
//Source Journal Line: { "timestamp":"2026-01-10T14:59:59Z", "event":"HeatWarning" }

using System;
using System.Collections.Generic;

namespace ALICE_Events
{
    public class Event_HeatWarning : Event_Base
    {
        public Event_HeatWarning()
        {
            Name = "HeatWarning";
        }

        public void Logic()
        {
            if (Manager.WriteVariables && WriteVariables)
            {
                try
                {
                    Variables_Clear();
                    Variables_Generate();
                    Variables_Write();
                }
            }

            //GameState.Logic_HeatWarning((HeatWarning)GetEvent());

            TriggerEvent();
        }

        public void Variables_Generate()
        {
            HeatWarning Event = (HeatWarning)Manager.GetEvent(Name);

            Variables.Clear();

            #region Custom Variables

            #endregion

            #region Event Variables
            #endregion
        }
    }

    #region HeatWarning Event
    public class HeatWarning : Base
    {
    }
    #endregion
}


//Journal Reader Code Chunk.

// else if (EventName == "HeatWarning")
// {
//     var Event = JsonConvert.DeserializeObject<ALICE_Events.HeatWarning>(RawLine);
//     Manager.UpdateEvents(EventName, Event);
//     Manager.HeatWarning.Logic();
// }
