//Code Generated By Project A.L.I.C.E Developer Toolkit
//Class File Generated: 01/18/2026 4:27 PM
//Source Journal Line: { "timestamp":"2026-01-10T14:27:59Z", "event":"CrewLaunchFighter", "Telepresence":false, "Crew":"RIPTHEREAPER" }

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using ALICE_Ships_Datalink_Interface;
using ALICE_Command_Interface;
using ALICE_Internal;

namespace ALICE_Events
{
    public class Event_CrewLaunchFighter : Event_Base
    {
        public Event_CrewLaunchFighter()
        {
            Name = "CrewLaunchFighter";
        }

        public void Logic()
        {
            if (Manager.WriteVariables && WriteVariables)
            {
                try
                {
                    Variables_Clear();
                    Variables_Generate();
                    Variables_Write();
                }
            }

            //GameState.Logic_CrewLaunchFighter((CrewLaunchFighter)GetEvent());

            TriggerEvent();
        }

        public void Variables_Generate()
        {
            CrewLaunchFighter Event = (CrewLaunchFighter)Manager.GetEvent(Name);

            Variables.Clear();

            #region Custom Variables

            #endregion

            #region Event Variables
            Variable_Craft("Telepresence", Event.Telepresence.ToString());
            Variable_Craft("Crew", Event.Crew.ToString());
            #endregion
        }
    }

    #region CrewLaunchFighter Event
    public class CrewLaunchFighter : Base
    {
        public string Telepresence { get; set; }
        public string Crew { get; set; }
    }
    #endregion
}


//Journal Reader Code Chunk.

// else if (EventName == "CrewLaunchFighter")
// {
//     var Event = JsonConvert.DeserializeObject<ALICE_Events.CrewLaunchFighter>(RawLine);
//     Manager.UpdateEvents(EventName, Event);
//     Manager.CrewLaunchFighter.Logic();
// }
