//Code Generated By Project A.L.I.C.E Developer Toolkit
//Class File Generated: 01/18/2026 4:27 PM
//Source Journal Line: { "timestamp":"2026-01-10T19:58:15Z", "event":"FighterRebuilt", "Loadout":"zero", "ID":38 }

using System;
using System.Collections.Generic;

namespace ALICE_Events
{
    public class Event_FighterRebuilt : Event_Base
    {
        public Event_FighterRebuilt()
        {
            Name = "FighterRebuilt";
        }

        public void Logic()
        {
            if (Manager.WriteVariables && WriteVariables)
            {
                try
                {
                    Variables_Clear();
                    Variables_Generate();
                    Variables_Write();
                }
            }

            //GameState.Logic_FighterRebuilt((FighterRebuilt)GetEvent());

            TriggerEvent();
        }

        public void Variables_Generate()
        {
            FighterRebuilt Event = (FighterRebuilt)Manager.GetEvent(Name);

            Variables.Clear();

            #region Custom Variables

            #endregion

            #region Event Variables
            Variable_Craft("Loadout", Event.Loadout.ToString());
            Variable_Craft("ID", Event.ID.ToString());
            #endregion
        }
    }

    #region FighterRebuilt Event
    public class FighterRebuilt : Base
    {
        public string Loadout { get; set; }
        public decimal ID { get; set; }
    }
    #endregion
}


//Journal Reader Code Chunk.

// else if (EventName == "FighterRebuilt")
// {
//     var Event = JsonConvert.DeserializeObject<ALICE_Events.FighterRebuilt>(RawLine);
//     Manager.UpdateEvents(EventName, Event);
//     Manager.FighterRebuilt.Logic();
// }
