//Code Generated By Project A.L.I.C.E Developer Toolkit
//Class File Generated: 11/12/2018 1:27 AM
//Source Journal Line: { "timestamp":"2018-10-30T02:29:20Z", "event":"Missions", "Active":[ { "MissionID":425812062, "Name":"Mission_TheDead_name", "PassengerMission":false, "Expires":0 }, { "MissionID":429236792, "Name":"Mission_Collect_CivilUnrest_name", "PassengerMission":false, "Expires":0 }, { "MissionID":429236850, "Name":"Mission_Collect_CivilUnrest_name", "PassengerMission":false, "Expires":0 }, { "MissionID":429329450, "Name":"Mission_Massacre_Conflict_War_name", "PassengerMission":false, "Expires":0 }, { "MissionID":429329461, "Name":"Mission_Massacre_Conflict_War_name", "PassengerMission":false, "Expires":0 }, { "MissionID":429329471, "Name":"Mission_Massacre_Conflict_War_name", "PassengerMission":false, "Expires":0 }, { "MissionID":429329481, "Name":"Mission_Massacre_Conflict_War_name", "PassengerMission":false, "Expires":0 }, { "MissionID":429329489, "Name":"Mission_Massacre_Conflict_War_name", "PassengerMission":false, "Expires":0 } ], "Failed":[  ], "Complete":[  ] }

using System;
using System.Collections.Generic;

namespace ALICE_Events
{
    /// <summary>
    /// Object Data Class
    /// </summary>
    public class Missions : Base
    {
        public string Active { get; set; }
        public string Failed { get; set; }
        public string Complete { get; set; }

        //Default Constructor
        public Missions()
        {
            Active = Str();
            Failed = Str();
            Complete = Str();
        }
    }

    /// <summary>
    /// Event Logic & Data Storage Class
    /// </summary>
    public class Event_Missions : Event
    {
        //No Processing
    }
}