//Code Generated By Project A.L.I.C.E Developer Toolkit
//Class File Generated: 01/18/2026 4:27 PM
//Source Journal Line: { "timestamp":"2026-01-17T18:58:45Z", "event":"PayFines", "Amount":250, "AllFines":true, "ShipID":8, "BrokerPercentage":25.000000 }

using System;
using System.Collections.Generic;

namespace ALICE_Events
{
    public class Event_PayFines : Event_Base
    {
        public Event_PayFines()
        {
            Name = "PayFines";
        }

        public void Logic()
        {
            if (Manager.WriteVariables && WriteVariables)
            {
                try
                {
                    Variables_Clear();
                    Variables_Generate();
                    Variables_Write();
                }
                catch (Exception ex)
                {
                    Internal.Exception(Name, "An Exception Occured While Updating Variables");
                    Internal.Exception(Name, "Exception: " + ex);
                }
            }

            //GameState.Logic_PayFines((PayFines)GetEvent());

            TriggerEvent();
        }

        public void Variables_Generate()
        {
            PayFines Event = (PayFines)Manager.GetEvent(Name);

            Variables.Clear();

            #region Custom Variables

            #endregion

            #region Event Variables
            Variable_Craft("Amount", Event.Amount.ToString());
            Variable_Craft("AllFines", Event.AllFines.ToString());
            Variable_Craft("ShipID", Event.ShipID.ToString());
            Variable_Craft("BrokerPercentage", Event.BrokerPercentage.ToString());
            #endregion
        }
    }

    #region PayFines Event
    public class PayFines : Base
    {
        public decimal Amount { get; set; }
        public string AllFines { get; set; }
        public decimal ShipID { get; set; }
        public decimal BrokerPercentage { get; set; }
    }
    #endregion
}


//Journal Reader Code Chunk.

// else if (EventName == "PayFines")
// {
//     var Event = JsonConvert.DeserializeObject<ALICE_Events.PayFines>(RawLine);
//     Manager.UpdateEvents(EventName, Event);
//     Manager.PayFines.Logic();
// }
