//Code Generated By Project A.L.I.C.E Developer Toolkit
//Class File Generated: 01/18/2026 4:27 PM
//Source Journal Line: { "timestamp":"2026-01-07T16:55:36Z", "event":"FetchRemoteModule", "StorageSlot":119, "StoredItem":"$int_powerdistributor_size6_class1_name;", "StoredItem_Localised":"Power Distributor", "ServerId":128064203, "TransferCost":848, "TransferTime":1864, "Ship":"krait_mkii", "ShipID":7 }

using System;

namespace ALICE_Events
{
    public class Event_FetchRemoteModule : Event_Base
    {
        public Event_FetchRemoteModule()
        {
            Name = "FetchRemoteModule";
        }

        public void Logic()
        {
            if (Manager.WriteVariables && WriteVariables)
            {
                    Variables_Clear();
                    Variables_Generate();
                    Variables_Write();
            }

            //GameState.Logic_FetchRemoteModule((FetchRemoteModule)GetEvent());

            TriggerEvent();
        }

        public void Variables_Generate()
        {
            FetchRemoteModule Event = (FetchRemoteModule)Manager.GetEvent(Name);

            Variables.Clear();

            #region Custom Variables

            #endregion

            #region Event Variables
            Variable_Craft("StorageSlot", Event.StorageSlot.ToString());
            Variable_Craft("StoredItem", Event.StoredItem.ToString());
            Variable_Craft("StoredItem_Localised", Event.StoredItem_Localised.ToString());
            Variable_Craft("ServerId", Event.ServerId.ToString());
            Variable_Craft("TransferCost", Event.TransferCost.ToString());
            Variable_Craft("TransferTime", Event.TransferTime.ToString());
            Variable_Craft("Ship", Event.Ship.ToString());
            Variable_Craft("ShipID", Event.ShipID.ToString());
            #endregion
        }
    }

    #region FetchRemoteModule Event
    public class FetchRemoteModule : Base
    {
        public decimal StorageSlot { get; set; }
        public string StoredItem { get; set; }
        public string StoredItem_Localised { get; set; }
        public decimal ServerId { get; set; }
        public decimal TransferCost { get; set; }
        public decimal TransferTime { get; set; }
        public string Ship { get; set; }
        public decimal ShipID { get; set; }
    }
    #endregion
}


//Journal Reader Code Chunk.

// else if (EventName == "FetchRemoteModule")
// {
//     var Event = JsonConvert.DeserializeObject<ALICE_Events.FetchRemoteModule>(RawLine);
//     Manager.UpdateEvents(EventName, Event);
//     Manager.FetchRemoteModule.Logic();
// }
