//Code Generated By Project A.L.I.C.E Developer Toolkit
//Class File Generated: 01/18/2026 4:27 PM
//Source Journal Line: { "timestamp":"2026-01-10T14:16:20Z", "event":"WingJoin", "Others":[] }

using System;
using System.Collections.Generic;

namespace ALICE_Events
{
    public class Event_WingJoin : Event_Base
    {
        public Event_WingJoin()
        {
            Name = "WingJoin";
        }

        public void Logic()
        {
            if (Manager.WriteVariables && WriteVariables)
            {
                try
                {
                    Variables_Clear();
                    Variables_Generate();
                    Variables_Write();
                }
            }

            //GameState.Logic_WingJoin((WingJoin)GetEvent());

            TriggerEvent();
        }

        public void Variables_Generate()
        {
            WingJoin Event = (WingJoin)Manager.GetEvent(Name);

            Variables.Clear();

            #region Custom Variables

            #endregion

            #region Event Variables
            Variable_Craft("Others", Event.Others.ToString());
            #endregion
        }
    }

    #region WingJoin Event
    public class WingJoin : Base
    {
        public string Others { get; set; }
    }
    #endregion
}


//Journal Reader Code Chunk.

// else if (EventName == "WingJoin")
// {
//     var Event = JsonConvert.DeserializeObject<ALICE_Events.WingJoin>(RawLine);
//     Manager.UpdateEvents(EventName, Event);
//     Manager.WingJoin.Logic();
// }
