//Code Generated By Project A.L.I.C.E Developer Toolkit
//Class File Generated: 01/18/2026 4:27 PM
//Source Journal Line: { "timestamp":"2026-01-10T23:07:41Z", "event":"FactionKillBond", "Reward":11858, "AwardingFaction":"People's Kurmodiae Resistance", "VictimFaction":"Kurmodiae Services" }

using System;
using System.Collections.Generic;

namespace ALICE_Events
{
    public class Event_FactionKillBond : Event_Base
    {
        public Event_FactionKillBond()
        {
            Name = "FactionKillBond";
        }

        public void Logic()
        {
            if (Manager.WriteVariables && WriteVariables)
            {
                try
                {
                    Variables_Clear();
                    Variables_Generate();
                    Variables_Write();
                }
            }

            //GameState.Logic_FactionKillBond((FactionKillBond)GetEvent());

            TriggerEvent();
        }

        public void Variables_Generate()
        {
            FactionKillBond Event = (FactionKillBond)Manager.GetEvent(Name);

            Variables.Clear();

            #region Custom Variables

            #endregion

            #region Event Variables
            Variable_Craft("Reward", Event.Reward.ToString());
            Variable_Craft("AwardingFaction", Event.AwardingFaction.ToString());
            Variable_Craft("VictimFaction", Event.VictimFaction.ToString());
            #endregion
        }
    }

    #region FactionKillBond Event
    public class FactionKillBond : Base
    {
        public decimal Reward { get; set; }
        public string AwardingFaction { get; set; }
        public string VictimFaction { get; set; }
    }
    #endregion
}


//Journal Reader Code Chunk.

// else if (EventName == "FactionKillBond")
// {
//     var Event = JsonConvert.DeserializeObject<ALICE_Events.FactionKillBond>(RawLine);
//     Manager.UpdateEvents(EventName, Event);
//     Manager.FactionKillBond.Logic();
// }
