//Code Generated By Project A.L.I.C.E Developer Toolkit
//Class File Generated: 01/18/2026 4:27 PM
//Source Journal Line: { "timestamp":"2026-01-16T17:15:06Z", "event":"RepairAll", "Cost":108657 }

using System;
using System.Collections.Generic;

namespace ALICE_Events
{
    public class Event_RepairAll : Event_Base
    {
        public Event_RepairAll()
        {
            Name = "RepairAll";
        }

        public void Logic()
        {
            if (Manager.WriteVariables && WriteVariables)
            {
                try
                {
                    Variables_Clear();
                    Variables_Generate();
                    Variables_Write();
                }
            }

            //GameState.Logic_RepairAll((RepairAll)GetEvent());

            TriggerEvent();
        }

        public void Variables_Generate()
        {
            RepairAll Event = (RepairAll)Manager.GetEvent(Name);

            Variables.Clear();

            #region Custom Variables

            #endregion

            #region Event Variables
            Variable_Craft("Cost", Event.Cost.ToString());
            #endregion
        }
    }

    #region RepairAll Event
    public class RepairAll : Base
    {
        public decimal Cost { get; set; }
    }
    #endregion
}


//Journal Reader Code Chunk.

// else if (EventName == "RepairAll")
// {
//     var Event = JsonConvert.DeserializeObject<ALICE_Events.RepairAll>(RawLine);
//     Manager.UpdateEvents(EventName, Event);
//     Manager.RepairAll.Logic();
// }
