//Code Generated By Project A.L.I.C.E Developer Toolkit
//Class File Generated: 01/18/2026 4:27 PM
//Source Journal Line: { "timestamp":"2026-01-07T15:31:47Z", "event":"CarrierBuy", "CarrierType":"SquadronCarrier", "CarrierID":3714546688, "BoughtAtMarket":128037376, "Location":"Marrallang", "SystemAddress":5031788942042, "Price":25000000000, "Variant":"CarrierDockB_Squadron", "Callsign":"QZQ-08V" }

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using ALICE_Ships_Datalink_Interface;
using ALICE_Command_Interface;
using ALICE_Internal;

namespace ALICE_Events
{
    public class Event_CarrierBuy : Event_Base
    {
        public Event_CarrierBuy()
        {
            Name = "CarrierBuy";
        }

        public void Logic()
        {
            if (Manager.WriteVariables && WriteVariables)
            {
                try
                {
                    Variables_Clear();
                    Variables_Generate();
                    Variables_Write();
                }
                catch (Exception ex)
                {
                    Internal.Exception(Name, "An Exception Occured While Updating Variables");
                    Internal.Exception(Name, "Exception: " + ex);
                }
            }

            //GameState.Logic_CarrierBuy((CarrierBuy)GetEvent());

            TriggerEvent();
        }

        public void Variables_Generate()
        {
            CarrierBuy Event = (CarrierBuy)Manager.GetEvent(Name);

            Variables.Clear();

            #region Custom Variables

            #endregion

            #region Event Variables
            Variable_Craft("CarrierType", Event.CarrierType.ToString());
            Variable_Craft("CarrierID", Event.CarrierID.ToString());
            Variable_Craft("BoughtAtMarket", Event.BoughtAtMarket.ToString());
            Variable_Craft("Location", Event.Location.ToString());
            Variable_Craft("SystemAddress", Event.SystemAddress.ToString());
            Variable_Craft("Price", Event.Price.ToString());
            Variable_Craft("Variant", Event.Variant.ToString());
            Variable_Craft("Callsign", Event.Callsign.ToString());
            #endregion
        }
    }

    #region CarrierBuy Event
    public class CarrierBuy : Base
    {
        public string CarrierType { get; set; }
        public decimal CarrierID { get; set; }
        public decimal BoughtAtMarket { get; set; }
        public string Location { get; set; }
        public decimal SystemAddress { get; set; }
        public decimal Price { get; set; }
        public string Variant { get; set; }
        public string Callsign { get; set; }
    }
    #endregion
}


//Journal Reader Code Chunk.

// else if (EventName == "CarrierBuy")
// {
//     var Event = JsonConvert.DeserializeObject<ALICE_Events.CarrierBuy>(RawLine);
//     Manager.UpdateEvents(EventName, Event);
//     Manager.CarrierBuy.Logic();
// }
