//Code Generated By Project A.L.I.C.E Developer Toolkit
//Class File Generated: 01/18/2026 4:27 PM
//Source Journal Line: { "timestamp":"2026-01-15T17:44:03Z", "event":"EscapeInterdiction", "Interdictor":"Stanley Xander Byford", "IsPlayer":false }

using System;
using System.Collections.Generic;

namespace ALICE_Events
{
    public class Event_EscapeInterdiction : Event_Base
    {
        public Event_EscapeInterdiction()
        {
            Name = "EscapeInterdiction";
        }

        public void Logic()
        {
            if (Manager.WriteVariables && WriteVariables)
            {
                try
                {
                    Variables_Clear();
                    Variables_Generate();
                    Variables_Write();
                }
                catch (Exception ex)
                {
                    Internal.Exception(Name, "An Exception Occured While Updating Variables");
                    Internal.Exception(Name, "Exception: " + ex);
                }
            }

            //GameState.Logic_EscapeInterdiction((EscapeInterdiction)GetEvent());

            TriggerEvent();
        }

        public void Variables_Generate()
        {
            EscapeInterdiction Event = (EscapeInterdiction)Manager.GetEvent(Name);

            Variables.Clear();

            #region Custom Variables

            #endregion

            #region Event Variables
            Variable_Craft("Interdictor", Event.Interdictor.ToString());
            Variable_Craft("IsPlayer", Event.IsPlayer.ToString());
            #endregion
        }
    }

    #region EscapeInterdiction Event
    public class EscapeInterdiction : Base
    {
        public string Interdictor { get; set; }
        public string IsPlayer { get; set; }
    }
    #endregion
}


//Journal Reader Code Chunk.

// else if (EventName == "EscapeInterdiction")
// {
//     var Event = JsonConvert.DeserializeObject<ALICE_Events.EscapeInterdiction>(RawLine);
//     Manager.UpdateEvents(EventName, Event);
//     Manager.EscapeInterdiction.Logic();
// }
