//Code Generated By Project A.L.I.C.E Developer Toolkit
//Class File Generated: 11/12/2018 1:27 AM
//Source Journal Line: { "timestamp":"2018-10-03T04:32:45Z", "event":"DockSRV" }

using ALICE_Debug;
using ALICE_Status;
using System;

namespace ALICE_Events
{
    /// <summary>
    /// Object Data Class
    /// </summary>
    public class DockSRV : Base
    {
        public string SRVType { get; set; }
        public string SRVType_Localised { get; set; }
        public decimal ID { get; set; }

        //Default Constructor
        public DockSRV()
        {
            SRVType = Str();
            SRVType_Localised = Str();
            ID = Dec();
        }
    }

    /// <summary>
    /// Event Logic & Data Storage Class
    /// </summary>
    public class Event_DockSRV : Event
    {
        //Plugin Property Aligment
        public override void Alignment(object O)
        {
            try
            {
                IStatus.Touchdown = true;               
                ISet.Status.LandingGear(ClassName, true);
                IStatus.Fighter.Deployed = false;
                IStatus.CargoScoop = false;
                IStatus.Supercruise = false;
                IStatus.Hyperspace = false;
                IStatus.Docking.Docked = false;
                IStatus.Hardpoints = false;
            }
            catch (Exception ex)
            {
                ExceptionAlignment(Name, ex);
            }
        }
    }
}
