//Code Generated By Project A.L.I.C.E Developer Toolkit
//Class File Generated: 01/18/2026 4:27 PM
//Source Journal Line: { "timestamp":"2026-01-12T12:26:06Z", "event":"Cargo", "Vessel":"Ship", "Count":400, "Inventory":[ { "Name":"wine", "Count":400, "Stolen":0 } ] }

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using ALICE_Ships_Datalink_Interface;
using ALICE_Command_Interface;
using ALICE_Internal;

namespace ALICE_Events
{
    public class Event_Cargo : Event_Base
    {
        public Event_Cargo()
        {
            Name = "Cargo";
        }

        public void Logic()
        {
            if (Manager.WriteVariables && WriteVariables)
            {
                try
                {
                    Variables_Clear();
                    Variables_Generate();
                    Variables_Write();
                }
            }

            //GameState.Logic_Cargo((Cargo)GetEvent());

            TriggerEvent();
        }

        public void Variables_Generate()
        {
            Cargo Event = (Cargo)Manager.GetEvent(Name);

            Variables.Clear();

            #region Custom Variables

            #endregion

            #region Event Variables
            Variable_Craft("Vessel", Event.Vessel.ToString());
            Variable_Craft("Count", Event.Count.ToString());
            Variable_Craft("Inventory", Event.Inventory.ToString());
            #endregion
        }
    }

    #region Cargo Event
    public class Cargo : Base
    {
        public string Vessel { get; set; }
        public decimal Count { get; set; }
        public string Inventory { get; set; }
    }
    #endregion
}


//Journal Reader Code Chunk.

// else if (EventName == "Cargo")
// {
//     var Event = JsonConvert.DeserializeObject<ALICE_Events.Cargo>(RawLine);
//     Manager.UpdateEvents(EventName, Event);
//     Manager.Cargo.Logic();
// }
