//Code Generated By Project A.L.I.C.E Developer Toolkit
//Class File Generated: 01/18/2026 4:27 PM
//Source Journal Line: { "timestamp":"2026-01-07T15:33:51Z", "event":"CarrierCrewServices", "CarrierID":3714546688, "CarrierType":"SquadronCarrier", "CrewRole":"Exploration", "Operation":"Activate", "CrewName":"Aarohi Steiner" }

using System;

namespace ALICE_Events
{
    public class Event_CarrierCrewServices : Event_Base
    {
        public Event_CarrierCrewServices()
        {
            Name = "CarrierCrewServices";
        }

        public void Logic()
        {
            if (Manager.WriteVariables && WriteVariables)
            {
                    Variables_Clear();
                    Variables_Generate();
                    Variables_Write();
            }

            //GameState.Logic_CarrierCrewServices((CarrierCrewServices)GetEvent());

            TriggerEvent();
        }

        public void Variables_Generate()
        {
            CarrierCrewServices Event = (CarrierCrewServices)Manager.GetEvent(Name);

            Variables.Clear();

            #region Custom Variables

            #endregion

            #region Event Variables
            Variable_Craft("CarrierID", Event.CarrierID.ToString());
            Variable_Craft("CarrierType", Event.CarrierType.ToString());
            Variable_Craft("CrewRole", Event.CrewRole.ToString());
            Variable_Craft("Operation", Event.Operation.ToString());
            Variable_Craft("CrewName", Event.CrewName.ToString());
            #endregion
        }
    }

    #region CarrierCrewServices Event
    public class CarrierCrewServices : Base
    {
        public decimal CarrierID { get; set; }
        public string CarrierType { get; set; }
        public string CrewRole { get; set; }
        public string Operation { get; set; }
        public string CrewName { get; set; }
    }
    #endregion
}


//Journal Reader Code Chunk.

// else if (EventName == "CarrierCrewServices")
// {
//     var Event = JsonConvert.DeserializeObject<ALICE_Events.CarrierCrewServices>(RawLine);
//     Manager.UpdateEvents(EventName, Event);
//     Manager.CarrierCrewServices.Logic();
// }
