//Code Generated By Project A.L.I.C.E Developer Toolkit
//Class File Generated: 01/18/2026 4:27 PM
//Source Journal Line: { "timestamp":"2026-01-10T11:02:19Z", "event":"Repair", "Items":[ "$diamondbackxl_cockpit_name;", "Hull", "$modularcargobaydoor_name;", "Wear" ], "Cost":2196 }

using System;
using System.Collections.Generic;

namespace ALICE_Events
{
    public class Event_Repair : Event_Base
    {
        public Event_Repair()
        {
            Name = "Repair";
        }

        public void Logic()
        {
            if (Manager.WriteVariables && WriteVariables)
            {
                try
                {
                    Variables_Clear();
                    Variables_Generate();
                    Variables_Write();
                }
                catch (Exception ex)
                {
                    Internal.Exception(Name, "An Exception Occured While Updating Variables");
                    Internal.Exception(Name, "Exception: " + ex);
                }
            }

            //GameState.Logic_Repair((Repair)GetEvent());

            TriggerEvent();
        }

        public void Variables_Generate()
        {
            Repair Event = (Repair)Manager.GetEvent(Name);

            Variables.Clear();

            #region Custom Variables

            #endregion

            #region Event Variables
            Variable_Craft("Items", Event.Items.ToString());
            Variable_Craft("Cost", Event.Cost.ToString());
            #endregion
        }
    }

    #region Repair Event
    public class Repair : Base
    {
        public string Items { get; set; }
        public decimal Cost { get; set; }
    }
    #endregion
}


//Journal Reader Code Chunk.

// else if (EventName == "Repair")
// {
//     var Event = JsonConvert.DeserializeObject<ALICE_Events.Repair>(RawLine);
//     Manager.UpdateEvents(EventName, Event);
//     Manager.Repair.Logic();
// }
