//Code Generated By Project A.L.I.C.E Developer Toolkit
//Class File Generated: 01/18/2026 4:27 PM
//Source Journal Line: { "timestamp":"2026-01-17T19:24:53Z", "event":"MaterialCollected", "Category":"Encoded", "Name":"shieldpatternanalysis", "Name_Localised":"Aberrant Shield Pattern Analysis", "Count":3 }

using System;

namespace ALICE_Events
{
    public class Event_MaterialCollected : Event_Base
    {
        public Event_MaterialCollected()
        {
            Name = "MaterialCollected";
        }

        public void Logic()
        {
            if (Manager.WriteVariables && WriteVariables)
            {
                    Variables_Clear();
                    Variables_Generate();
                    Variables_Write();
            }

            //GameState.Logic_MaterialCollected((MaterialCollected)GetEvent());

            TriggerEvent();
        }

        public void Variables_Generate()
        {
            MaterialCollected Event = (MaterialCollected)Manager.GetEvent(Name);

            Variables.Clear();

            #region Custom Variables

            #endregion

            #region Event Variables
            Variable_Craft("Category", Event.Category.ToString());
            Variable_Craft("Name", Event.Name.ToString());
            Variable_Craft("Name_Localised", Event.Name_Localised.ToString());
            Variable_Craft("Count", Event.Count.ToString());
            #endregion
        }
    }

    #region MaterialCollected Event
    public class MaterialCollected : Base
    {
        public string Category { get; set; }
        public string Name { get; set; }
        public string Name_Localised { get; set; }
        public decimal Count { get; set; }
    }
    #endregion
}


//Journal Reader Code Chunk.

// else if (EventName == "MaterialCollected")
// {
//     var Event = JsonConvert.DeserializeObject<ALICE_Events.MaterialCollected>(RawLine);
//     Manager.UpdateEvents(EventName, Event);
//     Manager.MaterialCollected.Logic();
// }
