//Code Generated By Project A.L.I.C.E Developer Toolkit
//Class File Generated: 01/18/2026 4:27 PM
//Source Journal Line: { "timestamp":"2026-01-10T21:41:35Z", "event":"UseConsumable", "Name":"energycell", "Name_Localised":"Energy Cell", "Type":"Consumable" }

using System;
using System.Collections.Generic;

namespace ALICE_Events
{
    public class Event_UseConsumable : Event_Base
    {
        public Event_UseConsumable()
        {
            Name = "UseConsumable";
        }

        public void Logic()
        {
            if (Manager.WriteVariables && WriteVariables)
            {
                try
                {
                    Variables_Clear();
                    Variables_Generate();
                    Variables_Write();
                }
                catch (Exception ex)
                {
                    Internal.Exception(Name, "An Exception Occured While Updating Variables");
                    Internal.Exception(Name, "Exception: " + ex);
                }
            }

            //GameState.Logic_UseConsumable((UseConsumable)GetEvent());

            TriggerEvent();
        }

        public void Variables_Generate()
        {
            UseConsumable Event = (UseConsumable)Manager.GetEvent(Name);

            Variables.Clear();

            #region Custom Variables

            #endregion

            #region Event Variables
            Variable_Craft("Name", Event.Name.ToString());
            Variable_Craft("Name_Localised", Event.Name_Localised.ToString());
            Variable_Craft("Type", Event.Type.ToString());
            #endregion
        }
    }

    #region UseConsumable Event
    public class UseConsumable : Base
    {
        public string Name { get; set; }
        public string Name_Localised { get; set; }
        public string Type { get; set; }
    }
    #endregion
}


//Journal Reader Code Chunk.

// else if (EventName == "UseConsumable")
// {
//     var Event = JsonConvert.DeserializeObject<ALICE_Events.UseConsumable>(RawLine);
//     Manager.UpdateEvents(EventName, Event);
//     Manager.UseConsumable.Logic();
// }
