//Code Generated By Project A.L.I.C.E Developer Toolkit
//Class File Generated: 01/18/2026 4:27 PM
//Source Journal Line: { "timestamp":"2026-01-17T19:28:47Z", "event":"FSSSignalDiscovered", "SystemAddress":5361730210696, "SignalName":"$USS_HighGradeEmissions;", "SignalName_Localised":"Unidentified signal source", "SignalType":"USS", "USSType":"$USS_Type_ValuableSalvage;", "USSType_Localised":"Encoded emissions", "SpawningState":"$FactionState_Expansion_desc;", "SpawningState_Localised":"Expansion represents a factions intention to spread into a nearby system in the near future.", "SpawningFaction":"German Pilot Lounge", "ThreatLevel":0, "TimeRemaining":1908.215576 }

using System;

namespace ALICE_Events
{
    public class Event_FSSSignalDiscovered : Event_Base
    {
        public Event_FSSSignalDiscovered()
        {
            Name = "FSSSignalDiscovered";
        }

        public void Logic()
        {
            if (Manager.WriteVariables && WriteVariables)
            {
                    Variables_Clear();
                    Variables_Generate();
                    Variables_Write();
            }

            //GameState.Logic_FSSSignalDiscovered((FSSSignalDiscovered)GetEvent());

            TriggerEvent();
        }

        public void Variables_Generate()
        {
            FSSSignalDiscovered Event = (FSSSignalDiscovered)Manager.GetEvent(Name);

            Variables.Clear();

            #region Custom Variables

            #endregion

            #region Event Variables
            Variable_Craft("SystemAddress", Event.SystemAddress.ToString());
            Variable_Craft("SignalName", Event.SignalName.ToString());
            Variable_Craft("SignalName_Localised", Event.SignalName_Localised.ToString());
            Variable_Craft("SignalType", Event.SignalType.ToString());
            Variable_Craft("USSType", Event.USSType.ToString());
            Variable_Craft("USSType_Localised", Event.USSType_Localised.ToString());
            Variable_Craft("SpawningState", Event.SpawningState.ToString());
            Variable_Craft("SpawningState_Localised", Event.SpawningState_Localised.ToString());
            Variable_Craft("SpawningFaction", Event.SpawningFaction.ToString());
            Variable_Craft("ThreatLevel", Event.ThreatLevel.ToString());
            Variable_Craft("TimeRemaining", Event.TimeRemaining.ToString());
            #endregion
        }
    }

    #region FSSSignalDiscovered Event
    public class FSSSignalDiscovered : Base
    {
        public decimal SystemAddress { get; set; }
        public string SignalName { get; set; }
        public string SignalName_Localised { get; set; }
        public string SignalType { get; set; }
        public string USSType { get; set; }
        public string USSType_Localised { get; set; }
        public string SpawningState { get; set; }
        public string SpawningState_Localised { get; set; }
        public string SpawningFaction { get; set; }
        public decimal ThreatLevel { get; set; }
        public decimal TimeRemaining { get; set; }
    }
    #endregion
}


//Journal Reader Code Chunk.

// else if (EventName == "FSSSignalDiscovered")
// {
//     var Event = JsonConvert.DeserializeObject<ALICE_Events.FSSSignalDiscovered>(RawLine);
//     Manager.UpdateEvents(EventName, Event);
//     Manager.FSSSignalDiscovered.Logic();
// }
