//Code Generated By Project A.L.I.C.E Developer Toolkit
//Class File Generated: 01/18/2026 4:27 PM
//Source Journal Line: { "timestamp":"2026-01-10T18:41:01Z", "event":"NavBeaconScan", "SystemAddress":4923919960435, "NumBodies":71 }

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using ALICE_Ships_Datalink_Interface;
using ALICE_Command_Interface;
using ALICE_Internal;

namespace ALICE_Events
{
    public class Event_NavBeaconScan : Event_Base
    {
        public Event_NavBeaconScan()
        {
            Name = "NavBeaconScan";
        }

        public void Logic()
        {
            if (Manager.WriteVariables && WriteVariables)
            {
                try
                {
                    Variables_Clear();
                    Variables_Generate();
                    Variables_Write();
                }
            }

            //GameState.Logic_NavBeaconScan((NavBeaconScan)GetEvent());

            TriggerEvent();
        }

        public void Variables_Generate()
        {
            NavBeaconScan Event = (NavBeaconScan)Manager.GetEvent(Name);

            Variables.Clear();

            #region Custom Variables

            #endregion

            #region Event Variables
            Variable_Craft("SystemAddress", Event.SystemAddress.ToString());
            Variable_Craft("NumBodies", Event.NumBodies.ToString());
            #endregion
        }
    }

    #region NavBeaconScan Event
    public class NavBeaconScan : Base
    {
        public decimal SystemAddress { get; set; }
        public decimal NumBodies { get; set; }
    }
    #endregion
}


//Journal Reader Code Chunk.

// else if (EventName == "NavBeaconScan")
// {
//     var Event = JsonConvert.DeserializeObject<ALICE_Events.NavBeaconScan>(RawLine);
//     Manager.UpdateEvents(EventName, Event);
//     Manager.NavBeaconScan.Logic();
// }
