//Code Generated By Project A.L.I.C.E Developer Toolkit
//Class File Generated: 01/18/2026 4:27 PM
//Source Journal Line: { "timestamp":"2026-01-15T17:51:50Z", "event":"SupercruiseExit", "Taxi":false, "Multicrew":false, "StarSystem":"Rho Ophiuchi Sector IH-U b3-1", "SystemAddress":2870783649369, "Body":"Rho Ophiuchi Sector IH-U b3-1", "BodyID":0, "BodyType":"Star" }

using System;
using System.Collections.Generic;

namespace ALICE_Events
{
    public class Event_SupercruiseExit : Event_Base
    {
        public Event_SupercruiseExit()
        {
            Name = "SupercruiseExit";
        }

        public void Logic()
        {
            if (Manager.WriteVariables && WriteVariables)
            {
                try
                {
                    Variables_Clear();
                    Variables_Generate();
                    Variables_Write();
                }
                catch (Exception ex)
                {
                    Internal.Exception(Name, "An Exception Occured While Updating Variables");
                    Internal.Exception(Name, "Exception: " + ex);
                }
            }

            //GameState.Logic_SupercruiseExit((SupercruiseExit)GetEvent());

            TriggerEvent();
        }

        public void Variables_Generate()
        {
            SupercruiseExit Event = (SupercruiseExit)Manager.GetEvent(Name);

            Variables.Clear();

            #region Custom Variables

            #endregion

            #region Event Variables
            Variable_Craft("Taxi", Event.Taxi.ToString());
            Variable_Craft("Multicrew", Event.Multicrew.ToString());
            Variable_Craft("StarSystem", Event.StarSystem.ToString());
            Variable_Craft("SystemAddress", Event.SystemAddress.ToString());
            Variable_Craft("Body", Event.Body.ToString());
            Variable_Craft("BodyID", Event.BodyID.ToString());
            Variable_Craft("BodyType", Event.BodyType.ToString());
            #endregion
        }
    }

    #region SupercruiseExit Event
    public class SupercruiseExit : Base
    {
        public string Taxi { get; set; }
        public string Multicrew { get; set; }
        public string StarSystem { get; set; }
        public decimal SystemAddress { get; set; }
        public string Body { get; set; }
        public decimal BodyID { get; set; }
        public string BodyType { get; set; }
    }
    #endregion
}


//Journal Reader Code Chunk.

// else if (EventName == "SupercruiseExit")
// {
//     var Event = JsonConvert.DeserializeObject<ALICE_Events.SupercruiseExit>(RawLine);
//     Manager.UpdateEvents(EventName, Event);
//     Manager.SupercruiseExit.Logic();
// }
