//Code Generated By Project A.L.I.C.E Developer Toolkit
//Class File Generated: 01/18/2026 4:27 PM
//Source Journal Line: { "timestamp":"2026-01-10T15:04:40Z", "event":"RefuelAll", "Cost":545, "Amount":10.868427 }

using System;

namespace ALICE_Events
{
    public class Event_RefuelAll : Event_Base
    {
        public Event_RefuelAll()
        {
            Name = "RefuelAll";
        }

        public void Logic()
        {
            if (Manager.WriteVariables && WriteVariables)
            {
                    Variables_Clear();
                    Variables_Generate();
                    Variables_Write();
            }

            //GameState.Logic_RefuelAll((RefuelAll)GetEvent());

            TriggerEvent();
        }

        public void Variables_Generate()
        {
            RefuelAll Event = (RefuelAll)Manager.GetEvent(Name);

            Variables.Clear();

            #region Custom Variables

            #endregion

            #region Event Variables
            Variable_Craft("Cost", Event.Cost.ToString());
            Variable_Craft("Amount", Event.Amount.ToString());
            #endregion
        }
    }

    #region RefuelAll Event
    public class RefuelAll : Base
    {
        public decimal Cost { get; set; }
        public decimal Amount { get; set; }
    }
    #endregion
}


//Journal Reader Code Chunk.

// else if (EventName == "RefuelAll")
// {
//     var Event = JsonConvert.DeserializeObject<ALICE_Events.RefuelAll>(RawLine);
//     Manager.UpdateEvents(EventName, Event);
//     Manager.RefuelAll.Logic();
// }
