//Code Generated By Project A.L.I.C.E Developer Toolkit
//Class File Generated: 01/18/2026 4:27 PM
//Source Journal Line: { "timestamp":"2026-01-10T12:46:06Z", "event":"Friends", "Status":"Requested", "Name":"RIPTHEREAPER" }

using System;

namespace ALICE_Events
{
    public class Event_Friends : Event_Base
    {
        public Event_Friends()
        {
            Name = "Friends";
        }

        public void Logic()
        {
            if (Manager.WriteVariables && WriteVariables)
            {
                    Variables_Clear();
                    Variables_Generate();
                    Variables_Write();
            }

            //GameState.Logic_Friends((Friends)GetEvent());

            TriggerEvent();
        }

        public void Variables_Generate()
        {
            Friends Event = (Friends)Manager.GetEvent(Name);

            Variables.Clear();

            #region Custom Variables

            #endregion

            #region Event Variables
            Variable_Craft("Status", Event.Status.ToString());
            Variable_Craft("Name", Event.Name.ToString());
            #endregion
        }
    }

    #region Friends Event
    public class Friends : Base
    {
        public string Status { get; set; }
        public string Name { get; set; }
    }
    #endregion
}


//Journal Reader Code Chunk.

// else if (EventName == "Friends")
// {
//     var Event = JsonConvert.DeserializeObject<ALICE_Events.Friends>(RawLine);
//     Manager.UpdateEvents(EventName, Event);
//     Manager.Friends.Logic();
// }
