//Code Generated By Project A.L.I.C.E Developer Toolkit
//Class File Generated: 01/18/2026 4:27 PM
//Source Journal Line: { "timestamp":"2026-01-15T17:42:46Z", "event":"SupercruiseEntry", "Taxi":false, "Multicrew":false, "StarSystem":"Rho Ophiuchi Sector IH-U b3-1", "SystemAddress":2870783649369 }

using System;
using System.Collections.Generic;

namespace ALICE_Events
{
    public class Event_SupercruiseEntry : Event_Base
    {
        public Event_SupercruiseEntry()
        {
            Name = "SupercruiseEntry";
        }

        public void Logic()
        {
            if (Manager.WriteVariables && WriteVariables)
            {
                try
                {
                    Variables_Clear();
                    Variables_Generate();
                    Variables_Write();
                }
                catch (Exception ex)
                {
                    Internal.Exception(Name, "An Exception Occured While Updating Variables");
                    Internal.Exception(Name, "Exception: " + ex);
                }
            }

            //GameState.Logic_SupercruiseEntry((SupercruiseEntry)GetEvent());

            TriggerEvent();
        }

        public void Variables_Generate()
        {
            SupercruiseEntry Event = (SupercruiseEntry)Manager.GetEvent(Name);

            Variables.Clear();

            #region Custom Variables

            #endregion

            #region Event Variables
            Variable_Craft("Taxi", Event.Taxi.ToString());
            Variable_Craft("Multicrew", Event.Multicrew.ToString());
            Variable_Craft("StarSystem", Event.StarSystem.ToString());
            Variable_Craft("SystemAddress", Event.SystemAddress.ToString());
            #endregion
        }
    }

    #region SupercruiseEntry Event
    public class SupercruiseEntry : Base
    {
        public string Taxi { get; set; }
        public string Multicrew { get; set; }
        public string StarSystem { get; set; }
        public decimal SystemAddress { get; set; }
    }
    #endregion
}


//Journal Reader Code Chunk.

// else if (EventName == "SupercruiseEntry")
// {
//     var Event = JsonConvert.DeserializeObject<ALICE_Events.SupercruiseEntry>(RawLine);
//     Manager.UpdateEvents(EventName, Event);
//     Manager.SupercruiseEntry.Logic();
// }
