//Code Generated By Project A.L.I.C.E Developer Toolkit
//Class File Generated: 01/18/2026 4:27 PM
//Source Journal Line: { "timestamp":"2026-01-10T14:10:42Z", "event":"ModuleSellRemote", "StorageSlot":182, "SellItem":"$int_shieldgenerator_size6_class1_name;", "SellItem_Localised":"Shield Generator", "ServerId":128064283, "SellPrice":175277, "Ship":"anaconda", "ShipID":8 }

using System;

namespace ALICE_Events
{
    public class Event_ModuleSellRemote : Event_Base
    {
        public Event_ModuleSellRemote()
        {
            Name = "ModuleSellRemote";
        }

        public void Logic()
        {
            if (Manager.WriteVariables && WriteVariables)
            {
                    Variables_Clear();
                    Variables_Generate();
                    Variables_Write();
            }

            //GameState.Logic_ModuleSellRemote((ModuleSellRemote)GetEvent());

            TriggerEvent();
        }

        public void Variables_Generate()
        {
            ModuleSellRemote Event = (ModuleSellRemote)Manager.GetEvent(Name);

            Variables.Clear();

            #region Custom Variables

            #endregion

            #region Event Variables
            Variable_Craft("StorageSlot", Event.StorageSlot.ToString());
            Variable_Craft("SellItem", Event.SellItem.ToString());
            Variable_Craft("SellItem_Localised", Event.SellItem_Localised.ToString());
            Variable_Craft("ServerId", Event.ServerId.ToString());
            Variable_Craft("SellPrice", Event.SellPrice.ToString());
            Variable_Craft("Ship", Event.Ship.ToString());
            Variable_Craft("ShipID", Event.ShipID.ToString());
            #endregion
        }
    }

    #region ModuleSellRemote Event
    public class ModuleSellRemote : Base
    {
        public decimal StorageSlot { get; set; }
        public string SellItem { get; set; }
        public string SellItem_Localised { get; set; }
        public decimal ServerId { get; set; }
        public decimal SellPrice { get; set; }
        public string Ship { get; set; }
        public decimal ShipID { get; set; }
    }
    #endregion
}


//Journal Reader Code Chunk.

// else if (EventName == "ModuleSellRemote")
// {
//     var Event = JsonConvert.DeserializeObject<ALICE_Events.ModuleSellRemote>(RawLine);
//     Manager.UpdateEvents(EventName, Event);
//     Manager.ModuleSellRemote.Logic();
// }
