//Code Generated By Project A.L.I.C.E Developer Toolkit
//Class File Generated: 01/18/2026 4:27 PM
//Source Journal Line: { "timestamp":"2026-01-17T19:21:53Z", "event":"USSDrop", "USSType":"$USS_Type_WeaponsFire;", "USSType_Localised":"Weapons fire", "USSThreat":1 }

using System;

namespace ALICE_Events
{
    public class Event_USSDrop : Event_Base
    {
        public Event_USSDrop()
        {
            Name = "USSDrop";
        }

        public void Logic()
        {
            if (Manager.WriteVariables && WriteVariables)
            {
                    Variables_Clear();
                    Variables_Generate();
                    Variables_Write();
            }

            //GameState.Logic_USSDrop((USSDrop)GetEvent());

            TriggerEvent();
        }

        public void Variables_Generate()
        {
            USSDrop Event = (USSDrop)Manager.GetEvent(Name);

            Variables.Clear();

            #region Custom Variables

            #endregion

            #region Event Variables
            Variable_Craft("USSType", Event.USSType.ToString());
            Variable_Craft("USSType_Localised", Event.USSType_Localised.ToString());
            Variable_Craft("USSThreat", Event.USSThreat.ToString());
            #endregion
        }
    }

    #region USSDrop Event
    public class USSDrop : Base
    {
        public string USSType { get; set; }
        public string USSType_Localised { get; set; }
        public decimal USSThreat { get; set; }
    }
    #endregion
}


//Journal Reader Code Chunk.

// else if (EventName == "USSDrop")
// {
//     var Event = JsonConvert.DeserializeObject<ALICE_Events.USSDrop>(RawLine);
//     Manager.UpdateEvents(EventName, Event);
//     Manager.USSDrop.Logic();
// }
