//Code Generated By Project A.L.I.C.E Developer Toolkit
//Class File Generated: 01/18/2026 4:27 PM
//Source Journal Line: { "timestamp":"2025-11-12T09:23:03Z", "event":"ModuleInfo" }

using System;
using System.Collections.Generic;

namespace ALICE_Events
{
    public class Event_ModuleInfo : Event_Base
    {
        public Event_ModuleInfo()
        {
            Name = "ModuleInfo";
        }

        public void Logic()
        {
            if (Manager.WriteVariables && WriteVariables)
            {
                try
                {
                    Variables_Clear();
                    Variables_Generate();
                    Variables_Write();
                }
            }

            //GameState.Logic_ModuleInfo((ModuleInfo)GetEvent());

            TriggerEvent();
        }

        public void Variables_Generate()
        {
            ModuleInfo Event = (ModuleInfo)Manager.GetEvent(Name);

            Variables.Clear();

            #region Custom Variables

            #endregion

            #region Event Variables
            #endregion
        }
    }

    #region ModuleInfo Event
    public class ModuleInfo : Base
    {
    }
    #endregion
}


//Journal Reader Code Chunk.

// else if (EventName == "ModuleInfo")
// {
//     var Event = JsonConvert.DeserializeObject<ALICE_Events.ModuleInfo>(RawLine);
//     Manager.UpdateEvents(EventName, Event);
//     Manager.ModuleInfo.Logic();
// }
