//Code Generated By Project A.L.I.C.E Developer Toolkit
//Class File Generated: 01/18/2026 4:27 PM
//Source Journal Line: { "timestamp":"2026-01-08T08:56:42Z", "event":"ShipyardNew", "ShipType":"panthermkii", "ShipType_Localised":"Panther Clipper Mk II", "NewShipID":37 }

using System;
using System.Collections.Generic;

namespace ALICE_Events
{
    public class Event_ShipyardNew : Event_Base
    {
        public Event_ShipyardNew()
        {
            Name = "ShipyardNew";
        }

        public void Logic()
        {
            if (Manager.WriteVariables && WriteVariables)
            {
                try
                {
                    Variables_Clear();
                    Variables_Generate();
                    Variables_Write();
                }
                catch (Exception ex)
                {
                    Internal.Exception(Name, "An Exception Occured While Updating Variables");
                    Internal.Exception(Name, "Exception: " + ex);
                }
            }

            //GameState.Logic_ShipyardNew((ShipyardNew)GetEvent());

            TriggerEvent();
        }

        public void Variables_Generate()
        {
            ShipyardNew Event = (ShipyardNew)Manager.GetEvent(Name);

            Variables.Clear();

            #region Custom Variables

            #endregion

            #region Event Variables
            Variable_Craft("ShipType", Event.ShipType.ToString());
            Variable_Craft("ShipType_Localised", Event.ShipType_Localised.ToString());
            Variable_Craft("NewShipID", Event.NewShipID.ToString());
            #endregion
        }
    }

    #region ShipyardNew Event
    public class ShipyardNew : Base
    {
        public string ShipType { get; set; }
        public string ShipType_Localised { get; set; }
        public decimal NewShipID { get; set; }
    }
    #endregion
}


//Journal Reader Code Chunk.

// else if (EventName == "ShipyardNew")
// {
//     var Event = JsonConvert.DeserializeObject<ALICE_Events.ShipyardNew>(RawLine);
//     Manager.UpdateEvents(EventName, Event);
//     Manager.ShipyardNew.Logic();
// }
