//Code Generated By Project A.L.I.C.E Developer Toolkit
//Class File Generated: 01/18/2026 4:27 PM
//Source Journal Line: { "timestamp":"2026-01-10T21:37:22Z", "event":"Backpack", "Items":[  ], "Components":[  ], "Consumables":[ { "Name":"healthpack", "Name_Localised":"Medkit", "OwnerID":0, "Count":2 }, { "Name":"energycell", "Name_Localised":"Energy Cell", "OwnerID":0, "Count":2 }, { "Name":"amm_grenade_emp", "Name_Localised":"Shield Disruptor", "OwnerID":0, "Count":1 }, { "Name":"amm_grenade_frag", "Name_Localised":"Frag Grenade", "OwnerID":0, "Count":3 }, { "Name":"amm_grenade_shield", "Name_Localised":"Shield Projector", "OwnerID":0, "Count":1 }, { "Name":"bypass", "Name_Localised":"E-Breach", "OwnerID":0, "Count":1 } ], "Data":[  ] }

using System;
using System.Collections.Generic;

namespace ALICE_Events
{
    public class Event_Backpack : Event_Base
    {
        public Event_Backpack()
        {
            Name = "Backpack";
        }

        public void Logic()
        {
            if (Manager.WriteVariables && WriteVariables)
            {
                try
                {
                    Variables_Clear();
                    Variables_Generate();
                    Variables_Write();
                }
                catch (Exception ex)
                {
                    Internal.Exception(Name, "An Exception Occured While Updating Variables");
                    Internal.Exception(Name, "Exception: " + ex);
                }
            }

            //GameState.Logic_Backpack((Backpack)GetEvent());

            TriggerEvent();
        }

        public void Variables_Generate()
        {
            Backpack Event = (Backpack)Manager.GetEvent(Name);

            Variables.Clear();

            #region Custom Variables

            #endregion

            #region Event Variables
            Variable_Craft("Items", Event.Items.ToString());
            Variable_Craft("Components", Event.Components.ToString());
            Variable_Craft("Consumables", Event.Consumables.ToString());
            Variable_Craft("Data", Event.Data.ToString());
            #endregion
        }
    }

    #region Backpack Event
    public class Backpack : Base
    {
        public string Items { get; set; }
        public string Components { get; set; }
        public string Consumables { get; set; }
        public string Data { get; set; }
    }
    #endregion
}


//Journal Reader Code Chunk.

// else if (EventName == "Backpack")
// {
//     var Event = JsonConvert.DeserializeObject<ALICE_Events.Backpack>(RawLine);
//     Manager.UpdateEvents(EventName, Event);
//     Manager.Backpack.Logic();
// }
