//Code Generated By Project A.L.I.C.E Developer Toolkit
//Class File Generated: 01/18/2026 4:27 PM
//Source Journal Line: { "timestamp":"2026-01-17T18:59:51Z", "event":"MissionAccepted", "Faction":"Loan Sharks Mercenary Corps", "Name":"Mission_Massacre_RankFed", "LocalisedName":"Federal Navy Strike Contract", "TargetType":"$MissionUtil_FactionTag_Pirate;", "TargetType_Localised":"Pirates", "TargetFaction":"GD 215 Blue Pirates", "KillCount":5, "DestinationSystem":"GD 215", "DestinationStation":"Faraday Orbital", "Expiry":"2026-01-19T13:08:32Z", "Wing":false, "Influence":"++", "Reputation":"++", "Reward":3159602, "MissionID":1042347155 }

using System;
using System.Collections.Generic;

namespace ALICE_Events
{
    public class Event_MissionAccepted : Event_Base
    {
        public Event_MissionAccepted()
        {
            Name = "MissionAccepted";
        }

        public void Logic()
        {
            if (Manager.WriteVariables && WriteVariables)
            {
                try
                {
                    Variables_Clear();
                    Variables_Generate();
                    Variables_Write();
                }
            }

            //GameState.Logic_MissionAccepted((MissionAccepted)GetEvent());

            TriggerEvent();
        }

        public void Variables_Generate()
        {
            MissionAccepted Event = (MissionAccepted)Manager.GetEvent(Name);

            Variables.Clear();

            #region Custom Variables

            #endregion

            #region Event Variables
            Variable_Craft("Faction", Event.Faction.ToString());
            Variable_Craft("Name", Event.Name.ToString());
            Variable_Craft("LocalisedName", Event.LocalisedName.ToString());
            Variable_Craft("TargetType", Event.TargetType.ToString());
            Variable_Craft("TargetType_Localised", Event.TargetType_Localised.ToString());
            Variable_Craft("TargetFaction", Event.TargetFaction.ToString());
            Variable_Craft("KillCount", Event.KillCount.ToString());
            Variable_Craft("DestinationSystem", Event.DestinationSystem.ToString());
            Variable_Craft("DestinationStation", Event.DestinationStation.ToString());
            Variable_Craft("Expiry", Event.Expiry.ToString());
            Variable_Craft("Wing", Event.Wing.ToString());
            Variable_Craft("Influence", Event.Influence.ToString());
            Variable_Craft("Reputation", Event.Reputation.ToString());
            Variable_Craft("Reward", Event.Reward.ToString());
            Variable_Craft("MissionID", Event.MissionID.ToString());
            #endregion
        }
    }

    #region MissionAccepted Event
    public class MissionAccepted : Base
    {
        public string Faction { get; set; }
        public string Name { get; set; }
        public string LocalisedName { get; set; }
        public string TargetType { get; set; }
        public string TargetType_Localised { get; set; }
        public string TargetFaction { get; set; }
        public decimal KillCount { get; set; }
        public string DestinationSystem { get; set; }
        public string DestinationStation { get; set; }
        public string Expiry { get; set; }
        public string Wing { get; set; }
        public string Influence { get; set; }
        public string Reputation { get; set; }
        public decimal Reward { get; set; }
        public decimal MissionID { get; set; }
    }
    #endregion
}


//Journal Reader Code Chunk.

// else if (EventName == "MissionAccepted")
// {
//     var Event = JsonConvert.DeserializeObject<ALICE_Events.MissionAccepted>(RawLine);
//     Manager.UpdateEvents(EventName, Event);
//     Manager.MissionAccepted.Logic();
// }
