//Code Generated By Project A.L.I.C.E Developer Toolkit
//Class File Generated: 01/18/2026 4:27 PM
//Source Journal Line: { "timestamp":"2026-01-08T08:56:41Z", "event":"ShipyardBuy", "ShipType":"panthermkii", "ShipType_Localised":"Panther Clipper Mk II", "ShipPrice":264433384, "StoreOldShip":"Type8", "StoreShipID":36, "MarketID":128666762 }

using System;
using System.Collections.Generic;

namespace ALICE_Events
{
    public class Event_ShipyardBuy : Event_Base
    {
        public Event_ShipyardBuy()
        {
            Name = "ShipyardBuy";
        }

        public void Logic()
        {
            if (Manager.WriteVariables && WriteVariables)
            {
                try
                {
                    Variables_Clear();
                    Variables_Generate();
                    Variables_Write();
                }
            }

            //GameState.Logic_ShipyardBuy((ShipyardBuy)GetEvent());

            TriggerEvent();
        }

        public void Variables_Generate()
        {
            ShipyardBuy Event = (ShipyardBuy)Manager.GetEvent(Name);

            Variables.Clear();

            #region Custom Variables

            #endregion

            #region Event Variables
            Variable_Craft("ShipType", Event.ShipType.ToString());
            Variable_Craft("ShipType_Localised", Event.ShipType_Localised.ToString());
            Variable_Craft("ShipPrice", Event.ShipPrice.ToString());
            Variable_Craft("StoreOldShip", Event.StoreOldShip.ToString());
            Variable_Craft("StoreShipID", Event.StoreShipID.ToString());
            Variable_Craft("MarketID", Event.MarketID.ToString());
            #endregion
        }
    }

    #region ShipyardBuy Event
    public class ShipyardBuy : Base
    {
        public string ShipType { get; set; }
        public string ShipType_Localised { get; set; }
        public decimal ShipPrice { get; set; }
        public string StoreOldShip { get; set; }
        public decimal StoreShipID { get; set; }
        public decimal MarketID { get; set; }
    }
    #endregion
}


//Journal Reader Code Chunk.

// else if (EventName == "ShipyardBuy")
// {
//     var Event = JsonConvert.DeserializeObject<ALICE_Events.ShipyardBuy>(RawLine);
//     Manager.UpdateEvents(EventName, Event);
//     Manager.ShipyardBuy.Logic();
// }
