//Code Generated By Project A.L.I.C.E Developer Toolkit
//Class File Generated: 01/18/2026 4:27 PM
//Source Journal Line: { "timestamp":"2025-11-12T09:27:45Z", "event":"CarrierDecommission", "CarrierID":3703130368, "CarrierType":"FleetCarrier", "ScrapRefund":5408435600, "ScrapTime":1763622000 }

using System;
using System.Collections.Generic;

namespace ALICE_Events
{
    public class Event_CarrierDecommission : Event_Base
    {
        public Event_CarrierDecommission()
        {
            Name = "CarrierDecommission";
        }

        public void Logic()
        {
            if (Manager.WriteVariables && WriteVariables)
            {
                try
                {
                    Variables_Clear();
                    Variables_Generate();
                    Variables_Write();
                }
            }

            //GameState.Logic_CarrierDecommission((CarrierDecommission)GetEvent());

            TriggerEvent();
        }

        public void Variables_Generate()
        {
            CarrierDecommission Event = (CarrierDecommission)Manager.GetEvent(Name);

            Variables.Clear();

            #region Custom Variables

            #endregion

            #region Event Variables
            Variable_Craft("CarrierID", Event.CarrierID.ToString());
            Variable_Craft("CarrierType", Event.CarrierType.ToString());
            Variable_Craft("ScrapRefund", Event.ScrapRefund.ToString());
            Variable_Craft("ScrapTime", Event.ScrapTime.ToString());
            #endregion
        }
    }

    #region CarrierDecommission Event
    public class CarrierDecommission : Base
    {
        public decimal CarrierID { get; set; }
        public string CarrierType { get; set; }
        public decimal ScrapRefund { get; set; }
        public decimal ScrapTime { get; set; }
    }
    #endregion
}


//Journal Reader Code Chunk.

// else if (EventName == "CarrierDecommission")
// {
//     var Event = JsonConvert.DeserializeObject<ALICE_Events.CarrierDecommission>(RawLine);
//     Manager.UpdateEvents(EventName, Event);
//     Manager.CarrierDecommission.Logic();
// }
