//Code Generated By Project A.L.I.C.E Developer Toolkit
//Class File Generated: 01/18/2026 4:27 PM
//Source Journal Line: { "timestamp":"2026-01-10T15:22:20Z", "event":"ShipyardBankDeposit", "ShipType":"Type8", "ShipType_Localised":"Type-8 Transporter", "MarketID":3714546688 }

using System;

namespace ALICE_Events
{
    public class Event_ShipyardBankDeposit : Event_Base
    {
        public Event_ShipyardBankDeposit()
        {
            Name = "ShipyardBankDeposit";
        }

        public void Logic()
        {
            if (Manager.WriteVariables && WriteVariables)
            {
                    Variables_Clear();
                    Variables_Generate();
                    Variables_Write();
            }

            //GameState.Logic_ShipyardBankDeposit((ShipyardBankDeposit)GetEvent());

            TriggerEvent();
        }

        public void Variables_Generate()
        {
            ShipyardBankDeposit Event = (ShipyardBankDeposit)Manager.GetEvent(Name);

            Variables.Clear();

            #region Custom Variables

            #endregion

            #region Event Variables
            Variable_Craft("ShipType", Event.ShipType.ToString());
            Variable_Craft("ShipType_Localised", Event.ShipType_Localised.ToString());
            Variable_Craft("MarketID", Event.MarketID.ToString());
            #endregion
        }
    }

    #region ShipyardBankDeposit Event
    public class ShipyardBankDeposit : Base
    {
        public string ShipType { get; set; }
        public string ShipType_Localised { get; set; }
        public decimal MarketID { get; set; }
    }
    #endregion
}


//Journal Reader Code Chunk.

// else if (EventName == "ShipyardBankDeposit")
// {
//     var Event = JsonConvert.DeserializeObject<ALICE_Events.ShipyardBankDeposit>(RawLine);
//     Manager.UpdateEvents(EventName, Event);
//     Manager.ShipyardBankDeposit.Logic();
// }
