//Code Generated By Project A.L.I.C.E Developer Toolkit
//Class File Generated: 01/18/2026 4:27 PM
//Source Journal Line: { "timestamp":"2026-01-15T17:58:53Z", "event":"CarrierTradeOrder", "CarrierID":3714546688, "CarrierType":"SquadronCarrier", "BlackMarket":false, "Commodity":"thermalcoolingunits", "Commodity_Localised":"Thermal Cooling Units", "PurchaseOrder":46134, "Price":185 }

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using ALICE_Ships_Datalink_Interface;
using ALICE_Command_Interface;
using ALICE_Internal;

namespace ALICE_Events
{
    public class Event_CarrierTradeOrder : Event_Base
    {
        public Event_CarrierTradeOrder()
        {
            Name = "CarrierTradeOrder";
        }

        public void Logic()
        {
            if (Manager.WriteVariables && WriteVariables)
            {
                try
                {
                    Variables_Clear();
                    Variables_Generate();
                    Variables_Write();
                }
                catch (Exception ex)
                {
                    Internal.Exception(Name, "An Exception Occured While Updating Variables");
                    Internal.Exception(Name, "Exception: " + ex);
                }
            }

            //GameState.Logic_CarrierTradeOrder((CarrierTradeOrder)GetEvent());

            TriggerEvent();
        }

        public void Variables_Generate()
        {
            CarrierTradeOrder Event = (CarrierTradeOrder)Manager.GetEvent(Name);

            Variables.Clear();

            #region Custom Variables

            #endregion

            #region Event Variables
            Variable_Craft("CarrierID", Event.CarrierID.ToString());
            Variable_Craft("CarrierType", Event.CarrierType.ToString());
            Variable_Craft("BlackMarket", Event.BlackMarket.ToString());
            Variable_Craft("Commodity", Event.Commodity.ToString());
            Variable_Craft("Commodity_Localised", Event.Commodity_Localised.ToString());
            Variable_Craft("PurchaseOrder", Event.PurchaseOrder.ToString());
            Variable_Craft("Price", Event.Price.ToString());
            #endregion
        }
    }

    #region CarrierTradeOrder Event
    public class CarrierTradeOrder : Base
    {
        public decimal CarrierID { get; set; }
        public string CarrierType { get; set; }
        public string BlackMarket { get; set; }
        public string Commodity { get; set; }
        public string Commodity_Localised { get; set; }
        public decimal PurchaseOrder { get; set; }
        public decimal Price { get; set; }
    }
    #endregion
}


//Journal Reader Code Chunk.

// else if (EventName == "CarrierTradeOrder")
// {
//     var Event = JsonConvert.DeserializeObject<ALICE_Events.CarrierTradeOrder>(RawLine);
//     Manager.UpdateEvents(EventName, Event);
//     Manager.CarrierTradeOrder.Logic();
// }
