//Code Generated By Project A.L.I.C.E Developer Toolkit
//Class File Generated: 01/18/2026 4:27 PM
//Source Journal Line: { "timestamp":"2026-01-15T17:40:21Z", "event":"Shipyard", "MarketID":3714546688, "StationName":"FXBX", "StarSystem":"Rho Ophiuchi Sector IH-U b3-1" }

using System;
using System.Collections.Generic;

namespace ALICE_Events
{
    public class Event_Shipyard : Event_Base
    {
        public Event_Shipyard()
        {
            Name = "Shipyard";
        }

        public void Logic()
        {
            if (Manager.WriteVariables && WriteVariables)
            {
                try
                {
                    Variables_Clear();
                    Variables_Generate();
                    Variables_Write();
                }
            }

            //GameState.Logic_Shipyard((Shipyard)GetEvent());

            TriggerEvent();
        }

        public void Variables_Generate()
        {
            Shipyard Event = (Shipyard)Manager.GetEvent(Name);

            Variables.Clear();

            #region Custom Variables

            #endregion

            #region Event Variables
            Variable_Craft("MarketID", Event.MarketID.ToString());
            Variable_Craft("StationName", Event.StationName.ToString());
            Variable_Craft("StarSystem", Event.StarSystem.ToString());
            #endregion
        }
    }

    #region Shipyard Event
    public class Shipyard : Base
    {
        public decimal MarketID { get; set; }
        public string StationName { get; set; }
        public string StarSystem { get; set; }
    }
    #endregion
}


//Journal Reader Code Chunk.

// else if (EventName == "Shipyard")
// {
//     var Event = JsonConvert.DeserializeObject<ALICE_Events.Shipyard>(RawLine);
//     Manager.UpdateEvents(EventName, Event);
//     Manager.Shipyard.Logic();
// }
