//Code Generated By Project A.L.I.C.E Developer Toolkit
//Class File Generated: 01/18/2026 4:27 PM
//Source Journal Line: { "timestamp":"2025-11-12T09:46:15Z", "event":"JetConeBoost", "BoostValue":1.500000 }

using System;
using System.Collections.Generic;

namespace ALICE_Events
{
    public class Event_JetConeBoost : Event_Base
    {
        public Event_JetConeBoost()
        {
            Name = "JetConeBoost";
        }

        public void Logic()
        {
            if (Manager.WriteVariables && WriteVariables)
            {
                try
                {
                    Variables_Clear();
                    Variables_Generate();
                    Variables_Write();
                }
                catch (Exception ex)
                {
                    Internal.Exception(Name, "An Exception Occured While Updating Variables");
                    Internal.Exception(Name, "Exception: " + ex);
                }
            }

            //GameState.Logic_JetConeBoost((JetConeBoost)GetEvent());

            TriggerEvent();
        }

        public void Variables_Generate()
        {
            JetConeBoost Event = (JetConeBoost)Manager.GetEvent(Name);

            Variables.Clear();

            #region Custom Variables

            #endregion

            #region Event Variables
            Variable_Craft("BoostValue", Event.BoostValue.ToString());
            #endregion
        }
    }

    #region JetConeBoost Event
    public class JetConeBoost : Base
    {
        public decimal BoostValue { get; set; }
    }
    #endregion
}


//Journal Reader Code Chunk.

// else if (EventName == "JetConeBoost")
// {
//     var Event = JsonConvert.DeserializeObject<ALICE_Events.JetConeBoost>(RawLine);
//     Manager.UpdateEvents(EventName, Event);
//     Manager.JetConeBoost.Logic();
// }
