//Code Generated By Project A.L.I.C.E Developer Toolkit
//Class File Generated: 01/18/2026 4:27 PM
//Source Journal Line: { "timestamp":"2026-01-17T19:41:36Z", "event":"MissionRedirected", "MissionID":1042347155, "Name":"Mission_Massacre_RankFed", "LocalisedName":"Federal Navy Strike Contract", "NewDestinationStation":"Biggus Dockus", "NewDestinationSystem":"BD+04 3919", "OldDestinationStation":"", "OldDestinationSystem":"GD 215" }

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using ALICE_Ships_Datalink_Interface;
using ALICE_Command_Interface;
using ALICE_Internal;

namespace ALICE_Events
{
    public class Event_MissionRedirected : Event_Base
    {
        public Event_MissionRedirected()
        {
            Name = "MissionRedirected";
        }

        public void Logic()
        {
            if (Manager.WriteVariables && WriteVariables)
            {
                try
                {
                    Variables_Clear();
                    Variables_Generate();
                    Variables_Write();
                }
            }

            //GameState.Logic_MissionRedirected((MissionRedirected)GetEvent());

            TriggerEvent();
        }

        public void Variables_Generate()
        {
            MissionRedirected Event = (MissionRedirected)Manager.GetEvent(Name);

            Variables.Clear();

            #region Custom Variables

            #endregion

            #region Event Variables
            Variable_Craft("MissionID", Event.MissionID.ToString());
            Variable_Craft("Name", Event.Name.ToString());
            Variable_Craft("LocalisedName", Event.LocalisedName.ToString());
            Variable_Craft("NewDestinationStation", Event.NewDestinationStation.ToString());
            Variable_Craft("NewDestinationSystem", Event.NewDestinationSystem.ToString());
            Variable_Craft("OldDestinationStation", Event.OldDestinationStation.ToString());
            Variable_Craft("OldDestinationSystem", Event.OldDestinationSystem.ToString());
            #endregion
        }
    }

    #region MissionRedirected Event
    public class MissionRedirected : Base
    {
        public decimal MissionID { get; set; }
        public string Name { get; set; }
        public string LocalisedName { get; set; }
        public string NewDestinationStation { get; set; }
        public string NewDestinationSystem { get; set; }
        public string OldDestinationStation { get; set; }
        public string OldDestinationSystem { get; set; }
    }
    #endregion
}


//Journal Reader Code Chunk.

// else if (EventName == "MissionRedirected")
// {
//     var Event = JsonConvert.DeserializeObject<ALICE_Events.MissionRedirected>(RawLine);
//     Manager.UpdateEvents(EventName, Event);
//     Manager.MissionRedirected.Logic();
// }
