//Code Generated By Project A.L.I.C.E Developer Toolkit
//Class File Generated: 01/18/2026 4:27 PM
//Source Journal Line: { "timestamp":"2026-01-10T22:56:39Z", "event":"BookDropship", "Retreat":false, "Cost":0, "DestinationSystem":"Kurmodiae", "DestinationLocation":"Medina Entertainment Complex" }

using System;
using System.Collections.Generic;

namespace ALICE_Events
{
    public class Event_BookDropship : Event_Base
    {
        public Event_BookDropship()
        {
            Name = "BookDropship";
        }

        public void Logic()
        {
            if (Manager.WriteVariables && WriteVariables)
            {
                try
                {
                    Variables_Clear();
                    Variables_Generate();
                    Variables_Write();
                }
                catch (Exception ex)
                {
                    Internal.Exception(Name, "An Exception Occured While Updating Variables");
                    Internal.Exception(Name, "Exception: " + ex);
                }
            }

            //GameState.Logic_BookDropship((BookDropship)GetEvent());

            TriggerEvent();
        }

        public void Variables_Generate()
        {
            BookDropship Event = (BookDropship)Manager.GetEvent(Name);

            Variables.Clear();

            #region Custom Variables

            #endregion

            #region Event Variables
            Variable_Craft("Retreat", Event.Retreat.ToString());
            Variable_Craft("Cost", Event.Cost.ToString());
            Variable_Craft("DestinationSystem", Event.DestinationSystem.ToString());
            Variable_Craft("DestinationLocation", Event.DestinationLocation.ToString());
            #endregion
        }
    }

    #region BookDropship Event
    public class BookDropship : Base
    {
        public string Retreat { get; set; }
        public decimal Cost { get; set; }
        public string DestinationSystem { get; set; }
        public string DestinationLocation { get; set; }
    }
    #endregion
}


//Journal Reader Code Chunk.

// else if (EventName == "BookDropship")
// {
//     var Event = JsonConvert.DeserializeObject<ALICE_Events.BookDropship>(RawLine);
//     Manager.UpdateEvents(EventName, Event);
//     Manager.BookDropship.Logic();
// }
