//Code Generated By Project A.L.I.C.E Developer Toolkit
//Class File Generated: 01/18/2026 4:27 PM
//Source Journal Line: { "timestamp":"2026-01-12T01:54:56Z", "event":"NpcCrewPaidWage", "NpcCrewName":"Alonzo Robertson", "NpcCrewId":143023072, "Amount":2053224 }

using System;

namespace ALICE_Events
{
    public class Event_NpcCrewPaidWage : Event_Base
    {
        public Event_NpcCrewPaidWage()
        {
            Name = "NpcCrewPaidWage";
        }

        public void Logic()
        {
            if (Manager.WriteVariables && WriteVariables)
            {
                    Variables_Clear();
                    Variables_Generate();
                    Variables_Write();
            }

            //GameState.Logic_NpcCrewPaidWage((NpcCrewPaidWage)GetEvent());

            TriggerEvent();
        }

        public void Variables_Generate()
        {
            NpcCrewPaidWage Event = (NpcCrewPaidWage)Manager.GetEvent(Name);

            Variables.Clear();

            #region Custom Variables

            #endregion

            #region Event Variables
            Variable_Craft("NpcCrewName", Event.NpcCrewName.ToString());
            Variable_Craft("NpcCrewId", Event.NpcCrewId.ToString());
            Variable_Craft("Amount", Event.Amount.ToString());
            #endregion
        }
    }

    #region NpcCrewPaidWage Event
    public class NpcCrewPaidWage : Base
    {
        public string NpcCrewName { get; set; }
        public decimal NpcCrewId { get; set; }
        public decimal Amount { get; set; }
    }
    #endregion
}


//Journal Reader Code Chunk.

// else if (EventName == "NpcCrewPaidWage")
// {
//     var Event = JsonConvert.DeserializeObject<ALICE_Events.NpcCrewPaidWage>(RawLine);
//     Manager.UpdateEvents(EventName, Event);
//     Manager.NpcCrewPaidWage.Logic();
// }
