//Code Generated By Project A.L.I.C.E Developer Toolkit
//Class File Generated: 01/18/2026 4:27 PM
//Source Journal Line: { "timestamp":"2026-01-10T15:11:56Z", "event":"StoredShips", "StationName":"Jameson Memorial", "MarketID":128666762, "StarSystem":"Shinrarta Dezhra", "ShipsHere":[ { "ShipID":21, "ShipType":"diamondbackxl", "ShipType_Localised":"Diamondback Explorer", "Value":8172927, "Hot":false }, { "ShipID":40, "ShipType":"type8", "ShipType_Localised":"Type-8 Transporter", "Value":39602625, "Hot":false } ], "ShipsRemote":[ { "ShipID":18, "ShipType":"SideWinder", "Name":"", "StarSystem":"Palee", "ShipMarketID":3714546688, "TransferPrice":6103, "TransferTime":1672, "Value":544574, "Hot":false }, { "ShipID":36, "ShipType":"Type8", "ShipType_Localised":"Type-8 Transporter", "Name":"", "StarSystem":"Gali", "ShipMarketID":3713931520, "TransferPrice":399663, "TransferTime":1659, "Value":42947658, "Hot":false }, { "ShipID":30, "ShipType":"Python", "Name":"", "StarSystem":"Palee", "ShipMarketID":3714546688, "TransferPrice":657924, "TransferTime":1672, "Value":70103577, "Hot":false }, { "ShipID":35, "ShipType":"Type9", "ShipType_Localised":"Type-9 Heavy", "Name":"", "StarSystem":"Palee", "ShipMarketID":3714546688, "TransferPrice":998752, "TransferTime":1672, "Value":106474966, "Hot":false }, { "ShipID":8, "ShipType":"Anaconda", "Name":"", "StarSystem":"Palee", "ShipMarketID":3714546688, "TransferPrice":4680228, "TransferTime":1672, "Value":499343140, "Hot":false }, { "ShipID":37, "ShipType":"PantherMkII", "ShipType_Localised":"Panther Clipper Mk II", "Name":"", "StarSystem":"Gali", "ShipMarketID":3713931520, "TransferPrice":4785929, "TransferTime":1659, "Value":515475989, "Hot":false } ] }

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using ALICE_Ships_Datalink_Interface;
using ALICE_Command_Interface;
using ALICE_Internal;

namespace ALICE_Events
{
    public class Event_StoredShips : Event_Base
    {
        public Event_StoredShips()
        {
            Name = "StoredShips";
        }

        public void Logic()
        {
            if (Manager.WriteVariables && WriteVariables)
            {
                try
                {
                    Variables_Clear();
                    Variables_Generate();
                    Variables_Write();
                }
            }

            //GameState.Logic_StoredShips((StoredShips)GetEvent());

            TriggerEvent();
        }

        public void Variables_Generate()
        {
            StoredShips Event = (StoredShips)Manager.GetEvent(Name);

            Variables.Clear();

            #region Custom Variables

            #endregion

            #region Event Variables
            Variable_Craft("StationName", Event.StationName.ToString());
            Variable_Craft("MarketID", Event.MarketID.ToString());
            Variable_Craft("StarSystem", Event.StarSystem.ToString());
            Variable_Craft("ShipsHere", Event.ShipsHere.ToString());
            Variable_Craft("ShipsRemote", Event.ShipsRemote.ToString());
            #endregion
        }
    }

    #region StoredShips Event
    public class StoredShips : Base
    {
        public string StationName { get; set; }
        public decimal MarketID { get; set; }
        public string StarSystem { get; set; }
        public string ShipsHere { get; set; }
        public string ShipsRemote { get; set; }
    }
    #endregion
}


//Journal Reader Code Chunk.

// else if (EventName == "StoredShips")
// {
//     var Event = JsonConvert.DeserializeObject<ALICE_Events.StoredShips>(RawLine);
//     Manager.UpdateEvents(EventName, Event);
//     Manager.StoredShips.Logic();
// }
