//Code Generated By Project A.L.I.C.E Developer Toolkit
//Class File Generated: 01/18/2026 4:27 PM
//Source Journal Line: { "timestamp":"2026-01-17T18:48:54Z", "event":"RedeemVoucher", "Type":"bounty", "Amount":2651044, "Factions":[ { "Faction":"MADDISON Interstellar", "Amount":2651044 } ] }

using System;

namespace ALICE_Events
{
    public class Event_RedeemVoucher : Event_Base
    {
        public Event_RedeemVoucher()
        {
            Name = "RedeemVoucher";
        }

        public void Logic()
        {
            if (Manager.WriteVariables && WriteVariables)
            {
                    Variables_Clear();
                    Variables_Generate();
                    Variables_Write();
            }

            //GameState.Logic_RedeemVoucher((RedeemVoucher)GetEvent());

            TriggerEvent();
        }

        public void Variables_Generate()
        {
            RedeemVoucher Event = (RedeemVoucher)Manager.GetEvent(Name);

            Variables.Clear();

            #region Custom Variables

            #endregion

            #region Event Variables
            Variable_Craft("Type", Event.Type.ToString());
            Variable_Craft("Amount", Event.Amount.ToString());
            Variable_Craft("Factions", Event.Factions.ToString());
            #endregion
        }
    }

    #region RedeemVoucher Event
    public class RedeemVoucher : Base
    {
        public string Type { get; set; }
        public decimal Amount { get; set; }
        public string Factions { get; set; }
    }
    #endregion
}


//Journal Reader Code Chunk.

// else if (EventName == "RedeemVoucher")
// {
//     var Event = JsonConvert.DeserializeObject<ALICE_Events.RedeemVoucher>(RawLine);
//     Manager.UpdateEvents(EventName, Event);
//     Manager.RedeemVoucher.Logic();
// }
