//Code Generated By Project A.L.I.C.E Developer Toolkit
//Class File Generated: 01/18/2026 4:27 PM
//Source Journal Line: { "timestamp":"2026-01-11T00:59:44Z", "event":"Synthesis", "Name":"FSD Premium", "Materials":[ { "Name":"carbon", "Count":1 }, { "Name":"germanium", "Count":1 }, { "Name":"arsenic", "Count":1 }, { "Name":"niobium", "Count":1 }, { "Name":"yttrium", "Count":1 }, { "Name":"polonium", "Count":1 } ] }

using System;

namespace ALICE_Events
{
    public class Event_Synthesis : Event_Base
    {
        public Event_Synthesis()
        {
            Name = "Synthesis";
        }

        public void Logic()
        {
            if (Manager.WriteVariables && WriteVariables)
            {
                    Variables_Clear();
                    Variables_Generate();
                    Variables_Write();
            }

            //GameState.Logic_Synthesis((Synthesis)GetEvent());

            TriggerEvent();
        }

        public void Variables_Generate()
        {
            Synthesis Event = (Synthesis)Manager.GetEvent(Name);

            Variables.Clear();

            #region Custom Variables

            #endregion

            #region Event Variables
            Variable_Craft("Name", Event.Name.ToString());
            Variable_Craft("Materials", Event.Materials.ToString());
            #endregion
        }
    }

    #region Synthesis Event
    public class Synthesis : Base
    {
        public string Name { get; set; }
        public string Materials { get; set; }
    }
    #endregion
}


//Journal Reader Code Chunk.

// else if (EventName == "Synthesis")
// {
//     var Event = JsonConvert.DeserializeObject<ALICE_Events.Synthesis>(RawLine);
//     Manager.UpdateEvents(EventName, Event);
//     Manager.Synthesis.Logic();
// }
