//Code Generated By Project A.L.I.C.E Developer Toolkit
//Class File Generated: 01/18/2026 4:27 PM
//Source Journal Line: { "timestamp":"2026-01-17T19:45:36Z", "event":"Promotion", "Federation":7 }

using System;

namespace ALICE_Events
{
    public class Event_Promotion : Event_Base
    {
        public Event_Promotion()
        {
            Name = "Promotion";
        }

        public void Logic()
        {
            if (Manager.WriteVariables && WriteVariables)
            {
                    Variables_Clear();
                    Variables_Generate();
                    Variables_Write();
            }

            //GameState.Logic_Promotion((Promotion)GetEvent());

            TriggerEvent();
        }

        public void Variables_Generate()
        {
            Promotion Event = (Promotion)Manager.GetEvent(Name);

            Variables.Clear();

            #region Custom Variables

            #endregion

            #region Event Variables
            Variable_Craft("Federation", Event.Federation.ToString());
            #endregion
        }
    }

    #region Promotion Event
    public class Promotion : Base
    {
        public decimal Federation { get; set; }
    }
    #endregion
}


//Journal Reader Code Chunk.

// else if (EventName == "Promotion")
// {
//     var Event = JsonConvert.DeserializeObject<ALICE_Events.Promotion>(RawLine);
//     Manager.UpdateEvents(EventName, Event);
//     Manager.Promotion.Logic();
// }
