//Code Generated By Project A.L.I.C.E Developer Toolkit
//Class File Generated: 01/18/2026 4:27 PM
//Source Journal Line: { "timestamp":"2026-01-17T18:50:21Z", "event":"MaterialTrade", "MarketID":3230440960, "TraderType":"manufactured", "Paid":{ "Material":"exquisitefocuscrystals", "Material_Localised":"Exquisite Focus Crystals", "Category":"Manufactured", "Quantity":20 }, "Received":{ "Material":"wornshieldemitters", "Material_Localised":"Worn Shield Emitters", "Category":"Manufactured", "Quantity":270 } }

using System;

namespace ALICE_Events
{
    public class Event_MaterialTrade : Event_Base
    {
        public Event_MaterialTrade()
        {
            Name = "MaterialTrade";
        }

        public void Logic()
        {
            if (Manager.WriteVariables && WriteVariables)
            {
                    Variables_Clear();
                    Variables_Generate();
                    Variables_Write();
            }

            //GameState.Logic_MaterialTrade((MaterialTrade)GetEvent());

            TriggerEvent();
        }

        public void Variables_Generate()
        {
            MaterialTrade Event = (MaterialTrade)Manager.GetEvent(Name);

            Variables.Clear();

            #region Custom Variables

            #endregion

            #region Event Variables
            Variable_Craft("MarketID", Event.MarketID.ToString());
            Variable_Craft("TraderType", Event.TraderType.ToString());
            Variable_Craft("Paid", Event.Paid.ToString());
            Variable_Craft("Received", Event.Received.ToString());
            #endregion
        }
    }

    #region MaterialTrade Event
    public class MaterialTrade : Base
    {
        public decimal MarketID { get; set; }
        public string TraderType { get; set; }
        public string Paid { get; set; }
        public string Received { get; set; }
    }
    #endregion
}


//Journal Reader Code Chunk.

// else if (EventName == "MaterialTrade")
// {
//     var Event = JsonConvert.DeserializeObject<ALICE_Events.MaterialTrade>(RawLine);
//     Manager.UpdateEvents(EventName, Event);
//     Manager.MaterialTrade.Logic();
// }
