//Code Generated By Project A.L.I.C.E Developer Toolkit
//Class File Generated: 01/18/2026 4:27 PM
//Source Journal Line: { "timestamp":"2026-01-10T21:52:28Z", "event":"LoadoutEquipModule", "LoadoutName":"combat 2", "SuitID":1763747430586625, "SuitName":"tacticalsuit_class2", "SuitName_Localised":"$TacticalSuit_Class1_Name;", "LoadoutID":4293000002, "SlotName":"SecondaryWeapon", "ModuleName":"wpn_s_pistol_laser_sauto", "ModuleName_Localised":"TK Zenith", "Class":3, "WeaponMods":[ "weapon_suppression_pressurised" ], "SuitModuleID":1763896499181480 }

using System;
using System.Collections.Generic;

namespace ALICE_Events
{
    public class Event_LoadoutEquipModule : Event_Base
    {
        public Event_LoadoutEquipModule()
        {
            Name = "LoadoutEquipModule";
        }

        public void Logic()
        {
            if (Manager.WriteVariables && WriteVariables)
            {
                try
                {
                    Variables_Clear();
                    Variables_Generate();
                    Variables_Write();
                }
            }

            //GameState.Logic_LoadoutEquipModule((LoadoutEquipModule)GetEvent());

            TriggerEvent();
        }

        public void Variables_Generate()
        {
            LoadoutEquipModule Event = (LoadoutEquipModule)Manager.GetEvent(Name);

            Variables.Clear();

            #region Custom Variables

            #endregion

            #region Event Variables
            Variable_Craft("LoadoutName", Event.LoadoutName.ToString());
            Variable_Craft("SuitID", Event.SuitID.ToString());
            Variable_Craft("SuitName", Event.SuitName.ToString());
            Variable_Craft("SuitName_Localised", Event.SuitName_Localised.ToString());
            Variable_Craft("LoadoutID", Event.LoadoutID.ToString());
            Variable_Craft("SlotName", Event.SlotName.ToString());
            Variable_Craft("ModuleName", Event.ModuleName.ToString());
            Variable_Craft("ModuleName_Localised", Event.ModuleName_Localised.ToString());
            Variable_Craft("Class", Event.Class.ToString());
            Variable_Craft("WeaponMods", Event.WeaponMods.ToString());
            Variable_Craft("SuitModuleID", Event.SuitModuleID.ToString());
            #endregion
        }
    }

    #region LoadoutEquipModule Event
    public class LoadoutEquipModule : Base
    {
        public string LoadoutName { get; set; }
        public decimal SuitID { get; set; }
        public string SuitName { get; set; }
        public string SuitName_Localised { get; set; }
        public decimal LoadoutID { get; set; }
        public string SlotName { get; set; }
        public string ModuleName { get; set; }
        public string ModuleName_Localised { get; set; }
        public decimal Class { get; set; }
        public string WeaponMods { get; set; }
        public decimal SuitModuleID { get; set; }
    }
    #endregion
}


//Journal Reader Code Chunk.

// else if (EventName == "LoadoutEquipModule")
// {
//     var Event = JsonConvert.DeserializeObject<ALICE_Events.LoadoutEquipModule>(RawLine);
//     Manager.UpdateEvents(EventName, Event);
//     Manager.LoadoutEquipModule.Logic();
// }
