//Code Generated By Project A.L.I.C.E Developer Toolkit
//Class File Generated: 01/18/2026 4:27 PM
//Source Journal Line: { "timestamp":"2026-01-10T18:56:12Z", "event":"Resurrect", "Option":"handin", "Cost":0, "Bankrupt":false }

using System;
using System.Collections.Generic;

namespace ALICE_Events
{
    public class Event_Resurrect : Event_Base
    {
        public Event_Resurrect()
        {
            Name = "Resurrect";
        }

        public void Logic()
        {
            if (Manager.WriteVariables && WriteVariables)
            {
                try
                {
                    Variables_Clear();
                    Variables_Generate();
                    Variables_Write();
                }
            }

            //GameState.Logic_Resurrect((Resurrect)GetEvent());

            TriggerEvent();
        }

        public void Variables_Generate()
        {
            Resurrect Event = (Resurrect)Manager.GetEvent(Name);

            Variables.Clear();

            #region Custom Variables

            #endregion

            #region Event Variables
            Variable_Craft("Option", Event.Option.ToString());
            Variable_Craft("Cost", Event.Cost.ToString());
            Variable_Craft("Bankrupt", Event.Bankrupt.ToString());
            #endregion
        }
    }

    #region Resurrect Event
    public class Resurrect : Base
    {
        public string Option { get; set; }
        public decimal Cost { get; set; }
        public string Bankrupt { get; set; }
    }
    #endregion
}


//Journal Reader Code Chunk.

// else if (EventName == "Resurrect")
// {
//     var Event = JsonConvert.DeserializeObject<ALICE_Events.Resurrect>(RawLine);
//     Manager.UpdateEvents(EventName, Event);
//     Manager.Resurrect.Logic();
// }
