//Code Generated By Project A.L.I.C.E Developer Toolkit
//Class File Generated: 01/18/2026 4:27 PM
//Source Journal Line: { "timestamp":"2026-01-15T17:48:25Z", "event":"MarketBuy", "MarketID":4298026243, "Type":"thermalcoolingunits", "Type_Localised":"Thermal Cooling Units", "Count":1232, "BuyPrice":2965, "TotalCost":3652880 }

using System;

namespace ALICE_Events
{
    public class Event_MarketBuy : Event_Base
    {
        public Event_MarketBuy()
        {
            Name = "MarketBuy";
        }

        public void Logic()
        {
            if (Manager.WriteVariables && WriteVariables)
            {
                    Variables_Clear();
                    Variables_Generate();
                    Variables_Write();
            }

            //GameState.Logic_MarketBuy((MarketBuy)GetEvent());

            TriggerEvent();
        }

        public void Variables_Generate()
        {
            MarketBuy Event = (MarketBuy)Manager.GetEvent(Name);

            Variables.Clear();

            #region Custom Variables

            #endregion

            #region Event Variables
            Variable_Craft("MarketID", Event.MarketID.ToString());
            Variable_Craft("Type", Event.Type.ToString());
            Variable_Craft("Type_Localised", Event.Type_Localised.ToString());
            Variable_Craft("Count", Event.Count.ToString());
            Variable_Craft("BuyPrice", Event.BuyPrice.ToString());
            Variable_Craft("TotalCost", Event.TotalCost.ToString());
            #endregion
        }
    }

    #region MarketBuy Event
    public class MarketBuy : Base
    {
        public decimal MarketID { get; set; }
        public string Type { get; set; }
        public string Type_Localised { get; set; }
        public decimal Count { get; set; }
        public decimal BuyPrice { get; set; }
        public decimal TotalCost { get; set; }
    }
    #endregion
}


//Journal Reader Code Chunk.

// else if (EventName == "MarketBuy")
// {
//     var Event = JsonConvert.DeserializeObject<ALICE_Events.MarketBuy>(RawLine);
//     Manager.UpdateEvents(EventName, Event);
//     Manager.MarketBuy.Logic();
// }
