//Code Generated By Project A.L.I.C.E Developer Toolkit
//Class File Generated: 01/18/2026 4:27 PM
//Source Journal Line: { "timestamp":"2026-01-07T19:01:33Z", "event":"CarrierDepositFuel", "CarrierID":3714546688, "Amount":518, "Total":1000 }

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using ALICE_Ships_Datalink_Interface;
using ALICE_Command_Interface;
using ALICE_Internal;

namespace ALICE_Events
{
    public class Event_CarrierDepositFuel : Event_Base
    {
        public Event_CarrierDepositFuel()
        {
            Name = "CarrierDepositFuel";
        }

        public void Logic()
        {
            if (Manager.WriteVariables && WriteVariables)
            {
                try
                {
                    Variables_Clear();
                    Variables_Generate();
                    Variables_Write();
                }
            }

            //GameState.Logic_CarrierDepositFuel((CarrierDepositFuel)GetEvent());

            TriggerEvent();
        }

        public void Variables_Generate()
        {
            CarrierDepositFuel Event = (CarrierDepositFuel)Manager.GetEvent(Name);

            Variables.Clear();

            #region Custom Variables

            #endregion

            #region Event Variables
            Variable_Craft("CarrierID", Event.CarrierID.ToString());
            Variable_Craft("Amount", Event.Amount.ToString());
            Variable_Craft("Total", Event.Total.ToString());
            #endregion
        }
    }

    #region CarrierDepositFuel Event
    public class CarrierDepositFuel : Base
    {
        public decimal CarrierID { get; set; }
        public decimal Amount { get; set; }
        public decimal Total { get; set; }
    }
    #endregion
}


//Journal Reader Code Chunk.

// else if (EventName == "CarrierDepositFuel")
// {
//     var Event = JsonConvert.DeserializeObject<ALICE_Events.CarrierDepositFuel>(RawLine);
//     Manager.UpdateEvents(EventName, Event);
//     Manager.CarrierDepositFuel.Logic();
// }
