//Code Generated By Project A.L.I.C.E Developer Toolkit
//Class File Generated: 01/18/2026 4:27 PM
//Source Journal Line: { "timestamp":"2026-01-15T17:43:11Z", "event":"Scan", "ScanType":"AutoScan", "BodyName":"Rho Ophiuchi Sector IH-U b3-1 3", "BodyID":10, "Parents":[ {"Star":0} ], "StarSystem":"Rho Ophiuchi Sector IH-U b3-1", "SystemAddress":2870783649369, "DistanceFromArrivalLS":44.798474, "TidalLock":true, "TerraformState":"", "PlanetClass":"Rocky ice body", "Atmosphere":"thin sulfur dioxide atmosphere", "AtmosphereType":"SulphurDioxide", "AtmosphereComposition":[ { "Name":"SulphurDioxide", "Percent":100.000000 } ], "Volcanism":"", "MassEM":0.054300, "Radius":2582516.250000, "SurfaceGravity":3.245091, "SurfaceTemperature":235.013306, "SurfacePressure":780.382568, "Landable":true, "Materials":[ { "Name":"iron", "Percent":20.317785 }, { "Name":"sulphur", "Percent":17.379732 }, { "Name":"nickel", "Percent":15.367519 }, { "Name":"carbon", "Percent":14.614555 }, { "Name":"phosphorus", "Percent":9.356489 }, { "Name":"manganese", "Percent":8.391038 }, { "Name":"zinc", "Percent":5.521613 }, { "Name":"vanadium", "Percent":4.989341 }, { "Name":"cadmium", "Percent":1.577768 }, { "Name":"niobium", "Percent":1.388612 }, { "Name":"tellurium", "Percent":1.095539 } ], "Composition":{ "Ice":0.133330, "Rock":0.580238, "Metal":0.286433 }, "SemiMajorAxis":13430225849.151611, "Eccentricity":0.000059, "OrbitalInclination":-0.002515, "Periapsis":156.328851, "OrbitalPeriod":1587988.495827, "AscendingNode":17.401584, "MeanAnomaly":91.351154, "RotationPeriod":1589506.516045, "AxialTilt":-0.427538, "WasDiscovered":true, "WasMapped":true, "WasFootfalled":true }

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using ALICE_Ships_Datalink_Interface;
using ALICE_Command_Interface;
using ALICE_Internal;

namespace ALICE_Events
{
    public class Event_Scan : Event_Base
    {
        public Event_Scan()
        {
            Name = "Scan";
        }

        public void Logic()
        {
            if (Manager.WriteVariables && WriteVariables)
            {
                try
                {
                    Variables_Clear();
                    Variables_Generate();
                    Variables_Write();
                }
            }

            //GameState.Logic_Scan((Scan)GetEvent());

            TriggerEvent();
        }

        public void Variables_Generate()
        {
            Scan Event = (Scan)Manager.GetEvent(Name);

            Variables.Clear();

            #region Custom Variables

            #endregion

            #region Event Variables
            Variable_Craft("ScanType", Event.ScanType.ToString());
            Variable_Craft("BodyName", Event.BodyName.ToString());
            Variable_Craft("BodyID", Event.BodyID.ToString());
            Variable_Craft("Parents", Event.Parents.ToString());
            Variable_Craft("StarSystem", Event.StarSystem.ToString());
            Variable_Craft("SystemAddress", Event.SystemAddress.ToString());
            Variable_Craft("DistanceFromArrivalLS", Event.DistanceFromArrivalLS.ToString());
            Variable_Craft("TidalLock", Event.TidalLock.ToString());
            Variable_Craft("TerraformState", Event.TerraformState.ToString());
            Variable_Craft("PlanetClass", Event.PlanetClass.ToString());
            Variable_Craft("Atmosphere", Event.Atmosphere.ToString());
            Variable_Craft("AtmosphereType", Event.AtmosphereType.ToString());
            Variable_Craft("AtmosphereComposition", Event.AtmosphereComposition.ToString());
            Variable_Craft("Volcanism", Event.Volcanism.ToString());
            Variable_Craft("MassEM", Event.MassEM.ToString());
            Variable_Craft("Radius", Event.Radius.ToString());
            Variable_Craft("SurfaceGravity", Event.SurfaceGravity.ToString());
            Variable_Craft("SurfaceTemperature", Event.SurfaceTemperature.ToString());
            Variable_Craft("SurfacePressure", Event.SurfacePressure.ToString());
            Variable_Craft("Landable", Event.Landable.ToString());
            Variable_Craft("Materials", Event.Materials.ToString());
            Variable_Craft("Composition", Event.Composition.ToString());
            Variable_Craft("SemiMajorAxis", Event.SemiMajorAxis.ToString());
            Variable_Craft("Eccentricity", Event.Eccentricity.ToString());
            Variable_Craft("OrbitalInclination", Event.OrbitalInclination.ToString());
            Variable_Craft("Periapsis", Event.Periapsis.ToString());
            Variable_Craft("OrbitalPeriod", Event.OrbitalPeriod.ToString());
            Variable_Craft("AscendingNode", Event.AscendingNode.ToString());
            Variable_Craft("MeanAnomaly", Event.MeanAnomaly.ToString());
            Variable_Craft("RotationPeriod", Event.RotationPeriod.ToString());
            Variable_Craft("AxialTilt", Event.AxialTilt.ToString());
            Variable_Craft("WasDiscovered", Event.WasDiscovered.ToString());
            Variable_Craft("WasMapped", Event.WasMapped.ToString());
            Variable_Craft("WasFootfalled", Event.WasFootfalled.ToString());
            #endregion
        }
    }

    #region Scan Event
    public class Scan : Base
    {
        public string ScanType { get; set; }
        public string BodyName { get; set; }
        public decimal BodyID { get; set; }
        public string Parents { get; set; }
        public string StarSystem { get; set; }
        public decimal SystemAddress { get; set; }
        public decimal DistanceFromArrivalLS { get; set; }
        public string TidalLock { get; set; }
        public string TerraformState { get; set; }
        public string PlanetClass { get; set; }
        public string Atmosphere { get; set; }
        public string AtmosphereType { get; set; }
        public string AtmosphereComposition { get; set; }
        public string Volcanism { get; set; }
        public decimal MassEM { get; set; }
        public decimal Radius { get; set; }
        public decimal SurfaceGravity { get; set; }
        public decimal SurfaceTemperature { get; set; }
        public decimal SurfacePressure { get; set; }
        public string Landable { get; set; }
        public string Materials { get; set; }
        public string Composition { get; set; }
        public decimal SemiMajorAxis { get; set; }
        public string Eccentricity { get; set; }
        public decimal OrbitalInclination { get; set; }
        public decimal Periapsis { get; set; }
        public decimal OrbitalPeriod { get; set; }
        public decimal AscendingNode { get; set; }
        public decimal MeanAnomaly { get; set; }
        public decimal RotationPeriod { get; set; }
        public decimal AxialTilt { get; set; }
        public string WasDiscovered { get; set; }
        public string WasMapped { get; set; }
        public string WasFootfalled { get; set; }
    }
    #endregion
}


//Journal Reader Code Chunk.

// else if (EventName == "Scan")
// {
//     var Event = JsonConvert.DeserializeObject<ALICE_Events.Scan>(RawLine);
//     Manager.UpdateEvents(EventName, Event);
//     Manager.Scan.Logic();
// }
