//Code Generated By Project A.L.I.C.E Developer Toolkit
//Class File Generated: 01/18/2026 4:27 PM
//Source Journal Line: { "timestamp":"2025-11-12T10:57:44Z", "event":"DockingGranted", "LandingPad":10, "MarketID":3507690240, "StationName":"McDevitt Settlement", "StationType":"CraterPort" }

using System;

namespace ALICE_Events
{
    public class Event_DockingGranted : Event_Base
    {
        public Event_DockingGranted()
        {
            Name = "DockingGranted";
        }

        public void Logic()
        {
            if (Manager.WriteVariables && WriteVariables)
            {
                    Variables_Clear();
                    Variables_Generate();
                    Variables_Write();
            }

            //GameState.Logic_DockingGranted((DockingGranted)GetEvent());

            TriggerEvent();
        }

        public void Variables_Generate()
        {
            DockingGranted Event = (DockingGranted)Manager.GetEvent(Name);

            Variables.Clear();

            #region Custom Variables

            #endregion

            #region Event Variables
            Variable_Craft("LandingPad", Event.LandingPad.ToString());
            Variable_Craft("MarketID", Event.MarketID.ToString());
            Variable_Craft("StationName", Event.StationName.ToString());
            Variable_Craft("StationType", Event.StationType.ToString());
            #endregion
        }
    }

    #region DockingGranted Event
    public class DockingGranted : Base
    {
        public decimal LandingPad { get; set; }
        public decimal MarketID { get; set; }
        public string StationName { get; set; }
        public string StationType { get; set; }
    }
    #endregion
}


//Journal Reader Code Chunk.

// else if (EventName == "DockingGranted")
// {
//     var Event = JsonConvert.DeserializeObject<ALICE_Events.DockingGranted>(RawLine);
//     Manager.UpdateEvents(EventName, Event);
//     Manager.DockingGranted.Logic();
// }
