//Code Generated By Project A.L.I.C.E Developer Toolkit
//Class File Generated: 01/18/2026 4:27 PM
//Source Journal Line: { "timestamp":"2025-11-12T11:27:00Z", "event":"ShieldState", "ShieldsUp":false }

using System;
using System.Collections.Generic;

namespace ALICE_Events
{
    public class Event_ShieldState : Event_Base
    {
        public Event_ShieldState()
        {
            Name = "ShieldState";
        }

        public void Logic()
        {
            if (Manager.WriteVariables && WriteVariables)
            {
                try
                {
                    Variables_Clear();
                    Variables_Generate();
                    Variables_Write();
                }
            }

            //GameState.Logic_ShieldState((ShieldState)GetEvent());

            TriggerEvent();
        }

        public void Variables_Generate()
        {
            ShieldState Event = (ShieldState)Manager.GetEvent(Name);

            Variables.Clear();

            #region Custom Variables

            #endregion

            #region Event Variables
            Variable_Craft("ShieldsUp", Event.ShieldsUp.ToString());
            #endregion
        }
    }

    #region ShieldState Event
    public class ShieldState : Base
    {
        public string ShieldsUp { get; set; }
    }
    #endregion
}


//Journal Reader Code Chunk.

// else if (EventName == "ShieldState")
// {
//     var Event = JsonConvert.DeserializeObject<ALICE_Events.ShieldState>(RawLine);
//     Manager.UpdateEvents(EventName, Event);
//     Manager.ShieldState.Logic();
// }
