//Code Generated By Project A.L.I.C.E Developer Toolkit
//Class File Generated: 01/18/2026 4:27 PM
//Source Journal Line: { "timestamp":"2026-01-08T09:59:44Z", "event":"ReservoirReplenished", "FuelMain":126.889999, "FuelReservoir":1.110000 }

using System;
using System.Collections.Generic;

namespace ALICE_Events
{
    public class Event_ReservoirReplenished : Event_Base
    {
        public Event_ReservoirReplenished()
        {
            Name = "ReservoirReplenished";
        }

        public void Logic()
        {
            if (Manager.WriteVariables && WriteVariables)
            {
                try
                {
                    Variables_Clear();
                    Variables_Generate();
                    Variables_Write();
                }
            }

            //GameState.Logic_ReservoirReplenished((ReservoirReplenished)GetEvent());

            TriggerEvent();
        }

        public void Variables_Generate()
        {
            ReservoirReplenished Event = (ReservoirReplenished)Manager.GetEvent(Name);

            Variables.Clear();

            #region Custom Variables

            #endregion

            #region Event Variables
            Variable_Craft("FuelMain", Event.FuelMain.ToString());
            Variable_Craft("FuelReservoir", Event.FuelReservoir.ToString());
            #endregion
        }
    }

    #region ReservoirReplenished Event
    public class ReservoirReplenished : Base
    {
        public decimal FuelMain { get; set; }
        public decimal FuelReservoir { get; set; }
    }
    #endregion
}


//Journal Reader Code Chunk.

// else if (EventName == "ReservoirReplenished")
// {
//     var Event = JsonConvert.DeserializeObject<ALICE_Events.ReservoirReplenished>(RawLine);
//     Manager.UpdateEvents(EventName, Event);
//     Manager.ReservoirReplenished.Logic();
// }
