//Code Generated By Project A.L.I.C.E Developer Toolkit
//Class File Generated: 01/18/2026 4:27 PM
//Source Journal Line: { "timestamp":"2026-01-16T00:18:39Z", "event":"MarketSell", "MarketID":129032283, "Type":"thermalcoolingunits", "Type_Localised":"Thermal Cooling Units", "Count":1232, "SellPrice":37000, "TotalSale":45584000, "AvgPricePaid":185 }

using System;

namespace ALICE_Events
{
    public class Event_MarketSell : Event_Base
    {
        public Event_MarketSell()
        {
            Name = "MarketSell";
        }

        public void Logic()
        {
            if (Manager.WriteVariables && WriteVariables)
            {
                    Variables_Clear();
                    Variables_Generate();
                    Variables_Write();
            }

            //GameState.Logic_MarketSell((MarketSell)GetEvent());

            TriggerEvent();
        }

        public void Variables_Generate()
        {
            MarketSell Event = (MarketSell)Manager.GetEvent(Name);

            Variables.Clear();

            #region Custom Variables

            #endregion

            #region Event Variables
            Variable_Craft("MarketID", Event.MarketID.ToString());
            Variable_Craft("Type", Event.Type.ToString());
            Variable_Craft("Type_Localised", Event.Type_Localised.ToString());
            Variable_Craft("Count", Event.Count.ToString());
            Variable_Craft("SellPrice", Event.SellPrice.ToString());
            Variable_Craft("TotalSale", Event.TotalSale.ToString());
            Variable_Craft("AvgPricePaid", Event.AvgPricePaid.ToString());
            #endregion
        }
    }

    #region MarketSell Event
    public class MarketSell : Base
    {
        public decimal MarketID { get; set; }
        public string Type { get; set; }
        public string Type_Localised { get; set; }
        public decimal Count { get; set; }
        public decimal SellPrice { get; set; }
        public decimal TotalSale { get; set; }
        public decimal AvgPricePaid { get; set; }
    }
    #endregion
}


//Journal Reader Code Chunk.

// else if (EventName == "MarketSell")
// {
//     var Event = JsonConvert.DeserializeObject<ALICE_Events.MarketSell>(RawLine);
//     Manager.UpdateEvents(EventName, Event);
//     Manager.MarketSell.Logic();
// }
