//Code Generated By Project A.L.I.C.E Developer Toolkit
//Class File Generated: 01/18/2026 4:27 PM
//Source Journal Line: { "timestamp":"2026-01-17T18:34:42Z", "event":"Bounty", "Rewards":[ { "Faction":"MADDISON Interstellar", "Reward":416479 } ], "PilotName":"$npc_name_decorate:#name=Douglas Alexander Frank Torrance;", "PilotName_Localised":"Douglas Alexander Frank Torrance", "Target":"federation_dropship_mkii", "Target_Localised":"Federal Assault Ship", "TotalReward":416479, "VictimFaction":"Kigah Drug Empire" }

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using ALICE_Ships_Datalink_Interface;
using ALICE_Command_Interface;
using ALICE_Internal;

namespace ALICE_Events
{
    public class Event_Bounty : Event_Base
    {
        public Event_Bounty()
        {
            Name = "Bounty";
        }

        public void Logic()
        {
            if (Manager.WriteVariables && WriteVariables)
            {
                try
                {
                    Variables_Clear();
                    Variables_Generate();
                    Variables_Write();
                }
            }

            //GameState.Logic_Bounty((Bounty)GetEvent());

            TriggerEvent();
        }

        public void Variables_Generate()
        {
            Bounty Event = (Bounty)Manager.GetEvent(Name);

            Variables.Clear();

            #region Custom Variables

            #endregion

            #region Event Variables
            Variable_Craft("Rewards", Event.Rewards.ToString());
            Variable_Craft("PilotName", Event.PilotName.ToString());
            Variable_Craft("PilotName_Localised", Event.PilotName_Localised.ToString());
            Variable_Craft("Target", Event.Target.ToString());
            Variable_Craft("Target_Localised", Event.Target_Localised.ToString());
            Variable_Craft("TotalReward", Event.TotalReward.ToString());
            Variable_Craft("VictimFaction", Event.VictimFaction.ToString());
            #endregion
        }
    }

    #region Bounty Event
    public class Bounty : Base
    {
        public string Rewards { get; set; }
        public string PilotName { get; set; }
        public string PilotName_Localised { get; set; }
        public string Target { get; set; }
        public string Target_Localised { get; set; }
        public decimal TotalReward { get; set; }
        public string VictimFaction { get; set; }
    }
    #endregion
}


//Journal Reader Code Chunk.

// else if (EventName == "Bounty")
// {
//     var Event = JsonConvert.DeserializeObject<ALICE_Events.Bounty>(RawLine);
//     Manager.UpdateEvents(EventName, Event);
//     Manager.Bounty.Logic();
// }
