//Code Generated By Project A.L.I.C.E Developer Toolkit
//Class File Generated: 01/18/2026 4:27 PM
//Source Journal Line: { "timestamp":"2026-01-10T15:00:12Z", "event":"HeatDamage" }

using System;

namespace ALICE_Events
{
    public class Event_HeatDamage : Event_Base
    {
        public Event_HeatDamage()
        {
            Name = "HeatDamage";
        }

        public void Logic()
        {
            if (Manager.WriteVariables && WriteVariables)
            {
                    Variables_Clear();
                    Variables_Generate();
                    Variables_Write();
            }

            //GameState.Logic_HeatDamage((HeatDamage)GetEvent());

            TriggerEvent();
        }

        public void Variables_Generate()
        {
            HeatDamage Event = (HeatDamage)Manager.GetEvent(Name);

            Variables.Clear();

            #region Custom Variables

            #endregion

            #region Event Variables
            #endregion
        }
    }

    #region HeatDamage Event
    public class HeatDamage : Base
    {
    }
    #endregion
}


//Journal Reader Code Chunk.

// else if (EventName == "HeatDamage")
// {
//     var Event = JsonConvert.DeserializeObject<ALICE_Events.HeatDamage>(RawLine);
//     Manager.UpdateEvents(EventName, Event);
//     Manager.HeatDamage.Logic();
// }
