//Code Generated By Project A.L.I.C.E Developer Toolkit
//Class File Generated: 01/18/2026 4:27 PM
//Source Journal Line: { "timestamp":"2026-01-15T17:46:59Z", "event":"Docked", "StationName":"Hawker Point", "StationType":"Coriolis", "Taxi":false, "Multicrew":false, "StarSystem":"Rho Ophiuchi Sector IH-U b3-1", "SystemAddress":2870783649369, "MarketID":4298026243, "StationFaction":{ "Name":"Black Flag Gang" }, "StationGovernment":"$government_Anarchy;", "StationGovernment_Localised":"Anarchy", "StationServices":[ "dock", "autodock", "blackmarket", "commodities", "contacts", "exploration", "missions", "outfitting", "crewlounge", "rearm", "refuel", "repair", "shipyard", "engineer", "missionsgenerated", "facilitator", "flightcontroller", "stationoperations", "powerplay", "stationMenu", "shop", "livery", "socialspace", "vistagenomics", "registeringcolonisation" ], "StationEconomy":"$economy_Refinery;", "StationEconomy_Localised":"Refinery", "StationEconomies":[ { "Name":"$economy_Refinery;", "Name_Localised":"Refinery", "Proportion":3.800000 }, { "Name":"$economy_Industrial;", "Name_Localised":"Industrial", "Proportion":3.400000 }, { "Name":"$economy_Terraforming;", "Name_Localised":"Terraforming", "Proportion":1.000000 }, { "Name":"$economy_Agri;", "Name_Localised":"Agriculture", "Proportion":0.600000 }, { "Name":"$economy_HighTech;", "Name_Localised":"High Tech", "Proportion":0.150000 }, { "Name":"$economy_Extraction;", "Name_Localised":"Extraction", "Proportion":0.150000 }, { "Name":"$economy_Military;", "Name_Localised":"Military", "Proportion":0.050000 }, { "Name":"$economy_Tourism;", "Name_Localised":"Tourism", "Proportion":0.050000 }, { "Name":"$economy_Service;", "Name_Localised":"Service", "Proportion":0.050000 } ], "DistFromStarLS":44.804046, "LandingPads":{ "Small":6, "Medium":14, "Large":6 } }

using System;

namespace ALICE_Events
{
    public class Event_Docked : Event_Base
    {
        public Event_Docked()
        {
            Name = "Docked";
        }

        public void Logic()
        {
            if (Manager.WriteVariables && WriteVariables)
            {
                    Variables_Clear();
                    Variables_Generate();
                    Variables_Write();
            }

            //GameState.Logic_Docked((Docked)GetEvent());

            TriggerEvent();
        }

        public void Variables_Generate()
        {
            Docked Event = (Docked)Manager.GetEvent(Name);

            Variables.Clear();

            #region Custom Variables

            #endregion

            #region Event Variables
            Variable_Craft("StationName", Event.StationName.ToString());
            Variable_Craft("StationType", Event.StationType.ToString());
            Variable_Craft("Taxi", Event.Taxi.ToString());
            Variable_Craft("Multicrew", Event.Multicrew.ToString());
            Variable_Craft("StarSystem", Event.StarSystem.ToString());
            Variable_Craft("SystemAddress", Event.SystemAddress.ToString());
            Variable_Craft("MarketID", Event.MarketID.ToString());
            Variable_Craft("StationFaction", Event.StationFaction.ToString());
            Variable_Craft("StationGovernment", Event.StationGovernment.ToString());
            Variable_Craft("StationGovernment_Localised", Event.StationGovernment_Localised.ToString());
            Variable_Craft("StationServices", Event.StationServices.ToString());
            Variable_Craft("StationEconomy", Event.StationEconomy.ToString());
            Variable_Craft("StationEconomy_Localised", Event.StationEconomy_Localised.ToString());
            Variable_Craft("StationEconomies", Event.StationEconomies.ToString());
            Variable_Craft("DistFromStarLS", Event.DistFromStarLS.ToString());
            Variable_Craft("LandingPads", Event.LandingPads.ToString());
            #endregion
        }
    }

    #region Docked Event
    public class Docked : Base
    {
        public string StationName { get; set; }
        public string StationType { get; set; }
        public string Taxi { get; set; }
        public string Multicrew { get; set; }
        public string StarSystem { get; set; }
        public decimal SystemAddress { get; set; }
        public decimal MarketID { get; set; }
        public string StationFaction { get; set; }
        public string StationGovernment { get; set; }
        public string StationGovernment_Localised { get; set; }
        public string StationServices { get; set; }
        public string StationEconomy { get; set; }
        public string StationEconomy_Localised { get; set; }
        public string StationEconomies { get; set; }
        public decimal DistFromStarLS { get; set; }
        public string LandingPads { get; set; }
    }
    #endregion
}


//Journal Reader Code Chunk.

// else if (EventName == "Docked")
// {
//     var Event = JsonConvert.DeserializeObject<ALICE_Events.Docked>(RawLine);
//     Manager.UpdateEvents(EventName, Event);
//     Manager.Docked.Logic();
// }
