//Code Generated By Project A.L.I.C.E Developer Toolkit
//Class File Generated: 01/18/2026 4:27 PM
//Source Journal Line: { "timestamp":"2026-01-08T09:46:47Z", "event":"ShipyardSwap", "ShipType":"panthermkii", "ShipType_Localised":"Panther Clipper Mk II", "ShipID":37, "StoreOldShip":"DiamondBackXL", "StoreShipID":21, "MarketID":3230817536 }

using System;
using System.Collections.Generic;

namespace ALICE_Events
{
    public class Event_ShipyardSwap : Event_Base
    {
        public Event_ShipyardSwap()
        {
            Name = "ShipyardSwap";
        }

        public void Logic()
        {
            if (Manager.WriteVariables && WriteVariables)
            {
                try
                {
                    Variables_Clear();
                    Variables_Generate();
                    Variables_Write();
                }
            }

            //GameState.Logic_ShipyardSwap((ShipyardSwap)GetEvent());

            TriggerEvent();
        }

        public void Variables_Generate()
        {
            ShipyardSwap Event = (ShipyardSwap)Manager.GetEvent(Name);

            Variables.Clear();

            #region Custom Variables

            #endregion

            #region Event Variables
            Variable_Craft("ShipType", Event.ShipType.ToString());
            Variable_Craft("ShipType_Localised", Event.ShipType_Localised.ToString());
            Variable_Craft("ShipID", Event.ShipID.ToString());
            Variable_Craft("StoreOldShip", Event.StoreOldShip.ToString());
            Variable_Craft("StoreShipID", Event.StoreShipID.ToString());
            Variable_Craft("MarketID", Event.MarketID.ToString());
            #endregion
        }
    }

    #region ShipyardSwap Event
    public class ShipyardSwap : Base
    {
        public string ShipType { get; set; }
        public string ShipType_Localised { get; set; }
        public decimal ShipID { get; set; }
        public string StoreOldShip { get; set; }
        public decimal StoreShipID { get; set; }
        public decimal MarketID { get; set; }
    }
    #endregion
}


//Journal Reader Code Chunk.

// else if (EventName == "ShipyardSwap")
// {
//     var Event = JsonConvert.DeserializeObject<ALICE_Events.ShipyardSwap>(RawLine);
//     Manager.UpdateEvents(EventName, Event);
//     Manager.ShipyardSwap.Logic();
// }
