//Code Generated By Project A.L.I.C.E Developer Toolkit
//Class File Generated: 01/18/2026 4:27 PM
//Source Journal Line: { "timestamp":"2026-01-08T08:59:57Z", "event":"ModuleSell", "MarketID":128666762, "Slot":"Slot01_Size8", "SellItem":"$int_shieldgenerator_size7_class1_name;", "SellItem_Localised":"Shield Generator", "SellPrice":555632, "Ship":"panthermkii", "ShipID":37 }

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using ALICE_Ships_Datalink_Interface;
using ALICE_Command_Interface;
using ALICE_Internal;

namespace ALICE_Events
{
    public class Event_ModuleSell : Event_Base
    {
        public Event_ModuleSell()
        {
            Name = "ModuleSell";
        }

        public void Logic()
        {
            if (Manager.WriteVariables && WriteVariables)
            {
                try
                {
                    Variables_Clear();
                    Variables_Generate();
                    Variables_Write();
                }
            }

            //GameState.Logic_ModuleSell((ModuleSell)GetEvent());

            TriggerEvent();
        }

        public void Variables_Generate()
        {
            ModuleSell Event = (ModuleSell)Manager.GetEvent(Name);

            Variables.Clear();

            #region Custom Variables

            #endregion

            #region Event Variables
            Variable_Craft("MarketID", Event.MarketID.ToString());
            Variable_Craft("Slot", Event.Slot.ToString());
            Variable_Craft("SellItem", Event.SellItem.ToString());
            Variable_Craft("SellItem_Localised", Event.SellItem_Localised.ToString());
            Variable_Craft("SellPrice", Event.SellPrice.ToString());
            Variable_Craft("Ship", Event.Ship.ToString());
            Variable_Craft("ShipID", Event.ShipID.ToString());
            #endregion
        }
    }

    #region ModuleSell Event
    public class ModuleSell : Base
    {
        public decimal MarketID { get; set; }
        public string Slot { get; set; }
        public string SellItem { get; set; }
        public string SellItem_Localised { get; set; }
        public decimal SellPrice { get; set; }
        public string Ship { get; set; }
        public decimal ShipID { get; set; }
    }
    #endregion
}


//Journal Reader Code Chunk.

// else if (EventName == "ModuleSell")
// {
//     var Event = JsonConvert.DeserializeObject<ALICE_Events.ModuleSell>(RawLine);
//     Manager.UpdateEvents(EventName, Event);
//     Manager.ModuleSell.Logic();
// }
