//Code Generated By Project A.L.I.C.E Developer Toolkit
//Class File Generated: 01/18/2026 4:27 PM
//Source Journal Line: { "timestamp":"2026-01-16T00:17:03Z", "event":"DockingDenied", "Reason":"Distance", "MarketID":129032283, "StationName":"Surveyor’s Reach", "StationType":"SurfaceStation" }

using System;
using System.Collections.Generic;

namespace ALICE_Events
{
    public class Event_DockingDenied : Event_Base
    {
        public Event_DockingDenied()
        {
            Name = "DockingDenied";
        }

        public void Logic()
        {
            if (Manager.WriteVariables && WriteVariables)
            {
                try
                {
                    Variables_Clear();
                    Variables_Generate();
                    Variables_Write();
                }
                catch (Exception ex)
                {
                    Internal.Exception(Name, "An Exception Occured While Updating Variables");
                    Internal.Exception(Name, "Exception: " + ex);
                }
            }

            //GameState.Logic_DockingDenied((DockingDenied)GetEvent());

            TriggerEvent();
        }

        public void Variables_Generate()
        {
            DockingDenied Event = (DockingDenied)Manager.GetEvent(Name);

            Variables.Clear();

            #region Custom Variables

            #endregion

            #region Event Variables
            Variable_Craft("Reason", Event.Reason.ToString());
            Variable_Craft("MarketID", Event.MarketID.ToString());
            Variable_Craft("StationName", Event.StationName.ToString());
            Variable_Craft("StationType", Event.StationType.ToString());
            #endregion
        }
    }

    #region DockingDenied Event
    public class DockingDenied : Base
    {
        public string Reason { get; set; }
        public decimal MarketID { get; set; }
        public string StationName { get; set; }
        public string StationType { get; set; }
    }
    #endregion
}


//Journal Reader Code Chunk.

// else if (EventName == "DockingDenied")
// {
//     var Event = JsonConvert.DeserializeObject<ALICE_Events.DockingDenied>(RawLine);
//     Manager.UpdateEvents(EventName, Event);
//     Manager.DockingDenied.Logic();
// }
