//Code Generated By Project A.L.I.C.E Developer Toolkit
//Class File Generated: 01/18/2026 4:27 PM
//Source Journal Line: { "timestamp":"2026-01-08T09:18:28Z", "event":"ShipyardTransfer", "ShipType":"PantherMkII", "ShipType_Localised":"Panther Clipper Mk II", "ShipID":37, "System":"Shinrarta Dezhra", "ShipMarketID":128666762, "Distance":135.904861, "TransferPrice":4785929, "TransferTime":1659, "MarketID":3230817536 }

using System;

namespace ALICE_Events
{
    public class Event_ShipyardTransfer : Event_Base
    {
        public Event_ShipyardTransfer()
        {
            Name = "ShipyardTransfer";
        }

        public void Logic()
        {
            if (Manager.WriteVariables && WriteVariables)
            {
                    Variables_Clear();
                    Variables_Generate();
                    Variables_Write();
            }

            //GameState.Logic_ShipyardTransfer((ShipyardTransfer)GetEvent());

            TriggerEvent();
        }

        public void Variables_Generate()
        {
            ShipyardTransfer Event = (ShipyardTransfer)Manager.GetEvent(Name);

            Variables.Clear();

            #region Custom Variables

            #endregion

            #region Event Variables
            Variable_Craft("ShipType", Event.ShipType.ToString());
            Variable_Craft("ShipType_Localised", Event.ShipType_Localised.ToString());
            Variable_Craft("ShipID", Event.ShipID.ToString());
            Variable_Craft("System", Event.System.ToString());
            Variable_Craft("ShipMarketID", Event.ShipMarketID.ToString());
            Variable_Craft("Distance", Event.Distance.ToString());
            Variable_Craft("TransferPrice", Event.TransferPrice.ToString());
            Variable_Craft("TransferTime", Event.TransferTime.ToString());
            Variable_Craft("MarketID", Event.MarketID.ToString());
            #endregion
        }
    }

    #region ShipyardTransfer Event
    public class ShipyardTransfer : Base
    {
        public string ShipType { get; set; }
        public string ShipType_Localised { get; set; }
        public decimal ShipID { get; set; }
        public string System { get; set; }
        public decimal ShipMarketID { get; set; }
        public decimal Distance { get; set; }
        public decimal TransferPrice { get; set; }
        public decimal TransferTime { get; set; }
        public decimal MarketID { get; set; }
    }
    #endregion
}


//Journal Reader Code Chunk.

// else if (EventName == "ShipyardTransfer")
// {
//     var Event = JsonConvert.DeserializeObject<ALICE_Events.ShipyardTransfer>(RawLine);
//     Manager.UpdateEvents(EventName, Event);
//     Manager.ShipyardTransfer.Logic();
// }
