//Code Generated By Project A.L.I.C.E Developer Toolkit
//Class File Generated: 01/18/2026 4:27 PM
//Source Journal Line: { "timestamp":"2026-01-10T18:47:19Z", "event":"CrimeVictim", "Offender":"RIPTHEREAPER", "CrimeType":"assault", "Bounty":300 }

using System;
using System.Collections.Generic;

namespace ALICE_Events
{
    public class Event_CrimeVictim : Event_Base
    {
        public Event_CrimeVictim()
        {
            Name = "CrimeVictim";
        }

        public void Logic()
        {
            if (Manager.WriteVariables && WriteVariables)
            {
                try
                {
                    Variables_Clear();
                    Variables_Generate();
                    Variables_Write();
                }
                catch (Exception ex)
                {
                    Internal.Exception(Name, "An Exception Occured While Updating Variables");
                    Internal.Exception(Name, "Exception: " + ex);
                }
            }

            //GameState.Logic_CrimeVictim((CrimeVictim)GetEvent());

            TriggerEvent();
        }

        public void Variables_Generate()
        {
            CrimeVictim Event = (CrimeVictim)Manager.GetEvent(Name);

            Variables.Clear();

            #region Custom Variables

            #endregion

            #region Event Variables
            Variable_Craft("Offender", Event.Offender.ToString());
            Variable_Craft("CrimeType", Event.CrimeType.ToString());
            Variable_Craft("Bounty", Event.Bounty.ToString());
            #endregion
        }
    }

    #region CrimeVictim Event
    public class CrimeVictim : Base
    {
        public string Offender { get; set; }
        public string CrimeType { get; set; }
        public decimal Bounty { get; set; }
    }
    #endregion
}


//Journal Reader Code Chunk.

// else if (EventName == "CrimeVictim")
// {
//     var Event = JsonConvert.DeserializeObject<ALICE_Events.CrimeVictim>(RawLine);
//     Manager.UpdateEvents(EventName, Event);
//     Manager.CrimeVictim.Logic();
// }
