//Code Generated By Project A.L.I.C.E Developer Toolkit
//Class File Generated: 01/18/2026 4:27 PM
//Source Journal Line: { "timestamp":"2026-01-10T23:14:27Z", "event":"BackpackChange", "Removed":[ { "Name":"amm_grenade_shield", "Name_Localised":"Shield Projector", "OwnerID":0, "Count":1, "Type":"Consumable" } ] }

using System;
using System.Collections.Generic;

namespace ALICE_Events
{
    public class Event_BackpackChange : Event_Base
    {
        public Event_BackpackChange()
        {
            Name = "BackpackChange";
        }

        public void Logic()
        {
            if (Manager.WriteVariables && WriteVariables)
            {
                try
                {
                    Variables_Clear();
                    Variables_Generate();
                    Variables_Write();
                }
                catch (Exception ex)
                {
                    Internal.Exception(Name, "An Exception Occured While Updating Variables");
                    Internal.Exception(Name, "Exception: " + ex);
                }
            }

            //GameState.Logic_BackpackChange((BackpackChange)GetEvent());

            TriggerEvent();
        }

        public void Variables_Generate()
        {
            BackpackChange Event = (BackpackChange)Manager.GetEvent(Name);

            Variables.Clear();

            #region Custom Variables

            #endregion

            #region Event Variables
            Variable_Craft("Removed", Event.Removed.ToString());
            #endregion
        }
    }

    #region BackpackChange Event
    public class BackpackChange : Base
    {
        public string Removed { get; set; }
    }
    #endregion
}


//Journal Reader Code Chunk.

// else if (EventName == "BackpackChange")
// {
//     var Event = JsonConvert.DeserializeObject<ALICE_Events.BackpackChange>(RawLine);
//     Manager.UpdateEvents(EventName, Event);
//     Manager.BackpackChange.Logic();
// }
