//Code Generated By Project A.L.I.C.E Developer Toolkit
//Class File Generated: 01/18/2026 4:27 PM
//Source Journal Line: { "timestamp":"2026-01-11T00:45:37Z", "event":"DockSRV", "SRVType":"combat_multicrew_srv_01", "SRVType_Localised":"SRV Scorpion", "ID":34 }

using System;
using System.Collections.Generic;

namespace ALICE_Events
{
    public class Event_DockSRV : Event_Base
    {
        public Event_DockSRV()
        {
            Name = "DockSRV";
        }

        public void Logic()
        {
            if (Manager.WriteVariables && WriteVariables)
            {
                try
                {
                    Variables_Clear();
                    Variables_Generate();
                    Variables_Write();
                }
                catch (Exception ex)
                {
                    Internal.Exception(Name, "An Exception Occured While Updating Variables");
                    Internal.Exception(Name, "Exception: " + ex);
                }
            }

            //GameState.Logic_DockSRV((DockSRV)GetEvent());

            TriggerEvent();
        }

        public void Variables_Generate()
        {
            DockSRV Event = (DockSRV)Manager.GetEvent(Name);

            Variables.Clear();

            #region Custom Variables

            #endregion

            #region Event Variables
            Variable_Craft("SRVType", Event.SRVType.ToString());
            Variable_Craft("SRVType_Localised", Event.SRVType_Localised.ToString());
            Variable_Craft("ID", Event.ID.ToString());
            #endregion
        }
    }

    #region DockSRV Event
    public class DockSRV : Base
    {
        public string SRVType { get; set; }
        public string SRVType_Localised { get; set; }
        public decimal ID { get; set; }
    }
    #endregion
}


//Journal Reader Code Chunk.

// else if (EventName == "DockSRV")
// {
//     var Event = JsonConvert.DeserializeObject<ALICE_Events.DockSRV>(RawLine);
//     Manager.UpdateEvents(EventName, Event);
//     Manager.DockSRV.Logic();
// }
