//Code Generated By Project A.L.I.C.E Developer Toolkit
//Class File Generated: 01/18/2026 4:27 PM
//Source Journal Line: { "timestamp":"2026-01-10T15:06:41Z", "event":"ModuleBuy", "Slot":"PowerDistributor", "SellItem":"$int_powerdistributor_size4_class1_name;", "SellItem_Localised":"Power Distributor", "SellPrice":9958, "BuyItem":"$int_powerdistributor_size4_class5_name;", "BuyItem_Localised":"Power Distributor", "MarketID":128666762, "BuyPrice":389022, "Ship":"type8", "ShipID":40 }

using System;
using System.Collections.Generic;

namespace ALICE_Events
{
    public class Event_ModuleBuy : Event_Base
    {
        public Event_ModuleBuy()
        {
            Name = "ModuleBuy";
        }

        public void Logic()
        {
            if (Manager.WriteVariables && WriteVariables)
            {
                try
                {
                    Variables_Clear();
                    Variables_Generate();
                    Variables_Write();
                }
            }

            //GameState.Logic_ModuleBuy((ModuleBuy)GetEvent());

            TriggerEvent();
        }

        public void Variables_Generate()
        {
            ModuleBuy Event = (ModuleBuy)Manager.GetEvent(Name);

            Variables.Clear();

            #region Custom Variables

            #endregion

            #region Event Variables
            Variable_Craft("Slot", Event.Slot.ToString());
            Variable_Craft("SellItem", Event.SellItem.ToString());
            Variable_Craft("SellItem_Localised", Event.SellItem_Localised.ToString());
            Variable_Craft("SellPrice", Event.SellPrice.ToString());
            Variable_Craft("BuyItem", Event.BuyItem.ToString());
            Variable_Craft("BuyItem_Localised", Event.BuyItem_Localised.ToString());
            Variable_Craft("MarketID", Event.MarketID.ToString());
            Variable_Craft("BuyPrice", Event.BuyPrice.ToString());
            Variable_Craft("Ship", Event.Ship.ToString());
            Variable_Craft("ShipID", Event.ShipID.ToString());
            #endregion
        }
    }

    #region ModuleBuy Event
    public class ModuleBuy : Base
    {
        public string Slot { get; set; }
        public string SellItem { get; set; }
        public string SellItem_Localised { get; set; }
        public decimal SellPrice { get; set; }
        public string BuyItem { get; set; }
        public string BuyItem_Localised { get; set; }
        public decimal MarketID { get; set; }
        public decimal BuyPrice { get; set; }
        public string Ship { get; set; }
        public decimal ShipID { get; set; }
    }
    #endregion
}


//Journal Reader Code Chunk.

// else if (EventName == "ModuleBuy")
// {
//     var Event = JsonConvert.DeserializeObject<ALICE_Events.ModuleBuy>(RawLine);
//     Manager.UpdateEvents(EventName, Event);
//     Manager.ModuleBuy.Logic();
// }
