//Code Generated By Project A.L.I.C.E Developer Toolkit
//Class File Generated: 01/18/2026 4:27 PM
//Source Journal Line: { "timestamp":"2025-11-12T09:47:53Z", "event":"NavRouteClear" }

using System;
using System.Collections.Generic;

namespace ALICE_Events
{
    public class Event_NavRouteClear : Event_Base
    {
        public Event_NavRouteClear()
        {
            Name = "NavRouteClear";
        }

        public void Logic()
        {
            if (Manager.WriteVariables && WriteVariables)
            {
                try
                {
                    Variables_Clear();
                    Variables_Generate();
                    Variables_Write();
                }
            }

            //GameState.Logic_NavRouteClear((NavRouteClear)GetEvent());

            TriggerEvent();
        }

        public void Variables_Generate()
        {
            NavRouteClear Event = (NavRouteClear)Manager.GetEvent(Name);

            Variables.Clear();

            #region Custom Variables

            #endregion

            #region Event Variables
            #endregion
        }
    }

    #region NavRouteClear Event
    public class NavRouteClear : Base
    {
    }
    #endregion
}


//Journal Reader Code Chunk.

// else if (EventName == "NavRouteClear")
// {
//     var Event = JsonConvert.DeserializeObject<ALICE_Events.NavRouteClear>(RawLine);
//     Manager.UpdateEvents(EventName, Event);
//     Manager.NavRouteClear.Logic();
// }
