//Code Generated By Project A.L.I.C.E Developer Toolkit
//Class File Generated: 01/18/2026 4:27 PM
//Source Journal Line: { "timestamp":"2026-01-08T08:55:32Z", "event":"ModuleRetrieve", "MarketID":128666762, "Slot":"Slot06_Size5", "RetrievedItem":"$int_cargorack_size5_class1_name;", "RetrievedItem_Localised":"Cargo Rack", "Ship":"type8", "ShipID":36, "Hot":false, "SwapOutItem":"$int_shieldgenerator_size4_class1_name;", "SwapOutItem_Localised":"Shield Generator" }

using System;
using System.Collections.Generic;

namespace ALICE_Events
{
    public class Event_ModuleRetrieve : Event_Base
    {
        public Event_ModuleRetrieve()
        {
            Name = "ModuleRetrieve";
        }

        public void Logic()
        {
            if (Manager.WriteVariables && WriteVariables)
            {
                try
                {
                    Variables_Clear();
                    Variables_Generate();
                    Variables_Write();
                }
                catch (Exception ex)
                {
                    Internal.Exception(Name, "An Exception Occured While Updating Variables");
                    Internal.Exception(Name, "Exception: " + ex);
                }
            }

            //GameState.Logic_ModuleRetrieve((ModuleRetrieve)GetEvent());

            TriggerEvent();
        }

        public void Variables_Generate()
        {
            ModuleRetrieve Event = (ModuleRetrieve)Manager.GetEvent(Name);

            Variables.Clear();

            #region Custom Variables

            #endregion

            #region Event Variables
            Variable_Craft("MarketID", Event.MarketID.ToString());
            Variable_Craft("Slot", Event.Slot.ToString());
            Variable_Craft("RetrievedItem", Event.RetrievedItem.ToString());
            Variable_Craft("RetrievedItem_Localised", Event.RetrievedItem_Localised.ToString());
            Variable_Craft("Ship", Event.Ship.ToString());
            Variable_Craft("ShipID", Event.ShipID.ToString());
            Variable_Craft("Hot", Event.Hot.ToString());
            Variable_Craft("SwapOutItem", Event.SwapOutItem.ToString());
            Variable_Craft("SwapOutItem_Localised", Event.SwapOutItem_Localised.ToString());
            #endregion
        }
    }

    #region ModuleRetrieve Event
    public class ModuleRetrieve : Base
    {
        public decimal MarketID { get; set; }
        public string Slot { get; set; }
        public string RetrievedItem { get; set; }
        public string RetrievedItem_Localised { get; set; }
        public string Ship { get; set; }
        public decimal ShipID { get; set; }
        public string Hot { get; set; }
        public string SwapOutItem { get; set; }
        public string SwapOutItem_Localised { get; set; }
    }
    #endregion
}


//Journal Reader Code Chunk.

// else if (EventName == "ModuleRetrieve")
// {
//     var Event = JsonConvert.DeserializeObject<ALICE_Events.ModuleRetrieve>(RawLine);
//     Manager.UpdateEvents(EventName, Event);
//     Manager.ModuleRetrieve.Logic();
// }
