//Code Generated By Project A.L.I.C.E Developer Toolkit
//Class File Generated: 11/12/2018 4:40 PM
//Source Journal Line: { "timestamp":"2018-09-16T11:42:23Z", "event":"EngineerProgress", "Engineer":"Elvira Martuuk", "EngineerID":300160, "Progress":"Unlocked", "Rank":1 }

using System;
using System.Collections.Generic;

namespace ALICE_Events
{
    /// <summary>
    /// Object Data Class
    /// </summary>
    public class EngineerProgress : Base
    {
        public string Engineers { get; set; }

        //Default Constructor
        public EngineerProgress()
        {
            Engineers = Str();
        }
    }

    /// <summary>
    /// Event Logic & Data Storage Class
    /// </summary>
    public class Event_EngineerProgress : Event
    {
        //Plugin Logic Process
        public override void Process(object O)
        {
            try
            {
                var Event = (EngineerProgress)O;
            }
            catch (Exception ex)
            {
                ExceptionProcess(Name, ex);
            }
        }
    }
}
