//Code Generated By Project A.L.I.C.E Developer Toolkit
//Class File Generated: 01/18/2026 4:27 PM
//Source Journal Line: { "timestamp":"2026-01-11T00:11:18Z", "event":"FSSAllBodiesFound", "SystemName":"Core Sys Sector QT-R b4-5", "SystemAddress":11665802339769, "Count":2 }

using System;
using System.Collections.Generic;

namespace ALICE_Events
{
    public class Event_FSSAllBodiesFound : Event_Base
    {
        public Event_FSSAllBodiesFound()
        {
            Name = "FSSAllBodiesFound";
        }

        public void Logic()
        {
            if (Manager.WriteVariables && WriteVariables)
            {
                try
                {
                    Variables_Clear();
                    Variables_Generate();
                    Variables_Write();
                }
            }

            //GameState.Logic_FSSAllBodiesFound((FSSAllBodiesFound)GetEvent());

            TriggerEvent();
        }

        public void Variables_Generate()
        {
            FSSAllBodiesFound Event = (FSSAllBodiesFound)Manager.GetEvent(Name);

            Variables.Clear();

            #region Custom Variables

            #endregion

            #region Event Variables
            Variable_Craft("SystemName", Event.SystemName.ToString());
            Variable_Craft("SystemAddress", Event.SystemAddress.ToString());
            Variable_Craft("Count", Event.Count.ToString());
            #endregion
        }
    }

    #region FSSAllBodiesFound Event
    public class FSSAllBodiesFound : Base
    {
        public string SystemName { get; set; }
        public decimal SystemAddress { get; set; }
        public decimal Count { get; set; }
    }
    #endregion
}


//Journal Reader Code Chunk.

// else if (EventName == "FSSAllBodiesFound")
// {
//     var Event = JsonConvert.DeserializeObject<ALICE_Events.FSSAllBodiesFound>(RawLine);
//     Manager.UpdateEvents(EventName, Event);
//     Manager.FSSAllBodiesFound.Logic();
// }
