//Code Generated By Project A.L.I.C.E Developer Toolkit
//Class File Generated: 01/18/2026 4:27 PM
//Source Journal Line: { "timestamp":"2026-01-16T00:18:44Z", "event":"CommunityGoal", "CurrentGoals":[ { "CGID":840, "Title":"Distant Worlds III Deep-Space Infrastructure Project", "SystemName":"Alrai", "MarketName":"Surveyor’s Reach", "Expiry":"2026-01-17T16:00:00Z", "IsComplete":false, "CurrentTotal":250493335, "PlayerContribution":1232, "NumContributors":16651, "TopTier":{ "Name":"Tier 5", "Bonus":"" }, "TopRankSize":10, "PlayerInTopRank":false, "TierReached":"Tier 3", "PlayerPercentileBand":100, "Bonus":45000000 } ] }

using System;
using System.Collections.Generic;

namespace ALICE_Events
{
    public class Event_CommunityGoal : Event_Base
    {
        public Event_CommunityGoal()
        {
            Name = "CommunityGoal";
        }

        public void Logic()
        {
            if (Manager.WriteVariables && WriteVariables)
            {
                try
                {
                    Variables_Clear();
                    Variables_Generate();
                    Variables_Write();
                }
            }

            //GameState.Logic_CommunityGoal((CommunityGoal)GetEvent());

            TriggerEvent();
        }

        public void Variables_Generate()
        {
            CommunityGoal Event = (CommunityGoal)Manager.GetEvent(Name);

            Variables.Clear();

            #region Custom Variables

            #endregion

            #region Event Variables
            Variable_Craft("CurrentGoals", Event.CurrentGoals.ToString());
            #endregion
        }
    }

    #region CommunityGoal Event
    public class CommunityGoal : Base
    {
        public string CurrentGoals { get; set; }
    }
    #endregion
}


//Journal Reader Code Chunk.

// else if (EventName == "CommunityGoal")
// {
//     var Event = JsonConvert.DeserializeObject<ALICE_Events.CommunityGoal>(RawLine);
//     Manager.UpdateEvents(EventName, Event);
//     Manager.CommunityGoal.Logic();
// }
