//Code Generated By Project A.L.I.C.E Developer Toolkit
//Class File Generated: 01/18/2026 4:27 PM
//Source Journal Line: { "timestamp":"2026-01-07T15:35:27Z", "event":"CarrierBankTransfer", "CarrierID":3714546688, "CarrierType":"SquadronCarrier", "Withdraw":1000000000, "PlayerBalance":1735560326, "CarrierBalance":1065000000 }

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using ALICE_Ships_Datalink_Interface;
using ALICE_Command_Interface;
using ALICE_Internal;

namespace ALICE_Events
{
    public class Event_CarrierBankTransfer : Event_Base
    {
        public Event_CarrierBankTransfer()
        {
            Name = "CarrierBankTransfer";
        }

        public void Logic()
        {
            if (Manager.WriteVariables && WriteVariables)
            {
                try
                {
                    Variables_Clear();
                    Variables_Generate();
                    Variables_Write();
                }
            }

            //GameState.Logic_CarrierBankTransfer((CarrierBankTransfer)GetEvent());

            TriggerEvent();
        }

        public void Variables_Generate()
        {
            CarrierBankTransfer Event = (CarrierBankTransfer)Manager.GetEvent(Name);

            Variables.Clear();

            #region Custom Variables

            #endregion

            #region Event Variables
            Variable_Craft("CarrierID", Event.CarrierID.ToString());
            Variable_Craft("CarrierType", Event.CarrierType.ToString());
            Variable_Craft("Withdraw", Event.Withdraw.ToString());
            Variable_Craft("PlayerBalance", Event.PlayerBalance.ToString());
            Variable_Craft("CarrierBalance", Event.CarrierBalance.ToString());
            #endregion
        }
    }

    #region CarrierBankTransfer Event
    public class CarrierBankTransfer : Base
    {
        public decimal CarrierID { get; set; }
        public string CarrierType { get; set; }
        public decimal Withdraw { get; set; }
        public decimal PlayerBalance { get; set; }
        public decimal CarrierBalance { get; set; }
    }
    #endregion
}


//Journal Reader Code Chunk.

// else if (EventName == "CarrierBankTransfer")
// {
//     var Event = JsonConvert.DeserializeObject<ALICE_Events.CarrierBankTransfer>(RawLine);
//     Manager.UpdateEvents(EventName, Event);
//     Manager.CarrierBankTransfer.Logic();
// }
