//Code Generated By Project A.L.I.C.E Developer Toolkit
//Class File Generated: 01/18/2026 4:27 PM
//Source Journal Line: { "timestamp":"2026-01-17T20:34:24Z", "event":"CommunityGoalReward", "CGID":840, "Name":"Distant Worlds III Deep-Space Infrastructure Project", "System":"Alrai", "Reward":100000000 }

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using ALICE_Ships_Datalink_Interface;
using ALICE_Command_Interface;
using ALICE_Internal;

namespace ALICE_Events
{
    public class Event_CommunityGoalReward : Event_Base
    {
        public Event_CommunityGoalReward()
        {
            Name = "CommunityGoalReward";
        }

        public void Logic()
        {
            if (Manager.WriteVariables && WriteVariables)
            {
                try
                {
                    Variables_Clear();
                    Variables_Generate();
                    Variables_Write();
                }
            }

            //GameState.Logic_CommunityGoalReward((CommunityGoalReward)GetEvent());

            TriggerEvent();
        }

        public void Variables_Generate()
        {
            CommunityGoalReward Event = (CommunityGoalReward)Manager.GetEvent(Name);

            Variables.Clear();

            #region Custom Variables

            #endregion

            #region Event Variables
            Variable_Craft("CGID", Event.CGID.ToString());
            Variable_Craft("Name", Event.Name.ToString());
            Variable_Craft("System", Event.System.ToString());
            Variable_Craft("Reward", Event.Reward.ToString());
            #endregion
        }
    }

    #region CommunityGoalReward Event
    public class CommunityGoalReward : Base
    {
        public decimal CGID { get; set; }
        public string Name { get; set; }
        public string System { get; set; }
        public decimal Reward { get; set; }
    }
    #endregion
}


//Journal Reader Code Chunk.

// else if (EventName == "CommunityGoalReward")
// {
//     var Event = JsonConvert.DeserializeObject<ALICE_Events.CommunityGoalReward>(RawLine);
//     Manager.UpdateEvents(EventName, Event);
//     Manager.CommunityGoalReward.Logic();
// }
