//Code Generated By Project A.L.I.C.E Developer Toolkit
//Class File Generated: 01/18/2026 4:27 PM
//Source Journal Line: { "timestamp":"2025-11-12T10:57:05Z", "event":"ApproachSettlement", "Name":"McDevitt Settlement", "MarketID":3507690240, "StationFaction":{ "Name":"HIP 9774 Anarchists", "FactionState":"CivilWar" }, "StationGovernment":"$government_Anarchy;", "StationGovernment_Localised":"Anarchy", "StationAllegiance":"Empire", "StationServices":[ "dock", "autodock", "blackmarket", "commodities", "contacts", "exploration", "missions", "outfitting", "crewlounge", "rearm", "refuel", "repair", "shipyard", "tuning", "engineer", "missionsgenerated", "facilitator", "flightcontroller", "stationoperations", "powerplay", "stationMenu", "shop", "livery", "socialspace", "bartender", "vistagenomics", "pioneersupplies", "apexinterstellar", "frontlinesolutions", "registeringcolonisation" ], "StationEconomy":"$economy_Colony;", "StationEconomy_Localised":"Colony", "StationEconomies":[ { "Name":"$economy_Colony;", "Name_Localised":"Colony", "Proportion":1.000000 } ], "SystemAddress":1659761559907, "BodyID":25, "BodyName":"HIP 9774 A 3 a", "Latitude":-51.718937, "Longitude":-47.780975 }

using System;
using System.Collections.Generic;

namespace ALICE_Events
{
    public class Event_ApproachSettlement : Event_Base
    {
        public Event_ApproachSettlement()
        {
            Name = "ApproachSettlement";
        }

        public void Logic()
        {
            if (Manager.WriteVariables && WriteVariables)
            {
                try
                {
                    Variables_Clear();
                    Variables_Generate();
                    Variables_Write();
                }
            }

            //GameState.Logic_ApproachSettlement((ApproachSettlement)GetEvent());

            TriggerEvent();
        }

        public void Variables_Generate()
        {
            ApproachSettlement Event = (ApproachSettlement)Manager.GetEvent(Name);

            Variables.Clear();

            #region Custom Variables

            #endregion

            #region Event Variables
            Variable_Craft("Name", Event.Name.ToString());
            Variable_Craft("MarketID", Event.MarketID.ToString());
            Variable_Craft("StationFaction", Event.StationFaction.ToString());
            Variable_Craft("StationGovernment", Event.StationGovernment.ToString());
            Variable_Craft("StationGovernment_Localised", Event.StationGovernment_Localised.ToString());
            Variable_Craft("StationAllegiance", Event.StationAllegiance.ToString());
            Variable_Craft("StationServices", Event.StationServices.ToString());
            Variable_Craft("StationEconomy", Event.StationEconomy.ToString());
            Variable_Craft("StationEconomy_Localised", Event.StationEconomy_Localised.ToString());
            Variable_Craft("StationEconomies", Event.StationEconomies.ToString());
            Variable_Craft("SystemAddress", Event.SystemAddress.ToString());
            Variable_Craft("BodyID", Event.BodyID.ToString());
            Variable_Craft("BodyName", Event.BodyName.ToString());
            Variable_Craft("Latitude", Event.Latitude.ToString());
            Variable_Craft("Longitude", Event.Longitude.ToString());
            #endregion
        }
    }

    #region ApproachSettlement Event
    public class ApproachSettlement : Base
    {
        public string Name { get; set; }
        public decimal MarketID { get; set; }
        public string StationFaction { get; set; }
        public string StationGovernment { get; set; }
        public string StationGovernment_Localised { get; set; }
        public string StationAllegiance { get; set; }
        public string StationServices { get; set; }
        public string StationEconomy { get; set; }
        public string StationEconomy_Localised { get; set; }
        public string StationEconomies { get; set; }
        public decimal SystemAddress { get; set; }
        public decimal BodyID { get; set; }
        public string BodyName { get; set; }
        public decimal Latitude { get; set; }
        public decimal Longitude { get; set; }
    }
    #endregion
}


//Journal Reader Code Chunk.

// else if (EventName == "ApproachSettlement")
// {
//     var Event = JsonConvert.DeserializeObject<ALICE_Events.ApproachSettlement>(RawLine);
//     Manager.UpdateEvents(EventName, Event);
//     Manager.ApproachSettlement.Logic();
// }
