//Code Generated By Project A.L.I.C.E Developer Toolkit
//Class File Generated: 01/18/2026 4:27 PM
//Source Journal Line: { "timestamp":"2025-11-12T09:17:48Z", "event":"ShipLocker", "Items":[  ], "Components":[  ], "Consumables":[ { "Name":"healthpack", "Name_Localised":"Medkit", "OwnerID":0, "Count":100 }, { "Name":"energycell", "Name_Localised":"Energy Cell", "OwnerID":0, "Count":100 }, { "Name":"amm_grenade_emp", "Name_Localised":"Shield Disruptor", "OwnerID":0, "Count":100 }, { "Name":"amm_grenade_frag", "Name_Localised":"Frag Grenade", "OwnerID":0, "Count":100 }, { "Name":"amm_grenade_shield", "Name_Localised":"Shield Projector", "OwnerID":0, "Count":100 }, { "Name":"bypass", "Name_Localised":"E-Breach", "OwnerID":0, "Count":100 } ], "Data":[  ] }

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using ALICE_Ships_Datalink_Interface;
using ALICE_Command_Interface;
using ALICE_Internal;

namespace ALICE_Events
{
    public class Event_ShipLocker : Event_Base
    {
        public Event_ShipLocker()
        {
            Name = "ShipLocker";
        }

        public void Logic()
        {
            if (Manager.WriteVariables && WriteVariables)
            {
                try
                {
                    Variables_Clear();
                    Variables_Generate();
                    Variables_Write();
                }
            }

            //GameState.Logic_ShipLocker((ShipLocker)GetEvent());

            TriggerEvent();
        }

        public void Variables_Generate()
        {
            ShipLocker Event = (ShipLocker)Manager.GetEvent(Name);

            Variables.Clear();

            #region Custom Variables

            #endregion

            #region Event Variables
            Variable_Craft("Items", Event.Items.ToString());
            Variable_Craft("Components", Event.Components.ToString());
            Variable_Craft("Consumables", Event.Consumables.ToString());
            Variable_Craft("Data", Event.Data.ToString());
            #endregion
        }
    }

    #region ShipLocker Event
    public class ShipLocker : Base
    {
        public string Items { get; set; }
        public string Components { get; set; }
        public string Consumables { get; set; }
        public string Data { get; set; }
    }
    #endregion
}


//Journal Reader Code Chunk.

// else if (EventName == "ShipLocker")
// {
//     var Event = JsonConvert.DeserializeObject<ALICE_Events.ShipLocker>(RawLine);
//     Manager.UpdateEvents(EventName, Event);
//     Manager.ShipLocker.Logic();
// }
