//Code Generated By Project A.L.I.C.E Developer Toolkit
//Class File Generated: 01/18/2026 4:27 PM
//Source Journal Line: { "timestamp":"2026-01-10T14:54:33Z", "event":"WingLeave" }

using System;

namespace ALICE_Events
{
    public class Event_WingLeave : Event_Base
    {
        public Event_WingLeave()
        {
            Name = "WingLeave";
        }

        public void Logic()
        {
            if (Manager.WriteVariables && WriteVariables)
            {
                    Variables_Clear();
                    Variables_Generate();
                    Variables_Write();
            }

            //GameState.Logic_WingLeave((WingLeave)GetEvent());

            TriggerEvent();
        }

        public void Variables_Generate()
        {
            WingLeave Event = (WingLeave)Manager.GetEvent(Name);

            Variables.Clear();

            #region Custom Variables

            #endregion

            #region Event Variables
            #endregion
        }
    }

    #region WingLeave Event
    public class WingLeave : Base
    {
    }
    #endregion
}


//Journal Reader Code Chunk.

// else if (EventName == "WingLeave")
// {
//     var Event = JsonConvert.DeserializeObject<ALICE_Events.WingLeave>(RawLine);
//     Manager.UpdateEvents(EventName, Event);
//     Manager.WingLeave.Logic();
// }
