//Code Generated By Project A.L.I.C.E Developer Toolkit
//Class File Generated: 01/18/2026 4:27 PM
//Source Journal Line: { "timestamp":"2025-11-12T11:25:10Z", "event":"UnderAttack", "Target":"You" }

using System;
using System.Collections.Generic;

namespace ALICE_Events
{
    public class Event_UnderAttack : Event_Base
    {
        public Event_UnderAttack()
        {
            Name = "UnderAttack";
        }

        public void Logic()
        {
            if (Manager.WriteVariables && WriteVariables)
            {
                try
                {
                    Variables_Clear();
                    Variables_Generate();
                    Variables_Write();
                }
            }

            //GameState.Logic_UnderAttack((UnderAttack)GetEvent());

            TriggerEvent();
        }

        public void Variables_Generate()
        {
            UnderAttack Event = (UnderAttack)Manager.GetEvent(Name);

            Variables.Clear();

            #region Custom Variables

            #endregion

            #region Event Variables
            Variable_Craft("Target", Event.Target.ToString());
            #endregion
        }
    }

    #region UnderAttack Event
    public class UnderAttack : Base
    {
        public string Target { get; set; }
    }
    #endregion
}


//Journal Reader Code Chunk.

// else if (EventName == "UnderAttack")
// {
//     var Event = JsonConvert.DeserializeObject<ALICE_Events.UnderAttack>(RawLine);
//     Manager.UpdateEvents(EventName, Event);
//     Manager.UnderAttack.Logic();
// }
