//Code Generated By Project A.L.I.C.E Developer Toolkit
//Class File Generated: 01/18/2026 4:27 PM
//Source Journal Line: { "timestamp":"2026-01-10T15:33:58Z", "event":"HullDamage", "Health":0.650889, "PlayerPilot":true, "Fighter":false }

using System;
using System.Collections.Generic;

namespace ALICE_Events
{
    public class Event_HullDamage : Event_Base
    {
        public Event_HullDamage()
        {
            Name = "HullDamage";
        }

        public void Logic()
        {
            if (Manager.WriteVariables && WriteVariables)
            {
                try
                {
                    Variables_Clear();
                    Variables_Generate();
                    Variables_Write();
                }
            }

            //GameState.Logic_HullDamage((HullDamage)GetEvent());

            TriggerEvent();
        }

        public void Variables_Generate()
        {
            HullDamage Event = (HullDamage)Manager.GetEvent(Name);

            Variables.Clear();

            #region Custom Variables

            #endregion

            #region Event Variables
            Variable_Craft("Health", Event.Health.ToString());
            Variable_Craft("PlayerPilot", Event.PlayerPilot.ToString());
            Variable_Craft("Fighter", Event.Fighter.ToString());
            #endregion
        }
    }

    #region HullDamage Event
    public class HullDamage : Base
    {
        public decimal Health { get; set; }
        public string PlayerPilot { get; set; }
        public string Fighter { get; set; }
    }
    #endregion
}


//Journal Reader Code Chunk.

// else if (EventName == "HullDamage")
// {
//     var Event = JsonConvert.DeserializeObject<ALICE_Events.HullDamage>(RawLine);
//     Manager.UpdateEvents(EventName, Event);
//     Manager.HullDamage.Logic();
// }
