//Code Generated By Project A.L.I.C.E Developer Toolkit
//Class File Generated: 01/18/2026 4:27 PM
//Source Journal Line: { "timestamp":"2026-01-16T00:17:06Z", "event":"DockingRequested", "MarketID":129032283, "StationName":"Surveyor’s Reach", "StationType":"SurfaceStation", "LandingPads":{ "Small":8, "Medium":8, "Large":16 } }

using System;
using System.Collections.Generic;

namespace ALICE_Events
{
    public class Event_DockingRequested : Event_Base
    {
        public Event_DockingRequested()
        {
            Name = "DockingRequested";
        }

        public void Logic()
        {
            if (Manager.WriteVariables && WriteVariables)
            {
                try
                {
                    Variables_Clear();
                    Variables_Generate();
                    Variables_Write();
                }
            }

            //GameState.Logic_DockingRequested((DockingRequested)GetEvent());

            TriggerEvent();
        }

        public void Variables_Generate()
        {
            DockingRequested Event = (DockingRequested)Manager.GetEvent(Name);

            Variables.Clear();

            #region Custom Variables

            #endregion

            #region Event Variables
            Variable_Craft("MarketID", Event.MarketID.ToString());
            Variable_Craft("StationName", Event.StationName.ToString());
            Variable_Craft("StationType", Event.StationType.ToString());
            Variable_Craft("LandingPads", Event.LandingPads.ToString());
            #endregion
        }
    }

    #region DockingRequested Event
    public class DockingRequested : Base
    {
        public decimal MarketID { get; set; }
        public string StationName { get; set; }
        public string StationType { get; set; }
        public string LandingPads { get; set; }
    }
    #endregion
}


//Journal Reader Code Chunk.

// else if (EventName == "DockingRequested")
// {
//     var Event = JsonConvert.DeserializeObject<ALICE_Events.DockingRequested>(RawLine);
//     Manager.UpdateEvents(EventName, Event);
//     Manager.DockingRequested.Logic();
// }
