//Code Generated By Project A.L.I.C.E Developer Toolkit
//Class File Generated: 01/18/2026 4:27 PM
//Source Journal Line: { "timestamp":"2026-01-12T02:00:56Z", "event":"DockingCancelled", "MarketID":128968675, "StationName":"Rackham's Peak", "StationType":"Outpost" }

using System;
using System.Collections.Generic;

namespace ALICE_Events
{
    public class Event_DockingCancelled : Event_Base
    {
        public Event_DockingCancelled()
        {
            Name = "DockingCancelled";
        }

        public void Logic()
        {
            if (Manager.WriteVariables && WriteVariables)
            {
                try
                {
                    Variables_Clear();
                    Variables_Generate();
                    Variables_Write();
                }
            }

            //GameState.Logic_DockingCancelled((DockingCancelled)GetEvent());

            TriggerEvent();
        }

        public void Variables_Generate()
        {
            DockingCancelled Event = (DockingCancelled)Manager.GetEvent(Name);

            Variables.Clear();

            #region Custom Variables

            #endregion

            #region Event Variables
            Variable_Craft("MarketID", Event.MarketID.ToString());
            Variable_Craft("StationName", Event.StationName.ToString());
            Variable_Craft("StationType", Event.StationType.ToString());
            #endregion
        }
    }

    #region DockingCancelled Event
    public class DockingCancelled : Base
    {
        public decimal MarketID { get; set; }
        public string StationName { get; set; }
        public string StationType { get; set; }
    }
    #endregion
}


//Journal Reader Code Chunk.

// else if (EventName == "DockingCancelled")
// {
//     var Event = JsonConvert.DeserializeObject<ALICE_Events.DockingCancelled>(RawLine);
//     Manager.UpdateEvents(EventName, Event);
//     Manager.DockingCancelled.Logic();
// }
