//Code Generated By Project A.L.I.C.E Developer Toolkit
//Class File Generated: 01/18/2026 4:27 PM
//Source Journal Line: { "timestamp":"2026-01-11T00:44:22Z", "event":"CommitCrime", "CrimeType":"fireInNoFireZone", "Faction":"Earth Defense Fleet", "Fine":100 }

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using ALICE_Ships_Datalink_Interface;
using ALICE_Command_Interface;
using ALICE_Internal;

namespace ALICE_Events
{
    public class Event_CommitCrime : Event_Base
    {
        public Event_CommitCrime()
        {
            Name = "CommitCrime";
        }

        public void Logic()
        {
            if (Manager.WriteVariables && WriteVariables)
            {
                try
                {
                    Variables_Clear();
                    Variables_Generate();
                    Variables_Write();
                }
                catch (Exception ex)
                {
                    Internal.Exception(Name, "An Exception Occured While Updating Variables");
                    Internal.Exception(Name, "Exception: " + ex);
                }
            }

            //GameState.Logic_CommitCrime((CommitCrime)GetEvent());

            TriggerEvent();
        }

        public void Variables_Generate()
        {
            CommitCrime Event = (CommitCrime)Manager.GetEvent(Name);

            Variables.Clear();

            #region Custom Variables

            #endregion

            #region Event Variables
            Variable_Craft("CrimeType", Event.CrimeType.ToString());
            Variable_Craft("Faction", Event.Faction.ToString());
            Variable_Craft("Fine", Event.Fine.ToString());
            #endregion
        }
    }

    #region CommitCrime Event
    public class CommitCrime : Base
    {
        public string CrimeType { get; set; }
        public string Faction { get; set; }
        public decimal Fine { get; set; }
    }
    #endregion
}


//Journal Reader Code Chunk.

// else if (EventName == "CommitCrime")
// {
//     var Event = JsonConvert.DeserializeObject<ALICE_Events.CommitCrime>(RawLine);
//     Manager.UpdateEvents(EventName, Event);
//     Manager.CommitCrime.Logic();
// }
