//Code Generated By Project A.L.I.C.E Developer Toolkit
//Class File Generated: 01/18/2026 4:27 PM
//Source Journal Line: { "timestamp":"2026-01-07T16:30:58Z", "event":"CargoTransfer", "Transfers":[ { "Type":"tritium", "Count":784, "Direction":"tocarrier" } ] }

using System;

namespace ALICE_Events
{
    public class Event_CargoTransfer : Event_Base
    {
        public Event_CargoTransfer()
        {
            Name = "CargoTransfer";
        }

        public void Logic()
        {
            if (Manager.WriteVariables && WriteVariables)
            {
                    Variables_Clear();
                    Variables_Generate();
                    Variables_Write();
            }

            //GameState.Logic_CargoTransfer((CargoTransfer)GetEvent());

            TriggerEvent();
        }

        public void Variables_Generate()
        {
            CargoTransfer Event = (CargoTransfer)Manager.GetEvent(Name);

            Variables.Clear();

            #region Custom Variables

            #endregion

            #region Event Variables
            Variable_Craft("Transfers", Event.Transfers.ToString());
            #endregion
        }
    }

    #region CargoTransfer Event
    public class CargoTransfer : Base
    {
        public string Transfers { get; set; }
    }
    #endregion
}


//Journal Reader Code Chunk.

// else if (EventName == "CargoTransfer")
// {
//     var Event = JsonConvert.DeserializeObject<ALICE_Events.CargoTransfer>(RawLine);
//     Manager.UpdateEvents(EventName, Event);
//     Manager.CargoTransfer.Logic();
// }
