//Code Generated By Project A.L.I.C.E Developer Toolkit
//Class File Generated: 01/18/2026 4:27 PM
//Source Journal Line: { "timestamp":"2026-01-10T22:23:39Z", "event":"SuitLoadout", "SuitID":1763747430586625, "SuitName":"tacticalsuit_class2", "SuitName_Localised":"$TacticalSuit_Class1_Name;", "SuitMods":[ "suit_reducedtoolbatteryconsumption" ], "LoadoutID":4293000002, "LoadoutName":"combat 2", "Modules":[ { "SlotName":"PrimaryWeapon1", "SuitModuleID":1763896492543420, "ModuleName":"wpn_m_submachinegun_laser_fauto", "ModuleName_Localised":"TK Eclipse", "Class":3, "WeaponMods":[ "weapon_handling" ] }, { "SlotName":"PrimaryWeapon2", "SuitModuleID":1766338459331283, "ModuleName":"wpn_m_submachinegun_kinetic_fauto", "ModuleName_Localised":"Karma C-44", "Class":3, "WeaponMods":[  ] }, { "SlotName":"SecondaryWeapon", "SuitModuleID":1763896499181480, "ModuleName":"wpn_s_pistol_laser_sauto", "ModuleName_Localised":"TK Zenith", "Class":3, "WeaponMods":[ "weapon_suppression_pressurised" ] } ] }

using System;
using System.Collections.Generic;

namespace ALICE_Events
{
    public class Event_SuitLoadout : Event_Base
    {
        public Event_SuitLoadout()
        {
            Name = "SuitLoadout";
        }

        public void Logic()
        {
            if (Manager.WriteVariables && WriteVariables)
            {
                try
                {
                    Variables_Clear();
                    Variables_Generate();
                    Variables_Write();
                }
                catch (Exception ex)
                {
                    Internal.Exception(Name, "An Exception Occured While Updating Variables");
                    Internal.Exception(Name, "Exception: " + ex);
                }
            }

            //GameState.Logic_SuitLoadout((SuitLoadout)GetEvent());

            TriggerEvent();
        }

        public void Variables_Generate()
        {
            SuitLoadout Event = (SuitLoadout)Manager.GetEvent(Name);

            Variables.Clear();

            #region Custom Variables

            #endregion

            #region Event Variables
            Variable_Craft("SuitID", Event.SuitID.ToString());
            Variable_Craft("SuitName", Event.SuitName.ToString());
            Variable_Craft("SuitName_Localised", Event.SuitName_Localised.ToString());
            Variable_Craft("SuitMods", Event.SuitMods.ToString());
            Variable_Craft("LoadoutID", Event.LoadoutID.ToString());
            Variable_Craft("LoadoutName", Event.LoadoutName.ToString());
            Variable_Craft("Modules", Event.Modules.ToString());
            #endregion
        }
    }

    #region SuitLoadout Event
    public class SuitLoadout : Base
    {
        public decimal SuitID { get; set; }
        public string SuitName { get; set; }
        public string SuitName_Localised { get; set; }
        public string SuitMods { get; set; }
        public decimal LoadoutID { get; set; }
        public string LoadoutName { get; set; }
        public string Modules { get; set; }
    }
    #endregion
}


//Journal Reader Code Chunk.

// else if (EventName == "SuitLoadout")
// {
//     var Event = JsonConvert.DeserializeObject<ALICE_Events.SuitLoadout>(RawLine);
//     Manager.UpdateEvents(EventName, Event);
//     Manager.SuitLoadout.Logic();
// }
