//Code Generated By Project A.L.I.C.E Developer Toolkit
//Class File Generated: 11/12/2018 1:27 AM
//Source Journal Line: { "timestamp":"2018-10-29T03:23:54Z", "event":"Synthesis", "Name":"Ammo Basic", "Materials":[ { "Name":"iron", "Count":2 }, { "Name":"nickel", "Count":1 }, { "Name":"sulphur", "Count":2 } ] }

using System;
using System.Collections.Generic;

namespace ALICE_Events
{
    /// <summary>
    /// Object Data Class
    /// </summary>
    public class Synthesis : Base
    {
        public string Name { get; set; }
        public string Materials { get; set; }

        //Default Constructor
        public Synthesis()
        {
            Name = Str();
            Materials = Str();
        }
    }

    /// <summary>
    /// Event Logic & Data Storage Class
    /// </summary>
    public class Event_Synthesis : Event
    {
        //Variable Generation
        public override void Generate(object O)
        {
            try
            {
                var Event = (Synthesis)O;

                Variables.Record(Name + "_Name", Event.Name);                
            }
            catch (Exception ex)
            {
                ExceptionGenerate(Name, ex);
            }
        }
    }
}