//Code Generated By Project A.L.I.C.E Developer Toolkit
//Class File Generated: 01/18/2026 4:27 PM
//Source Journal Line: { "timestamp":"2026-01-07T15:35:49Z", "event":"CarrierFinance", "CarrierID":3714546688, "CarrierType":"SquadronCarrier", "CarrierBalance":815000000, "ReserveBalance":0, "AvailableBalance":815000000, "ReservePercent":0, "TaxRate_pioneersupplies":5, "TaxRate_shipyard":0, "TaxRate_rearm":0, "TaxRate_outfitting":0, "TaxRate_refuel":0, "TaxRate_repair":0 }

using System;

namespace ALICE_Events
{
    public class Event_CarrierFinance : Event_Base
    {
        public Event_CarrierFinance()
        {
            Name = "CarrierFinance";
        }

        public void Logic()
        {
            if (Manager.WriteVariables && WriteVariables)
            {
                    Variables_Clear();
                    Variables_Generate();
                    Variables_Write();
            }

            //GameState.Logic_CarrierFinance((CarrierFinance)GetEvent());

            TriggerEvent();
        }

        public void Variables_Generate()
        {
            CarrierFinance Event = (CarrierFinance)Manager.GetEvent(Name);

            Variables.Clear();

            #region Custom Variables

            #endregion

            #region Event Variables
            Variable_Craft("CarrierID", Event.CarrierID.ToString());
            Variable_Craft("CarrierType", Event.CarrierType.ToString());
            Variable_Craft("CarrierBalance", Event.CarrierBalance.ToString());
            Variable_Craft("ReserveBalance", Event.ReserveBalance.ToString());
            Variable_Craft("AvailableBalance", Event.AvailableBalance.ToString());
            Variable_Craft("ReservePercent", Event.ReservePercent.ToString());
            Variable_Craft("TaxRate_pioneersupplies", Event.TaxRate_pioneersupplies.ToString());
            Variable_Craft("TaxRate_shipyard", Event.TaxRate_shipyard.ToString());
            Variable_Craft("TaxRate_rearm", Event.TaxRate_rearm.ToString());
            Variable_Craft("TaxRate_outfitting", Event.TaxRate_outfitting.ToString());
            Variable_Craft("TaxRate_refuel", Event.TaxRate_refuel.ToString());
            Variable_Craft("TaxRate_repair", Event.TaxRate_repair.ToString());
            #endregion
        }
    }

    #region CarrierFinance Event
    public class CarrierFinance : Base
    {
        public decimal CarrierID { get; set; }
        public string CarrierType { get; set; }
        public decimal CarrierBalance { get; set; }
        public decimal ReserveBalance { get; set; }
        public decimal AvailableBalance { get; set; }
        public decimal ReservePercent { get; set; }
        public decimal TaxRate_pioneersupplies { get; set; }
        public decimal TaxRate_shipyard { get; set; }
        public decimal TaxRate_rearm { get; set; }
        public decimal TaxRate_outfitting { get; set; }
        public decimal TaxRate_refuel { get; set; }
        public decimal TaxRate_repair { get; set; }
    }
    #endregion
}


//Journal Reader Code Chunk.

// else if (EventName == "CarrierFinance")
// {
//     var Event = JsonConvert.DeserializeObject<ALICE_Events.CarrierFinance>(RawLine);
//     Manager.UpdateEvents(EventName, Event);
//     Manager.CarrierFinance.Logic();
// }
