//Code Generated By Project A.L.I.C.E Developer Toolkit
//Class File Generated: 01/18/2026 4:27 PM
//Source Journal Line: { "timestamp":"2026-01-15T17:19:40Z", "event":"CarrierJumpRequest", "CarrierType":"SquadronCarrier", "CarrierID":3714546688, "SystemName":"Rho Ophiuchi Sector IH-U b3-1", "Body":"Rho Ophiuchi Sector IH-U b3-1", "SystemAddress":2870783649369, "BodyID":0, "DepartureTime":"2026-01-15T17:35:10Z" }

using System;

namespace ALICE_Events
{
    public class Event_CarrierJumpRequest : Event_Base
    {
        public Event_CarrierJumpRequest()
        {
            Name = "CarrierJumpRequest";
        }

        public void Logic()
        {
            if (Manager.WriteVariables && WriteVariables)
            {
                    Variables_Clear();
                    Variables_Generate();
                    Variables_Write();
            }

            //GameState.Logic_CarrierJumpRequest((CarrierJumpRequest)GetEvent());

            TriggerEvent();
        }

        public void Variables_Generate()
        {
            CarrierJumpRequest Event = (CarrierJumpRequest)Manager.GetEvent(Name);

            Variables.Clear();

            #region Custom Variables

            #endregion

            #region Event Variables
            Variable_Craft("CarrierType", Event.CarrierType.ToString());
            Variable_Craft("CarrierID", Event.CarrierID.ToString());
            Variable_Craft("SystemName", Event.SystemName.ToString());
            Variable_Craft("Body", Event.Body.ToString());
            Variable_Craft("SystemAddress", Event.SystemAddress.ToString());
            Variable_Craft("BodyID", Event.BodyID.ToString());
            Variable_Craft("DepartureTime", Event.DepartureTime.ToString());
            #endregion
        }
    }

    #region CarrierJumpRequest Event
    public class CarrierJumpRequest : Base
    {
        public string CarrierType { get; set; }
        public decimal CarrierID { get; set; }
        public string SystemName { get; set; }
        public string Body { get; set; }
        public decimal SystemAddress { get; set; }
        public decimal BodyID { get; set; }
        public string DepartureTime { get; set; }
    }
    #endregion
}


//Journal Reader Code Chunk.

// else if (EventName == "CarrierJumpRequest")
// {
//     var Event = JsonConvert.DeserializeObject<ALICE_Events.CarrierJumpRequest>(RawLine);
//     Manager.UpdateEvents(EventName, Event);
//     Manager.CarrierJumpRequest.Logic();
// }
