//Code Generated By Project A.L.I.C.E Developer Toolkit
//Class File Generated: 01/18/2026 4:27 PM
//Source Journal Line: { "timestamp":"2025-11-12T09:13:07Z", "event":"Fileheader", "part":1, "language":"English/UK", "Odyssey":true, "gameversion":"4.2.2.0", "build":"r320967/r0 " }

using System;

namespace ALICE_Events
{
    public class Event_Fileheader : Event_Base
    {
        public Event_Fileheader()
        {
            Name = "Fileheader";
        }

        public void Logic()
        {
            if (Manager.WriteVariables && WriteVariables)
            {
                    Variables_Clear();
                    Variables_Generate();
                    Variables_Write();
            }

            //GameState.Logic_Fileheader((Fileheader)GetEvent());

            TriggerEvent();
        }

        public void Variables_Generate()
        {
            Fileheader Event = (Fileheader)Manager.GetEvent(Name);

            Variables.Clear();

            #region Custom Variables

            #endregion

            #region Event Variables
            Variable_Craft("Part", Event.Part.ToString());
            Variable_Craft("Language", Event.Language.ToString());
            Variable_Craft("Odyssey", Event.Odyssey.ToString());
            Variable_Craft("Gameversion", Event.Gameversion.ToString());
            Variable_Craft("Build", Event.Build.ToString());
            #endregion
        }
    }

    #region Fileheader Event
    public class Fileheader : Base
    {
        public decimal Part { get; set; }
        public string Language { get; set; }
        public string Odyssey { get; set; }
        public string Gameversion { get; set; }
        public string Build { get; set; }
    }
    #endregion
}


//Journal Reader Code Chunk.

// else if (EventName == "Fileheader")
// {
//     var Event = JsonConvert.DeserializeObject<ALICE_Events.Fileheader>(RawLine);
//     Manager.UpdateEvents(EventName, Event);
//     Manager.Fileheader.Logic();
// }
