//Code Generated By Project A.L.I.C.E Developer Toolkit
//Class File Generated: 11/12/2018 1:27 AM
//Source Journal Line: { "timestamp":"2018-10-19T04:10:58Z", "event":"LaunchDrone", "Type":"Collection" }

using ALICE_Status;
using System;

namespace ALICE_Events
{
    /// <summary>
    /// Object Data Class
    /// </summary>
    public class LaunchDrone : Base
    {
        public string Type { get; set; }

        //Default Constructor
        public LaunchDrone()
        {
            Type = Str();
        }
    }

    /// <summary>
    /// Event Logic & Data Storage Class
    /// </summary>
    public class Event_LaunchDrone : Event
    {
        //Variable Generation
        public override void Generate(object O)
        {
                var Event = (LaunchDrone)O;

                Variables.Record(Name + "_Type", Event.Type);
        }

        //Plugin Property Aligment
        public override void Alignment(object O)
        {
                IStatus.Supercruise = false;
                IStatus.Hyperspace = false;
                IStatus.Touchdown = false;
                IStatus.Docking.Docked = false;
        }
    }
}