//Code Generated By Project A.L.I.C.E Developer Toolkit
//Class File Generated: 01/18/2026 4:27 PM
//Source Journal Line: { "timestamp":"2026-01-10T18:41:01Z", "event":"ScanBaryCentre", "StarSystem":"Palee", "SystemAddress":4923919960435, "BodyID":2, "SemiMajorAxis":6548910140991.210938, "Eccentricity":0.154441, "OrbitalInclination":150.229020, "Periapsis":343.819493, "OrbitalPeriod":14917109012.603760, "AscendingNode":-120.867775, "MeanAnomaly":329.079442 }

using System;
using System.Collections.Generic;

namespace ALICE_Events
{
    public class Event_ScanBaryCentre : Event_Base
    {
        public Event_ScanBaryCentre()
        {
            Name = "ScanBaryCentre";
        }

        public void Logic()
        {
            if (Manager.WriteVariables && WriteVariables)
            {
                try
                {
                    Variables_Clear();
                    Variables_Generate();
                    Variables_Write();
                }
            }

            //GameState.Logic_ScanBaryCentre((ScanBaryCentre)GetEvent());

            TriggerEvent();
        }

        public void Variables_Generate()
        {
            ScanBaryCentre Event = (ScanBaryCentre)Manager.GetEvent(Name);

            Variables.Clear();

            #region Custom Variables

            #endregion

            #region Event Variables
            Variable_Craft("StarSystem", Event.StarSystem.ToString());
            Variable_Craft("SystemAddress", Event.SystemAddress.ToString());
            Variable_Craft("BodyID", Event.BodyID.ToString());
            Variable_Craft("SemiMajorAxis", Event.SemiMajorAxis.ToString());
            Variable_Craft("Eccentricity", Event.Eccentricity.ToString());
            Variable_Craft("OrbitalInclination", Event.OrbitalInclination.ToString());
            Variable_Craft("Periapsis", Event.Periapsis.ToString());
            Variable_Craft("OrbitalPeriod", Event.OrbitalPeriod.ToString());
            Variable_Craft("AscendingNode", Event.AscendingNode.ToString());
            Variable_Craft("MeanAnomaly", Event.MeanAnomaly.ToString());
            #endregion
        }
    }

    #region ScanBaryCentre Event
    public class ScanBaryCentre : Base
    {
        public string StarSystem { get; set; }
        public decimal SystemAddress { get; set; }
        public decimal BodyID { get; set; }
        public decimal SemiMajorAxis { get; set; }
        public decimal Eccentricity { get; set; }
        public decimal OrbitalInclination { get; set; }
        public decimal Periapsis { get; set; }
        public decimal OrbitalPeriod { get; set; }
        public decimal AscendingNode { get; set; }
        public decimal MeanAnomaly { get; set; }
    }
    #endregion
}


//Journal Reader Code Chunk.

// else if (EventName == "ScanBaryCentre")
// {
//     var Event = JsonConvert.DeserializeObject<ALICE_Events.ScanBaryCentre>(RawLine);
//     Manager.UpdateEvents(EventName, Event);
//     Manager.ScanBaryCentre.Logic();
// }
