//Code Generated By Project A.L.I.C.E Developer Toolkit
//Class File Generated: 01/18/2026 4:27 PM
//Source Journal Line: { "timestamp":"2026-01-10T14:16:20Z", "event":"WingAdd", "Name":"RIPTHEREAPER" }

using System;
using System.Collections.Generic;

namespace ALICE_Events
{
    public class Event_WingAdd : Event_Base
    {
        public Event_WingAdd()
        {
            Name = "WingAdd";
        }

        public void Logic()
        {
            if (Manager.WriteVariables && WriteVariables)
            {
                try
                {
                    Variables_Clear();
                    Variables_Generate();
                    Variables_Write();
                }
                catch (Exception ex)
                {
                    Internal.Exception(Name, "An Exception Occured While Updating Variables");
                    Internal.Exception(Name, "Exception: " + ex);
                }
            }

            //GameState.Logic_WingAdd((WingAdd)GetEvent());

            TriggerEvent();
        }

        public void Variables_Generate()
        {
            WingAdd Event = (WingAdd)Manager.GetEvent(Name);

            Variables.Clear();

            #region Custom Variables

            #endregion

            #region Event Variables
            Variable_Craft("Name", Event.Name.ToString());
            #endregion
        }
    }

    #region WingAdd Event
    public class WingAdd : Base
    {
        public string Name { get; set; }
    }
    #endregion
}


//Journal Reader Code Chunk.

// else if (EventName == "WingAdd")
// {
//     var Event = JsonConvert.DeserializeObject<ALICE_Events.WingAdd>(RawLine);
//     Manager.UpdateEvents(EventName, Event);
//     Manager.WingAdd.Logic();
// }
