//Code Generated By Project A.L.I.C.E Developer Toolkit
//Class File Generated: 01/18/2026 4:27 PM
//Source Journal Line: { "timestamp":"2026-01-15T20:44:19Z", "event":"MultiSellExplorationData", "Discovered":[ { "SystemName":"HIP 58832", "NumBodies":3 }, { "SystemName":"HIP 57784", "NumBodies":6 }, { "SystemName":"HD 104495", "NumBodies":5 }, { "SystemName":"62 Gamma Ophiuchi", "NumBodies":1 }, { "SystemName":"Luyten 145-141", "NumBodies":1 }, { "SystemName":"LP 528-71", "NumBodies":1 }, { "SystemName":"BD+10 3250", "NumBodies":4 }, { "SystemName":"Rho Ophiuchi Sector IH-U b3-1", "NumBodies":9 }, { "SystemName":"Panchua", "NumBodies":1 }, { "SystemName":"Nerishis", "NumBodies":1 }, { "SystemName":"Puppis Sector EL-Y c20", "NumBodies":2 }, { "SystemName":"Ladabalbasa", "NumBodies":6 }, { "SystemName":"Alrai Sector KC-V c2-23", "NumBodies":1 }, { "SystemName":"LHS 2010", "NumBodies":2 }, { "SystemName":"Ngobed", "NumBodies":4 }, { "SystemName":"Core Sys Sector QT-R b4-5", "NumBodies":2 }, { "SystemName":"Puppis Sector JR-W b1-5", "NumBodies":1 }, { "SystemName":"LFT 507", "NumBodies":2 }, { "SystemName":"Col 285 Sector NG-H a26-1", "NumBodies":1 }, { "SystemName":"Col 285 Sector PM-F a27-2", "NumBodies":13 } ], "BaseValue":277908, "Bonus":0, "TotalEarnings":261252 }

using System;
using System.Collections.Generic;

namespace ALICE_Events
{
    public class Event_MultiSellExplorationData : Event_Base
    {
        public Event_MultiSellExplorationData()
        {
            Name = "MultiSellExplorationData";
        }

        public void Logic()
        {
            if (Manager.WriteVariables && WriteVariables)
            {
                try
                {
                    Variables_Clear();
                    Variables_Generate();
                    Variables_Write();
                }
                catch (Exception ex)
                {
                    Internal.Exception(Name, "An Exception Occured While Updating Variables");
                    Internal.Exception(Name, "Exception: " + ex);
                }
            }

            //GameState.Logic_MultiSellExplorationData((MultiSellExplorationData)GetEvent());

            TriggerEvent();
        }

        public void Variables_Generate()
        {
            MultiSellExplorationData Event = (MultiSellExplorationData)Manager.GetEvent(Name);

            Variables.Clear();

            #region Custom Variables

            #endregion

            #region Event Variables
            Variable_Craft("Discovered", Event.Discovered.ToString());
            Variable_Craft("BaseValue", Event.BaseValue.ToString());
            Variable_Craft("Bonus", Event.Bonus.ToString());
            Variable_Craft("TotalEarnings", Event.TotalEarnings.ToString());
            #endregion
        }
    }

    #region MultiSellExplorationData Event
    public class MultiSellExplorationData : Base
    {
        public string Discovered { get; set; }
        public decimal BaseValue { get; set; }
        public decimal Bonus { get; set; }
        public decimal TotalEarnings { get; set; }
    }
    #endregion
}


//Journal Reader Code Chunk.

// else if (EventName == "MultiSellExplorationData")
// {
//     var Event = JsonConvert.DeserializeObject<ALICE_Events.MultiSellExplorationData>(RawLine);
//     Manager.UpdateEvents(EventName, Event);
//     Manager.MultiSellExplorationData.Logic();
// }
