//Code Generated By Project A.L.I.C.E Developer Toolkit
//Class File Generated: 01/18/2026 4:27 PM
//Source Journal Line: { "timestamp":"2026-01-10T19:56:41Z", "event":"FighterDestroyed", "ID":38 }

using System;

namespace ALICE_Events
{
    public class Event_FighterDestroyed : Event_Base
    {
        public Event_FighterDestroyed()
        {
            Name = "FighterDestroyed";
        }

        public void Logic()
        {
            if (Manager.WriteVariables && WriteVariables)
            {
                    Variables_Clear();
                    Variables_Generate();
                    Variables_Write();
            }

            //GameState.Logic_FighterDestroyed((FighterDestroyed)GetEvent());

            TriggerEvent();
        }

        public void Variables_Generate()
        {
            FighterDestroyed Event = (FighterDestroyed)Manager.GetEvent(Name);

            Variables.Clear();

            #region Custom Variables

            #endregion

            #region Event Variables
            Variable_Craft("ID", Event.ID.ToString());
            #endregion
        }
    }

    #region FighterDestroyed Event
    public class FighterDestroyed : Base
    {
        public decimal ID { get; set; }
    }
    #endregion
}


//Journal Reader Code Chunk.

// else if (EventName == "FighterDestroyed")
// {
//     var Event = JsonConvert.DeserializeObject<ALICE_Events.FighterDestroyed>(RawLine);
//     Manager.UpdateEvents(EventName, Event);
//     Manager.FighterDestroyed.Logic();
// }
