//Code Generated By Project A.L.I.C.E Developer Toolkit
//Class File Generated: 01/18/2026 4:27 PM
//Source Journal Line: { "timestamp":"2026-01-07T15:45:34Z", "event":"CarrierDockingPermission", "CarrierID":3714546688, "CarrierType":"SquadronCarrier", "DockingAccess":"squadron", "AllowNotorious":true }

using System;
using System.Collections.Generic;

namespace ALICE_Events
{
    public class Event_CarrierDockingPermission : Event_Base
    {
        public Event_CarrierDockingPermission()
        {
            Name = "CarrierDockingPermission";
        }

        public void Logic()
        {
            if (Manager.WriteVariables && WriteVariables)
            {
                try
                {
                    Variables_Clear();
                    Variables_Generate();
                    Variables_Write();
                }
                catch (Exception ex)
                {
                    Internal.Exception(Name, "An Exception Occured While Updating Variables");
                    Internal.Exception(Name, "Exception: " + ex);
                }
            }

            //GameState.Logic_CarrierDockingPermission((CarrierDockingPermission)GetEvent());

            TriggerEvent();
        }

        public void Variables_Generate()
        {
            CarrierDockingPermission Event = (CarrierDockingPermission)Manager.GetEvent(Name);

            Variables.Clear();

            #region Custom Variables

            #endregion

            #region Event Variables
            Variable_Craft("CarrierID", Event.CarrierID.ToString());
            Variable_Craft("CarrierType", Event.CarrierType.ToString());
            Variable_Craft("DockingAccess", Event.DockingAccess.ToString());
            Variable_Craft("AllowNotorious", Event.AllowNotorious.ToString());
            #endregion
        }
    }

    #region CarrierDockingPermission Event
    public class CarrierDockingPermission : Base
    {
        public decimal CarrierID { get; set; }
        public string CarrierType { get; set; }
        public string DockingAccess { get; set; }
        public string AllowNotorious { get; set; }
    }
    #endregion
}


//Journal Reader Code Chunk.

// else if (EventName == "CarrierDockingPermission")
// {
//     var Event = JsonConvert.DeserializeObject<ALICE_Events.CarrierDockingPermission>(RawLine);
//     Manager.UpdateEvents(EventName, Event);
//     Manager.CarrierDockingPermission.Logic();
// }
