//Code Generated By Project A.L.I.C.E Developer Toolkit
//Class File Generated: 01/18/2026 4:27 PM
//Source Journal Line: { "timestamp":"2026-01-10T21:28:53Z", "event":"Disembark", "SRV":false, "Taxi":false, "Multicrew":false, "ID":8, "StarSystem":"Kurmodiae", "SystemAddress":5856221500130, "Body":"Covey Terminal", "BodyID":50, "OnStation":true, "OnPlanet":false, "StationName":"Covey Terminal", "StationType":"Coriolis", "MarketID":3230563328 }

using System;
using System.Collections.Generic;

namespace ALICE_Events
{
    public class Event_Disembark : Event_Base
    {
        public Event_Disembark()
        {
            Name = "Disembark";
        }

        public void Logic()
        {
            if (Manager.WriteVariables && WriteVariables)
            {
                try
                {
                    Variables_Clear();
                    Variables_Generate();
                    Variables_Write();
                }
                catch (Exception ex)
                {
                    Internal.Exception(Name, "An Exception Occured While Updating Variables");
                    Internal.Exception(Name, "Exception: " + ex);
                }
            }

            //GameState.Logic_Disembark((Disembark)GetEvent());

            TriggerEvent();
        }

        public void Variables_Generate()
        {
            Disembark Event = (Disembark)Manager.GetEvent(Name);

            Variables.Clear();

            #region Custom Variables

            #endregion

            #region Event Variables
            Variable_Craft("SRV", Event.SRV.ToString());
            Variable_Craft("Taxi", Event.Taxi.ToString());
            Variable_Craft("Multicrew", Event.Multicrew.ToString());
            Variable_Craft("ID", Event.ID.ToString());
            Variable_Craft("StarSystem", Event.StarSystem.ToString());
            Variable_Craft("SystemAddress", Event.SystemAddress.ToString());
            Variable_Craft("Body", Event.Body.ToString());
            Variable_Craft("BodyID", Event.BodyID.ToString());
            Variable_Craft("OnStation", Event.OnStation.ToString());
            Variable_Craft("OnPlanet", Event.OnPlanet.ToString());
            Variable_Craft("StationName", Event.StationName.ToString());
            Variable_Craft("StationType", Event.StationType.ToString());
            Variable_Craft("MarketID", Event.MarketID.ToString());
            #endregion
        }
    }

    #region Disembark Event
    public class Disembark : Base
    {
        public string SRV { get; set; }
        public string Taxi { get; set; }
        public string Multicrew { get; set; }
        public decimal ID { get; set; }
        public string StarSystem { get; set; }
        public decimal SystemAddress { get; set; }
        public string Body { get; set; }
        public decimal BodyID { get; set; }
        public string OnStation { get; set; }
        public string OnPlanet { get; set; }
        public string StationName { get; set; }
        public string StationType { get; set; }
        public decimal MarketID { get; set; }
    }
    #endregion
}


//Journal Reader Code Chunk.

// else if (EventName == "Disembark")
// {
//     var Event = JsonConvert.DeserializeObject<ALICE_Events.Disembark>(RawLine);
//     Manager.UpdateEvents(EventName, Event);
//     Manager.Disembark.Logic();
// }
