//Code Generated By Project A.L.I.C.E Developer Toolkit
//Class File Generated: 01/18/2026 4:27 PM
//Source Journal Line: { "timestamp":"2025-11-12T11:25:03Z", "event":"Interdicted", "Submitted":true, "Interdictor":"Clayton Slagle", "IsPlayer":false, "Faction":"Tangua Society" }

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using ALICE_Ships_Datalink_Interface;
using ALICE_Command_Interface;
using ALICE_Internal;

namespace ALICE_Events
{
    public class Event_Interdicted : Event_Base
    {
        public Event_Interdicted()
        {
            Name = "Interdicted";
        }

        public void Logic()
        {
            if (Manager.WriteVariables && WriteVariables)
            {
                try
                {
                    Variables_Clear();
                    Variables_Generate();
                    Variables_Write();
                }
            }

            //GameState.Logic_Interdicted((Interdicted)GetEvent());

            TriggerEvent();
        }

        public void Variables_Generate()
        {
            Interdicted Event = (Interdicted)Manager.GetEvent(Name);

            Variables.Clear();

            #region Custom Variables

            #endregion

            #region Event Variables
            Variable_Craft("Submitted", Event.Submitted.ToString());
            Variable_Craft("Interdictor", Event.Interdictor.ToString());
            Variable_Craft("IsPlayer", Event.IsPlayer.ToString());
            Variable_Craft("Faction", Event.Faction.ToString());
            #endregion
        }
    }

    #region Interdicted Event
    public class Interdicted : Base
    {
        public string Submitted { get; set; }
        public string Interdictor { get; set; }
        public string IsPlayer { get; set; }
        public string Faction { get; set; }
    }
    #endregion
}


//Journal Reader Code Chunk.

// else if (EventName == "Interdicted")
// {
//     var Event = JsonConvert.DeserializeObject<ALICE_Events.Interdicted>(RawLine);
//     Manager.UpdateEvents(EventName, Event);
//     Manager.Interdicted.Logic();
// }
