//Code Generated By Project A.L.I.C.E Developer Toolkit
//Class File Generated: 01/18/2026 4:27 PM
//Source Journal Line: { "timestamp":"2025-11-12T11:53:27Z", "event":"Missions", "Active":[ { "MissionID":1035688088, "Name":"Mission_Mining_name", "PassengerMission":false, "Expires":597317 } ], "Failed":[  ], "Complete":[  ] }

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using ALICE_Ships_Datalink_Interface;
using ALICE_Command_Interface;
using ALICE_Internal;

namespace ALICE_Events
{
    public class Event_Missions : Event_Base
    {
        public Event_Missions()
        {
            Name = "Missions";
        }

        public void Logic()
        {
            if (Manager.WriteVariables && WriteVariables)
            {
                try
                {
                    Variables_Clear();
                    Variables_Generate();
                    Variables_Write();
                }
                catch (Exception ex)
                {
                    Internal.Exception(Name, "An Exception Occured While Updating Variables");
                    Internal.Exception(Name, "Exception: " + ex);
                }
            }

            //GameState.Logic_Missions((Missions)GetEvent());

            TriggerEvent();
        }

        public void Variables_Generate()
        {
            Missions Event = (Missions)Manager.GetEvent(Name);

            Variables.Clear();

            #region Custom Variables

            #endregion

            #region Event Variables
            Variable_Craft("Active", Event.Active.ToString());
            Variable_Craft("Failed", Event.Failed.ToString());
            Variable_Craft("Complete", Event.Complete.ToString());
            #endregion
        }
    }

    #region Missions Event
    public class Missions : Base
    {
        public string Active { get; set; }
        public string Failed { get; set; }
        public string Complete { get; set; }
    }
    #endregion
}


//Journal Reader Code Chunk.

// else if (EventName == "Missions")
// {
//     var Event = JsonConvert.DeserializeObject<ALICE_Events.Missions>(RawLine);
//     Manager.UpdateEvents(EventName, Event);
//     Manager.Missions.Logic();
// }
