//Code Generated By Project A.L.I.C.E Developer Toolkit
//Class File Generated: 01/18/2026 4:27 PM
//Source Journal Line: { "timestamp":"2026-01-07T16:56:45Z", "event":"ModuleStore", "MarketID":3714546688, "Slot":"PowerDistributor", "StoredItem":"$int_powerdistributor_size7_class5_name;", "StoredItem_Localised":"Power Distributor", "Ship":"krait_mkii", "ShipID":7, "Hot":false, "EngineerModifications":"PowerDistributor_HighCapacity", "Level":2, "Quality":0.968000 }

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using ALICE_Ships_Datalink_Interface;
using ALICE_Command_Interface;
using ALICE_Internal;

namespace ALICE_Events
{
    public class Event_ModuleStore : Event_Base
    {
        public Event_ModuleStore()
        {
            Name = "ModuleStore";
        }

        public void Logic()
        {
            if (Manager.WriteVariables && WriteVariables)
            {
                try
                {
                    Variables_Clear();
                    Variables_Generate();
                    Variables_Write();
                }
                catch (Exception ex)
                {
                    Internal.Exception(Name, "An Exception Occured While Updating Variables");
                    Internal.Exception(Name, "Exception: " + ex);
                }
            }

            //GameState.Logic_ModuleStore((ModuleStore)GetEvent());

            TriggerEvent();
        }

        public void Variables_Generate()
        {
            ModuleStore Event = (ModuleStore)Manager.GetEvent(Name);

            Variables.Clear();

            #region Custom Variables

            #endregion

            #region Event Variables
            Variable_Craft("MarketID", Event.MarketID.ToString());
            Variable_Craft("Slot", Event.Slot.ToString());
            Variable_Craft("StoredItem", Event.StoredItem.ToString());
            Variable_Craft("StoredItem_Localised", Event.StoredItem_Localised.ToString());
            Variable_Craft("Ship", Event.Ship.ToString());
            Variable_Craft("ShipID", Event.ShipID.ToString());
            Variable_Craft("Hot", Event.Hot.ToString());
            Variable_Craft("EngineerModifications", Event.EngineerModifications.ToString());
            Variable_Craft("Level", Event.Level.ToString());
            Variable_Craft("Quality", Event.Quality.ToString());
            #endregion
        }
    }

    #region ModuleStore Event
    public class ModuleStore : Base
    {
        public decimal MarketID { get; set; }
        public string Slot { get; set; }
        public string StoredItem { get; set; }
        public string StoredItem_Localised { get; set; }
        public string Ship { get; set; }
        public decimal ShipID { get; set; }
        public string Hot { get; set; }
        public string EngineerModifications { get; set; }
        public decimal Level { get; set; }
        public decimal Quality { get; set; }
    }
    #endregion
}


//Journal Reader Code Chunk.

// else if (EventName == "ModuleStore")
// {
//     var Event = JsonConvert.DeserializeObject<ALICE_Events.ModuleStore>(RawLine);
//     Manager.UpdateEvents(EventName, Event);
//     Manager.ModuleStore.Logic();
// }
