//Code Generated By Project A.L.I.C.E Developer Toolkit
//Class File Generated: 01/18/2026 4:27 PM
//Source Journal Line: { "timestamp":"2026-01-10T21:19:57Z", "event":"Embark", "SRV":false, "Taxi":false, "Multicrew":false, "ID":8, "Crew":[ { "Name":"RIPTHEREAPER", "Role":"Idle" }, { "Name":"TOMOE'", "Role":"Idle" } ], "StarSystem":"Gali", "SystemAddress":6680855220970, "Body":"Chadwick Dock", "BodyID":39, "OnStation":true, "OnPlanet":false, "StationName":"Chadwick Dock", "StationType":"Coriolis", "MarketID":3230817536 }

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using ALICE_Ships_Datalink_Interface;
using ALICE_Command_Interface;
using ALICE_Internal;

namespace ALICE_Events
{
    public class Event_Embark : Event_Base
    {
        public Event_Embark()
        {
            Name = "Embark";
        }

        public void Logic()
        {
            if (Manager.WriteVariables && WriteVariables)
            {
                try
                {
                    Variables_Clear();
                    Variables_Generate();
                    Variables_Write();
                }
                catch (Exception ex)
                {
                    Internal.Exception(Name, "An Exception Occured While Updating Variables");
                    Internal.Exception(Name, "Exception: " + ex);
                }
            }

            //GameState.Logic_Embark((Embark)GetEvent());

            TriggerEvent();
        }

        public void Variables_Generate()
        {
            Embark Event = (Embark)Manager.GetEvent(Name);

            Variables.Clear();

            #region Custom Variables

            #endregion

            #region Event Variables
            Variable_Craft("SRV", Event.SRV.ToString());
            Variable_Craft("Taxi", Event.Taxi.ToString());
            Variable_Craft("Multicrew", Event.Multicrew.ToString());
            Variable_Craft("ID", Event.ID.ToString());
            Variable_Craft("Crew", Event.Crew.ToString());
            Variable_Craft("StarSystem", Event.StarSystem.ToString());
            Variable_Craft("SystemAddress", Event.SystemAddress.ToString());
            Variable_Craft("Body", Event.Body.ToString());
            Variable_Craft("BodyID", Event.BodyID.ToString());
            Variable_Craft("OnStation", Event.OnStation.ToString());
            Variable_Craft("OnPlanet", Event.OnPlanet.ToString());
            Variable_Craft("StationName", Event.StationName.ToString());
            Variable_Craft("StationType", Event.StationType.ToString());
            Variable_Craft("MarketID", Event.MarketID.ToString());
            #endregion
        }
    }

    #region Embark Event
    public class Embark : Base
    {
        public string SRV { get; set; }
        public string Taxi { get; set; }
        public string Multicrew { get; set; }
        public decimal ID { get; set; }
        public string Crew { get; set; }
        public string StarSystem { get; set; }
        public decimal SystemAddress { get; set; }
        public string Body { get; set; }
        public decimal BodyID { get; set; }
        public string OnStation { get; set; }
        public string OnPlanet { get; set; }
        public string StationName { get; set; }
        public string StationType { get; set; }
        public decimal MarketID { get; set; }
    }
    #endregion
}


//Journal Reader Code Chunk.

// else if (EventName == "Embark")
// {
//     var Event = JsonConvert.DeserializeObject<ALICE_Events.Embark>(RawLine);
//     Manager.UpdateEvents(EventName, Event);
//     Manager.Embark.Logic();
// }
