//Code Generated By Project A.L.I.C.E Developer Toolkit
//Class File Generated: 01/18/2026 4:27 PM
//Source Journal Line: { "timestamp":"2026-01-11T01:00:14Z", "event":"FSSDiscoveryScan", "Progress":0.172767, "BodyCount":11, "NonBodyCount":15, "SystemName":"Col 285 Sector PM-F a27-2", "SystemAddress":40565429127968 }

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using ALICE_Ships_Datalink_Interface;
using ALICE_Command_Interface;
using ALICE_Internal;

namespace ALICE_Events
{
    public class Event_FSSDiscoveryScan : Event_Base
    {
        public Event_FSSDiscoveryScan()
        {
            Name = "FSSDiscoveryScan";
        }

        public void Logic()
        {
            if (Manager.WriteVariables && WriteVariables)
            {
                try
                {
                    Variables_Clear();
                    Variables_Generate();
                    Variables_Write();
                }
                catch (Exception ex)
                {
                    Internal.Exception(Name, "An Exception Occured While Updating Variables");
                    Internal.Exception(Name, "Exception: " + ex);
                }
            }

            //GameState.Logic_FSSDiscoveryScan((FSSDiscoveryScan)GetEvent());

            TriggerEvent();
        }

        public void Variables_Generate()
        {
            FSSDiscoveryScan Event = (FSSDiscoveryScan)Manager.GetEvent(Name);

            Variables.Clear();

            #region Custom Variables

            #endregion

            #region Event Variables
            Variable_Craft("Progress", Event.Progress.ToString());
            Variable_Craft("BodyCount", Event.BodyCount.ToString());
            Variable_Craft("NonBodyCount", Event.NonBodyCount.ToString());
            Variable_Craft("SystemName", Event.SystemName.ToString());
            Variable_Craft("SystemAddress", Event.SystemAddress.ToString());
            #endregion
        }
    }

    #region FSSDiscoveryScan Event
    public class FSSDiscoveryScan : Base
    {
        public decimal Progress { get; set; }
        public decimal BodyCount { get; set; }
        public decimal NonBodyCount { get; set; }
        public string SystemName { get; set; }
        public decimal SystemAddress { get; set; }
    }
    #endregion
}


//Journal Reader Code Chunk.

// else if (EventName == "FSSDiscoveryScan")
// {
//     var Event = JsonConvert.DeserializeObject<ALICE_Events.FSSDiscoveryScan>(RawLine);
//     Manager.UpdateEvents(EventName, Event);
//     Manager.FSSDiscoveryScan.Logic();
// }
