//Code Generated By Project A.L.I.C.E Developer Toolkit
//Class File Generated: 01/18/2026 4:27 PM
//Source Journal Line: { "timestamp":"2026-01-16T00:18:24Z", "event":"CommunityGoalJoin", "CGID":840, "Name":"Distant Worlds III Deep-Space Infrastructure Project", "System":"Alrai" }

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using ALICE_Ships_Datalink_Interface;
using ALICE_Command_Interface;
using ALICE_Internal;

namespace ALICE_Events
{
    public class Event_CommunityGoalJoin : Event_Base
    {
        public Event_CommunityGoalJoin()
        {
            Name = "CommunityGoalJoin";
        }

        public void Logic()
        {
            if (Manager.WriteVariables && WriteVariables)
            {
                try
                {
                    Variables_Clear();
                    Variables_Generate();
                    Variables_Write();
                }
            }

            //GameState.Logic_CommunityGoalJoin((CommunityGoalJoin)GetEvent());

            TriggerEvent();
        }

        public void Variables_Generate()
        {
            CommunityGoalJoin Event = (CommunityGoalJoin)Manager.GetEvent(Name);

            Variables.Clear();

            #region Custom Variables

            #endregion

            #region Event Variables
            Variable_Craft("CGID", Event.CGID.ToString());
            Variable_Craft("Name", Event.Name.ToString());
            Variable_Craft("System", Event.System.ToString());
            #endregion
        }
    }

    #region CommunityGoalJoin Event
    public class CommunityGoalJoin : Base
    {
        public decimal CGID { get; set; }
        public string Name { get; set; }
        public string System { get; set; }
    }
    #endregion
}


//Journal Reader Code Chunk.

// else if (EventName == "CommunityGoalJoin")
// {
//     var Event = JsonConvert.DeserializeObject<ALICE_Events.CommunityGoalJoin>(RawLine);
//     Manager.UpdateEvents(EventName, Event);
//     Manager.CommunityGoalJoin.Logic();
// }
