//Code Generated By Project A.L.I.C.E Developer Toolkit
//Class File Generated: 01/18/2026 4:27 PM
//Source Journal Line: { "timestamp":"2026-01-10T14:24:45Z", "event":"RestockVehicle", "Type":"independent_fighter", "Type_Localised":"Taipan", "Loadout":"zero", "ID":38, "Cost":15270, "Count":1 }

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using ALICE_Ships_Datalink_Interface;
using ALICE_Command_Interface;
using ALICE_Internal;

namespace ALICE_Events
{
    public class Event_RestockVehicle : Event_Base
    {
        public Event_RestockVehicle()
        {
            Name = "RestockVehicle";
        }

        public void Logic()
        {
            if (Manager.WriteVariables && WriteVariables)
            {
                try
                {
                    Variables_Clear();
                    Variables_Generate();
                    Variables_Write();
                }
                catch (Exception ex)
                {
                    Internal.Exception(Name, "An Exception Occured While Updating Variables");
                    Internal.Exception(Name, "Exception: " + ex);
                }
            }

            //GameState.Logic_RestockVehicle((RestockVehicle)GetEvent());

            TriggerEvent();
        }

        public void Variables_Generate()
        {
            RestockVehicle Event = (RestockVehicle)Manager.GetEvent(Name);

            Variables.Clear();

            #region Custom Variables

            #endregion

            #region Event Variables
            Variable_Craft("Type", Event.Type.ToString());
            Variable_Craft("Type_Localised", Event.Type_Localised.ToString());
            Variable_Craft("Loadout", Event.Loadout.ToString());
            Variable_Craft("ID", Event.ID.ToString());
            Variable_Craft("Cost", Event.Cost.ToString());
            Variable_Craft("Count", Event.Count.ToString());
            #endregion
        }
    }

    #region RestockVehicle Event
    public class RestockVehicle : Base
    {
        public string Type { get; set; }
        public string Type_Localised { get; set; }
        public string Loadout { get; set; }
        public decimal ID { get; set; }
        public decimal Cost { get; set; }
        public decimal Count { get; set; }
    }
    #endregion
}


//Journal Reader Code Chunk.

// else if (EventName == "RestockVehicle")
// {
//     var Event = JsonConvert.DeserializeObject<ALICE_Events.RestockVehicle>(RawLine);
//     Manager.UpdateEvents(EventName, Event);
//     Manager.RestockVehicle.Logic();
// }
