//Code Generated By Project A.L.I.C.E Developer Toolkit
//Class File Generated: 01/18/2026 4:27 PM
//Source Journal Line: { "timestamp":"2025-11-12T09:17:29Z", "event":"SquadronStartup", "SquadronID":84124, "SquadronName":"FOXBOX", "CurrentRank":0, "CurrentRankName":"$Squadron_DefaultRankName_Rank0;", "CurrentRankName_Localised":"Leader" }

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using ALICE_Ships_Datalink_Interface;
using ALICE_Command_Interface;
using ALICE_Internal;

namespace ALICE_Events
{
    public class Event_SquadronStartup : Event_Base
    {
        public Event_SquadronStartup()
        {
            Name = "SquadronStartup";
        }

        public void Logic()
        {
            if (Manager.WriteVariables && WriteVariables)
            {
                try
                {
                    Variables_Clear();
                    Variables_Generate();
                    Variables_Write();
                }
                catch (Exception ex)
                {
                    Internal.Exception(Name, "An Exception Occured While Updating Variables");
                    Internal.Exception(Name, "Exception: " + ex);
                }
            }

            //GameState.Logic_SquadronStartup((SquadronStartup)GetEvent());

            TriggerEvent();
        }

        public void Variables_Generate()
        {
            SquadronStartup Event = (SquadronStartup)Manager.GetEvent(Name);

            Variables.Clear();

            #region Custom Variables

            #endregion

            #region Event Variables
            Variable_Craft("SquadronID", Event.SquadronID.ToString());
            Variable_Craft("SquadronName", Event.SquadronName.ToString());
            Variable_Craft("CurrentRank", Event.CurrentRank.ToString());
            Variable_Craft("CurrentRankName", Event.CurrentRankName.ToString());
            Variable_Craft("CurrentRankName_Localised", Event.CurrentRankName_Localised.ToString());
            #endregion
        }
    }

    #region SquadronStartup Event
    public class SquadronStartup : Base
    {
        public decimal SquadronID { get; set; }
        public string SquadronName { get; set; }
        public decimal CurrentRank { get; set; }
        public string CurrentRankName { get; set; }
        public string CurrentRankName_Localised { get; set; }
    }
    #endregion
}


//Journal Reader Code Chunk.

// else if (EventName == "SquadronStartup")
// {
//     var Event = JsonConvert.DeserializeObject<ALICE_Events.SquadronStartup>(RawLine);
//     Manager.UpdateEvents(EventName, Event);
//     Manager.SquadronStartup.Logic();
// }
