//Code Generated By Project A.L.I.C.E Developer Toolkit
//Class File Generated: 01/18/2026 4:27 PM
//Source Journal Line: { "timestamp":"2026-01-09T10:47:16Z", "event":"LoadGame", "FID":"F2812796", "Commander":"Snowythefox", "Horizons":true, "Odyssey":true, "Ship":"TacticalSuit_Class2", "Ship_Localised":"$TacticalSuit_Class1_Name;", "ShipID":4293000002, "ShipName":"", "ShipIdent":"", "FuelLevel":1.000000, "FuelCapacity":1.000000, "GameMode":"Group", "Group":"pilots trade network", "Credits":845383025, "Loan":0, "language":"English/UK", "gameversion":"4.3.0.1", "build":"r322188/r0 " }

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using ALICE_Ships_Datalink_Interface;
using ALICE_Command_Interface;
using ALICE_Internal;

namespace ALICE_Events
{
    public class Event_LoadGame : Event_Base
    {
        public Event_LoadGame()
        {
            Name = "LoadGame";
        }

        public void Logic()
        {
            if (Manager.WriteVariables && WriteVariables)
            {
                try
                {
                    Variables_Clear();
                    Variables_Generate();
                    Variables_Write();
                }
            }

            //GameState.Logic_LoadGame((LoadGame)GetEvent());

            TriggerEvent();
        }

        public void Variables_Generate()
        {
            LoadGame Event = (LoadGame)Manager.GetEvent(Name);

            Variables.Clear();

            #region Custom Variables

            #endregion

            #region Event Variables
            Variable_Craft("FID", Event.FID.ToString());
            Variable_Craft("Commander", Event.Commander.ToString());
            Variable_Craft("Horizons", Event.Horizons.ToString());
            Variable_Craft("Odyssey", Event.Odyssey.ToString());
            Variable_Craft("Ship", Event.Ship.ToString());
            Variable_Craft("Ship_Localised", Event.Ship_Localised.ToString());
            Variable_Craft("ShipID", Event.ShipID.ToString());
            Variable_Craft("ShipName", Event.ShipName.ToString());
            Variable_Craft("ShipIdent", Event.ShipIdent.ToString());
            Variable_Craft("FuelLevel", Event.FuelLevel.ToString());
            Variable_Craft("FuelCapacity", Event.FuelCapacity.ToString());
            Variable_Craft("GameMode", Event.GameMode.ToString());
            Variable_Craft("Group", Event.Group.ToString());
            Variable_Craft("Credits", Event.Credits.ToString());
            Variable_Craft("Loan", Event.Loan.ToString());
            Variable_Craft("Language", Event.Language.ToString());
            Variable_Craft("Gameversion", Event.Gameversion.ToString());
            Variable_Craft("Build", Event.Build.ToString());
            #endregion
        }
    }

    #region LoadGame Event
    public class LoadGame : Base
    {
        public string FID { get; set; }
        public string Commander { get; set; }
        public string Horizons { get; set; }
        public string Odyssey { get; set; }
        public string Ship { get; set; }
        public string Ship_Localised { get; set; }
        public decimal ShipID { get; set; }
        public string ShipName { get; set; }
        public string ShipIdent { get; set; }
        public decimal FuelLevel { get; set; }
        public decimal FuelCapacity { get; set; }
        public string GameMode { get; set; }
        public string Group { get; set; }
        public decimal Credits { get; set; }
        public decimal Loan { get; set; }
        public string Language { get; set; }
        public string Gameversion { get; set; }
        public string Build { get; set; }
    }
    #endregion
}


//Journal Reader Code Chunk.

// else if (EventName == "LoadGame")
// {
//     var Event = JsonConvert.DeserializeObject<ALICE_Events.LoadGame>(RawLine);
//     Manager.UpdateEvents(EventName, Event);
//     Manager.LoadGame.Logic();
// }
