//Code Generated By Project A.L.I.C.E Developer Toolkit
//Class File Generated: 01/18/2026 4:27 PM
//Source Journal Line: { "timestamp":"2026-01-17T20:03:00Z", "event":"EngineerCraft", "Slot":"FrameShiftDrive", "Module":"int_hyperdrive_overcharge_size6_class5", "Ingredients":[ { "Name":"phosphorus", "Count":1 }, { "Name":"chemicalprocessors", "Name_Localised":"Chemical Processors", "Count":1 }, { "Name":"wakesolutions", "Name_Localised":"Strange Wake Solutions", "Count":1 } ], "Engineer":"Felicity Farseer", "EngineerID":300100, "BlueprintID":128673692, "BlueprintName":"FSD_LongRange", "Level":3, "Quality":0.333000, "Modifiers":[ { "Label":"Mass", "Value":48.000000, "OriginalValue":40.000000, "LessIsGood":1 }, { "Label":"Integrity", "Value":128.309998, "OriginalValue":141.000000, "LessIsGood":0 }, { "Label":"PowerDraw", "Value":0.817500, "OriginalValue":0.750000, "LessIsGood":1 }, { "Label":"FSDOptimalMass", "Value":2566.600098, "OriginalValue":2000.000000, "LessIsGood":0 } ] }

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using ALICE_Ships_Datalink_Interface;
using ALICE_Command_Interface;
using ALICE_Internal;

namespace ALICE_Events
{
    public class Event_EngineerCraft : Event_Base
    {
        public Event_EngineerCraft()
        {
            Name = "EngineerCraft";
        }

        public void Logic()
        {
            if (Manager.WriteVariables && WriteVariables)
            {
                try
                {
                    Variables_Clear();
                    Variables_Generate();
                    Variables_Write();
                }
                catch (Exception ex)
                {
                    Internal.Exception(Name, "An Exception Occured While Updating Variables");
                    Internal.Exception(Name, "Exception: " + ex);
                }
            }

            //GameState.Logic_EngineerCraft((EngineerCraft)GetEvent());

            TriggerEvent();
        }

        public void Variables_Generate()
        {
            EngineerCraft Event = (EngineerCraft)Manager.GetEvent(Name);

            Variables.Clear();

            #region Custom Variables

            #endregion

            #region Event Variables
            Variable_Craft("Slot", Event.Slot.ToString());
            Variable_Craft("Module", Event.Module.ToString());
            Variable_Craft("Ingredients", Event.Ingredients.ToString());
            Variable_Craft("Engineer", Event.Engineer.ToString());
            Variable_Craft("EngineerID", Event.EngineerID.ToString());
            Variable_Craft("BlueprintID", Event.BlueprintID.ToString());
            Variable_Craft("BlueprintName", Event.BlueprintName.ToString());
            Variable_Craft("Level", Event.Level.ToString());
            Variable_Craft("Quality", Event.Quality.ToString());
            Variable_Craft("Modifiers", Event.Modifiers.ToString());
            #endregion
        }
    }

    #region EngineerCraft Event
    public class EngineerCraft : Base
    {
        public string Slot { get; set; }
        public string Module { get; set; }
        public string Ingredients { get; set; }
        public string Engineer { get; set; }
        public decimal EngineerID { get; set; }
        public decimal BlueprintID { get; set; }
        public string BlueprintName { get; set; }
        public decimal Level { get; set; }
        public decimal Quality { get; set; }
        public string Modifiers { get; set; }
    }
    #endregion
}


//Journal Reader Code Chunk.

// else if (EventName == "EngineerCraft")
// {
//     var Event = JsonConvert.DeserializeObject<ALICE_Events.EngineerCraft>(RawLine);
//     Manager.UpdateEvents(EventName, Event);
//     Manager.EngineerCraft.Logic();
// }
