//Code Generated By Project A.L.I.C.E Developer Toolkit
//Class File Generated: 01/18/2026 4:27 PM
//Source Journal Line: { "timestamp":"2026-01-17T01:35:02Z", "event":"ReceiveText", "From":"$ShipName_PowersSecurity;", "From_Localised":"Power Security Force", "Message":"$PowersSecurity_PassedStopAndSearchNoPower04:#myPowerName=Aisling Duval;", "Message_Localised":"Scan finished. While you're here... Ever thought about pledging to a Power? Aisling Duval is recruiting.", "Channel":"npc" }

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using ALICE_Ships_Datalink_Interface;
using ALICE_Command_Interface;
using ALICE_Internal;

namespace ALICE_Events
{
    public class Event_ReceiveText : Event_Base
    {
        public Event_ReceiveText()
        {
            Name = "ReceiveText";
        }

        public void Logic()
        {
            if (Manager.WriteVariables && WriteVariables)
            {
                try
                {
                    Variables_Clear();
                    Variables_Generate();
                    Variables_Write();
                }
                catch (Exception ex)
                {
                    Internal.Exception(Name, "An Exception Occured While Updating Variables");
                    Internal.Exception(Name, "Exception: " + ex);
                }
            }

            //GameState.Logic_ReceiveText((ReceiveText)GetEvent());

            TriggerEvent();
        }

        public void Variables_Generate()
        {
            ReceiveText Event = (ReceiveText)Manager.GetEvent(Name);

            Variables.Clear();

            #region Custom Variables

            #endregion

            #region Event Variables
            Variable_Craft("From", Event.From.ToString());
            Variable_Craft("From_Localised", Event.From_Localised.ToString());
            Variable_Craft("Message", Event.Message.ToString());
            Variable_Craft("Message_Localised", Event.Message_Localised.ToString());
            Variable_Craft("Channel", Event.Channel.ToString());
            #endregion
        }
    }

    #region ReceiveText Event
    public class ReceiveText : Base
    {
        public string From { get; set; }
        public string From_Localised { get; set; }
        public string Message { get; set; }
        public string Message_Localised { get; set; }
        public string Channel { get; set; }
    }
    #endregion
}


//Journal Reader Code Chunk.

// else if (EventName == "ReceiveText")
// {
//     var Event = JsonConvert.DeserializeObject<ALICE_Events.ReceiveText>(RawLine);
//     Manager.UpdateEvents(EventName, Event);
//     Manager.ReceiveText.Logic();
// }
