//Code Generated By Project A.L.I.C.E Developer Toolkit
//Class File Generated: 01/18/2026 4:27 PM
//Source Journal Line: { "timestamp":"2025-11-12T09:48:35Z", "event":"FuelScoop", "Scooped":2.206059, "Total":23.531073 }

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using ALICE_Ships_Datalink_Interface;
using ALICE_Command_Interface;
using ALICE_Internal;

namespace ALICE_Events
{
    public class Event_FuelScoop : Event_Base
    {
        public Event_FuelScoop()
        {
            Name = "FuelScoop";
        }

        public void Logic()
        {
            if (Manager.WriteVariables && WriteVariables)
            {
                try
                {
                    Variables_Clear();
                    Variables_Generate();
                    Variables_Write();
                }
                catch (Exception ex)
                {
                    Internal.Exception(Name, "An Exception Occured While Updating Variables");
                    Internal.Exception(Name, "Exception: " + ex);
                }
            }

            //GameState.Logic_FuelScoop((FuelScoop)GetEvent());

            TriggerEvent();
        }

        public void Variables_Generate()
        {
            FuelScoop Event = (FuelScoop)Manager.GetEvent(Name);

            Variables.Clear();

            #region Custom Variables

            #endregion

            #region Event Variables
            Variable_Craft("Scooped", Event.Scooped.ToString());
            Variable_Craft("Total", Event.Total.ToString());
            #endregion
        }
    }

    #region FuelScoop Event
    public class FuelScoop : Base
    {
        public decimal Scooped { get; set; }
        public decimal Total { get; set; }
    }
    #endregion
}


//Journal Reader Code Chunk.

// else if (EventName == "FuelScoop")
// {
//     var Event = JsonConvert.DeserializeObject<ALICE_Events.FuelScoop>(RawLine);
//     Manager.UpdateEvents(EventName, Event);
//     Manager.FuelScoop.Logic();
// }
