//Code Generated By Project A.L.I.C.E Developer Toolkit
//Class File Generated: 01/19/2026 11:54 AM
//Source Journal Line: { "timestamp":"2025-11-12T09:29:38Z", "event":"NavRoute" }

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using ALICE_Ships_Datalink_Interface;
using ALICE_Command_Interface;
using ALICE_Internal;

namespace ALICE_Events
{
    public class Event_NavRoute : Event_Base
    {
        public Event_NavRoute()
        {
            Name = "NavRoute";
        }

        public void Logic()
        {
            if (Manager.WriteVariables && WriteVariables)
            {
                try
                {
                    Variables_Clear();
                    Variables_Generate();
                    Variables_Write();
                }
                catch (Exception ex)
                {
                    Internal.Exception(Name, "An Exception Occured While Updating Variables");
                    Internal.Exception(Name, "Exception: " + ex);
                }
            }

            //GameState.Logic_NavRoute((NavRoute)GetEvent());

            TriggerEvent();
        }

        public void Variables_Generate()
        {
            NavRoute Event = (NavRoute)Manager.GetEvent(Name);

            Variables.Clear();

            #region Custom Variables

            #endregion

            #region Event Variables
            #endregion
        }
    }

    #region NavRoute Event
    public class NavRoute : Base
    {
    }
    #endregion
}


//Journal Reader Code Chunk.

// else if (EventName == "NavRoute")
// {
//     var Event = JsonConvert.DeserializeObject<ALICE_Events.NavRoute>(RawLine);
//     Manager.UpdateEvents(EventName, Event);
//     Manager.NavRoute.Logic();
// }
