//Code Generated By Project A.L.I.C.E Developer Toolkit
//Class File Generated: 01/18/2026 4:27 PM
//Source Journal Line: { "timestamp":"2026-01-11T00:09:51Z", "event":"FSDTarget", "Name":"Core Sys Sector QT-R b4-5", "SystemAddress":11665802339769, "StarClass":"M", "RemainingJumpsInRoute":4 }

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using ALICE_Ships_Datalink_Interface;
using ALICE_Command_Interface;
using ALICE_Internal;

namespace ALICE_Events
{
    public class Event_FSDTarget : Event_Base
    {
        public Event_FSDTarget()
        {
            Name = "FSDTarget";
        }

        public void Logic()
        {
            if (Manager.WriteVariables && WriteVariables)
            {
                try
                {
                    Variables_Clear();
                    Variables_Generate();
                    Variables_Write();
                }
                catch (Exception ex)
                {
                    Internal.Exception(Name, "An Exception Occured While Updating Variables");
                    Internal.Exception(Name, "Exception: " + ex);
                }
            }

            //GameState.Logic_FSDTarget((FSDTarget)GetEvent());

            TriggerEvent();
        }

        public void Variables_Generate()
        {
            FSDTarget Event = (FSDTarget)Manager.GetEvent(Name);

            Variables.Clear();

            #region Custom Variables

            #endregion

            #region Event Variables
            Variable_Craft("Name", Event.Name.ToString());
            Variable_Craft("SystemAddress", Event.SystemAddress.ToString());
            Variable_Craft("StarClass", Event.StarClass.ToString());
            Variable_Craft("RemainingJumpsInRoute", Event.RemainingJumpsInRoute.ToString());
            #endregion
        }
    }

    #region FSDTarget Event
    public class FSDTarget : Base
    {
        public string Name { get; set; }
        public decimal SystemAddress { get; set; }
        public string StarClass { get; set; }
        public decimal RemainingJumpsInRoute { get; set; }
    }
    #endregion
}


//Journal Reader Code Chunk.

// else if (EventName == "FSDTarget")
// {
//     var Event = JsonConvert.DeserializeObject<ALICE_Events.FSDTarget>(RawLine);
//     Manager.UpdateEvents(EventName, Event);
//     Manager.FSDTarget.Logic();
// }
