//Code Generated By Project A.L.I.C.E Developer Toolkit
//Class File Generated: 01/18/2026 4:27 PM
//Source Journal Line: { "timestamp":"2026-01-10T10:51:29Z", "event":"Touchdown", "PlayerControlled":true, "Taxi":false, "Multicrew":false, "StarSystem":"Gali", "SystemAddress":6680855220970, "Body":"Gali B 1", "BodyID":22, "OnStation":false, "OnPlanet":true, "Latitude":-28.222754, "Longitude":22.812067, "NearestDestination":"Bassett Hydroponics Base" }

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using ALICE_Ships_Datalink_Interface;
using ALICE_Command_Interface;
using ALICE_Internal;

namespace ALICE_Events
{
    public class Event_Touchdown : Event_Base
    {
        public Event_Touchdown()
        {
            Name = "Touchdown";
        }

        public void Logic()
        {
            if (Manager.WriteVariables && WriteVariables)
            {
                try
                {
                    Variables_Clear();
                    Variables_Generate();
                    Variables_Write();
                }
                catch (Exception ex)
                {
                    Internal.Exception(Name, "An Exception Occured While Updating Variables");
                    Internal.Exception(Name, "Exception: " + ex);
                }
            }

            //GameState.Logic_Touchdown((Touchdown)GetEvent());

            TriggerEvent();
        }

        public void Variables_Generate()
        {
            Touchdown Event = (Touchdown)Manager.GetEvent(Name);

            Variables.Clear();

            #region Custom Variables

            #endregion

            #region Event Variables
            Variable_Craft("PlayerControlled", Event.PlayerControlled.ToString());
            Variable_Craft("Taxi", Event.Taxi.ToString());
            Variable_Craft("Multicrew", Event.Multicrew.ToString());
            Variable_Craft("StarSystem", Event.StarSystem.ToString());
            Variable_Craft("SystemAddress", Event.SystemAddress.ToString());
            Variable_Craft("Body", Event.Body.ToString());
            Variable_Craft("BodyID", Event.BodyID.ToString());
            Variable_Craft("OnStation", Event.OnStation.ToString());
            Variable_Craft("OnPlanet", Event.OnPlanet.ToString());
            Variable_Craft("Latitude", Event.Latitude.ToString());
            Variable_Craft("Longitude", Event.Longitude.ToString());
            Variable_Craft("NearestDestination", Event.NearestDestination.ToString());
            #endregion
        }
    }

    #region Touchdown Event
    public class Touchdown : Base
    {
        public string PlayerControlled { get; set; }
        public string Taxi { get; set; }
        public string Multicrew { get; set; }
        public string StarSystem { get; set; }
        public decimal SystemAddress { get; set; }
        public string Body { get; set; }
        public decimal BodyID { get; set; }
        public string OnStation { get; set; }
        public string OnPlanet { get; set; }
        public decimal Latitude { get; set; }
        public decimal Longitude { get; set; }
        public string NearestDestination { get; set; }
    }
    #endregion
}


//Journal Reader Code Chunk.

// else if (EventName == "Touchdown")
// {
//     var Event = JsonConvert.DeserializeObject<ALICE_Events.Touchdown>(RawLine);
//     Manager.UpdateEvents(EventName, Event);
//     Manager.Touchdown.Logic();
// }
