//Code Generated By Project A.L.I.C.E Developer Toolkit
//Class File Generated: 01/18/2026 4:27 PM
//Source Journal Line: { "timestamp":"2025-11-12T09:17:26Z", "event":"Reputation", "Empire":75.000000, "Federation":75.000000, "Independent":0.000000, "Alliance":72.478600 }

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using ALICE_Ships_Datalink_Interface;
using ALICE_Command_Interface;
using ALICE_Internal;

namespace ALICE_Events
{
    public class Event_Reputation : Event_Base
    {
        public Event_Reputation()
        {
            Name = "Reputation";
        }

        public void Logic()
        {
            if (Manager.WriteVariables && WriteVariables)
            {
                try
                {
                    Variables_Clear();
                    Variables_Generate();
                    Variables_Write();
                }
                catch (Exception ex)
                {
                    Internal.Exception(Name, "An Exception Occured While Updating Variables");
                    Internal.Exception(Name, "Exception: " + ex);
                }
            }

            //GameState.Logic_Reputation((Reputation)GetEvent());

            TriggerEvent();
        }

        public void Variables_Generate()
        {
            Reputation Event = (Reputation)Manager.GetEvent(Name);

            Variables.Clear();

            #region Custom Variables

            #endregion

            #region Event Variables
            Variable_Craft("Empire", Event.Empire.ToString());
            Variable_Craft("Federation", Event.Federation.ToString());
            Variable_Craft("Independent", Event.Independent.ToString());
            Variable_Craft("Alliance", Event.Alliance.ToString());
            #endregion
        }
    }

    #region Reputation Event
    public class Reputation : Base
    {
        public decimal Empire { get; set; }
        public decimal Federation { get; set; }
        public decimal Independent { get; set; }
        public decimal Alliance { get; set; }
    }
    #endregion
}


//Journal Reader Code Chunk.

// else if (EventName == "Reputation")
// {
//     var Event = JsonConvert.DeserializeObject<ALICE_Events.Reputation>(RawLine);
//     Manager.UpdateEvents(EventName, Event);
//     Manager.Reputation.Logic();
// }
