//Code Generated By Project A.L.I.C.E Developer Toolkit
//Class File Generated: 01/18/2026 4:27 PM
//Source Journal Line: { "timestamp":"2025-11-12T10:45:29Z", "event":"CargoDepot", "MissionID":1035688088, "UpdateType":"Deliver", "CargoType":"Bertrandite", "Count":726, "StartMarketID":0, "EndMarketID":3222819072, "ItemsCollected":0, "ItemsDelivered":726, "TotalItemsToDeliver":726, "Progress":0.000000 }

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using ALICE_Ships_Datalink_Interface;
using ALICE_Command_Interface;
using ALICE_Internal;

namespace ALICE_Events
{
    public class Event_CargoDepot : Event_Base
    {
        public Event_CargoDepot()
        {
            Name = "CargoDepot";
        }

        public void Logic()
        {
            if (Manager.WriteVariables && WriteVariables)
            {
                try
                {
                    Variables_Clear();
                    Variables_Generate();
                    Variables_Write();
                }
                catch (Exception ex)
                {
                    Internal.Exception(Name, "An Exception Occured While Updating Variables");
                    Internal.Exception(Name, "Exception: " + ex);
                }
            }

            //GameState.Logic_CargoDepot((CargoDepot)GetEvent());

            TriggerEvent();
        }

        public void Variables_Generate()
        {
            CargoDepot Event = (CargoDepot)Manager.GetEvent(Name);

            Variables.Clear();

            #region Custom Variables

            #endregion

            #region Event Variables
            Variable_Craft("MissionID", Event.MissionID.ToString());
            Variable_Craft("UpdateType", Event.UpdateType.ToString());
            Variable_Craft("CargoType", Event.CargoType.ToString());
            Variable_Craft("Count", Event.Count.ToString());
            Variable_Craft("StartMarketID", Event.StartMarketID.ToString());
            Variable_Craft("EndMarketID", Event.EndMarketID.ToString());
            Variable_Craft("ItemsCollected", Event.ItemsCollected.ToString());
            Variable_Craft("ItemsDelivered", Event.ItemsDelivered.ToString());
            Variable_Craft("TotalItemsToDeliver", Event.TotalItemsToDeliver.ToString());
            Variable_Craft("Progress", Event.Progress.ToString());
            #endregion
        }
    }

    #region CargoDepot Event
    public class CargoDepot : Base
    {
        public decimal MissionID { get; set; }
        public string UpdateType { get; set; }
        public string CargoType { get; set; }
        public decimal Count { get; set; }
        public decimal StartMarketID { get; set; }
        public decimal EndMarketID { get; set; }
        public decimal ItemsCollected { get; set; }
        public decimal ItemsDelivered { get; set; }
        public decimal TotalItemsToDeliver { get; set; }
        public decimal Progress { get; set; }
    }
    #endregion
}


//Journal Reader Code Chunk.

// else if (EventName == "CargoDepot")
// {
//     var Event = JsonConvert.DeserializeObject<ALICE_Events.CargoDepot>(RawLine);
//     Manager.UpdateEvents(EventName, Event);
//     Manager.CargoDepot.Logic();
// }
