//Code Generated By Project A.L.I.C.E Developer Toolkit
//Class File Generated: 01/18/2026 4:27 PM
//Source Journal Line: { "timestamp":"2025-11-12T09:17:26Z", "event":"Rank", "Combat":4, "Trade":13, "Explore":5, "Soldier":1, "Exobiologist":0, "Empire":0, "Federation":6, "CQC":0 }

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using ALICE_Ships_Datalink_Interface;
using ALICE_Command_Interface;
using ALICE_Internal;

namespace ALICE_Events
{
    public class Event_Rank : Event_Base
    {
        public Event_Rank()
        {
            Name = "Rank";
        }

        public void Logic()
        {
            if (Manager.WriteVariables && WriteVariables)
            {
                try
                {
                    Variables_Clear();
                    Variables_Generate();
                    Variables_Write();
                }
                catch (Exception ex)
                {
                    Internal.Exception(Name, "An Exception Occured While Updating Variables");
                    Internal.Exception(Name, "Exception: " + ex);
                }
            }

            //GameState.Logic_Rank((Rank)GetEvent());

            TriggerEvent();
        }

        public void Variables_Generate()
        {
            Rank Event = (Rank)Manager.GetEvent(Name);

            Variables.Clear();

            #region Custom Variables

            #endregion

            #region Event Variables
            Variable_Craft("Combat", Event.Combat.ToString());
            Variable_Craft("Trade", Event.Trade.ToString());
            Variable_Craft("Explore", Event.Explore.ToString());
            Variable_Craft("Soldier", Event.Soldier.ToString());
            Variable_Craft("Exobiologist", Event.Exobiologist.ToString());
            Variable_Craft("Empire", Event.Empire.ToString());
            Variable_Craft("Federation", Event.Federation.ToString());
            Variable_Craft("CQC", Event.CQC.ToString());
            #endregion
        }
    }

    #region Rank Event
    public class Rank : Base
    {
        public decimal Combat { get; set; }
        public decimal Trade { get; set; }
        public decimal Explore { get; set; }
        public decimal Soldier { get; set; }
        public decimal Exobiologist { get; set; }
        public decimal Empire { get; set; }
        public decimal Federation { get; set; }
        public decimal CQC { get; set; }
    }
    #endregion
}


//Journal Reader Code Chunk.

// else if (EventName == "Rank")
// {
//     var Event = JsonConvert.DeserializeObject<ALICE_Events.Rank>(RawLine);
//     Manager.UpdateEvents(EventName, Event);
//     Manager.Rank.Logic();
// }
