//Code Generated By Project A.L.I.C.E Developer Toolkit
//Class File Generated: 01/18/2026 4:27 PM
//Source Journal Line: { "timestamp":"2026-01-11T00:10:34Z", "event":"StartJump", "JumpType":"Hyperspace", "Taxi":false, "StarSystem":"Core Sys Sector QT-R b4-5", "SystemAddress":11665802339769, "StarClass":"M" }

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using ALICE_Ships_Datalink_Interface;
using ALICE_Command_Interface;
using ALICE_Internal;

namespace ALICE_Events
{
    public class Event_StartJump : Event_Base
    {
        public Event_StartJump()
        {
            Name = "StartJump";
        }

        public void Logic()
        {
            if (Manager.WriteVariables && WriteVariables)
            {
                try
                {
                    Variables_Clear();
                    Variables_Generate();
                    Variables_Write();
                }
                catch (Exception ex)
                {
                    Internal.Exception(Name, "An Exception Occured While Updating Variables");
                    Internal.Exception(Name, "Exception: " + ex);
                }
            }

            //GameState.Logic_StartJump((StartJump)GetEvent());

            TriggerEvent();
        }

        public void Variables_Generate()
        {
            StartJump Event = (StartJump)Manager.GetEvent(Name);

            Variables.Clear();

            #region Custom Variables

            #endregion

            #region Event Variables
            Variable_Craft("JumpType", Event.JumpType.ToString());
            Variable_Craft("Taxi", Event.Taxi.ToString());
            Variable_Craft("StarSystem", Event.StarSystem.ToString());
            Variable_Craft("SystemAddress", Event.SystemAddress.ToString());
            Variable_Craft("StarClass", Event.StarClass.ToString());
            #endregion
        }
    }

    #region StartJump Event
    public class StartJump : Base
    {
        public string JumpType { get; set; }
        public string Taxi { get; set; }
        public string StarSystem { get; set; }
        public decimal SystemAddress { get; set; }
        public string StarClass { get; set; }
    }
    #endregion
}


//Journal Reader Code Chunk.

// else if (EventName == "StartJump")
// {
//     var Event = JsonConvert.DeserializeObject<ALICE_Events.StartJump>(RawLine);
//     Manager.UpdateEvents(EventName, Event);
//     Manager.StartJump.Logic();
// }
