//Code Generated By Project A.L.I.C.E Developer Toolkit
//Class File Generated: 01/18/2026 4:27 PM
//Source Journal Line: { "timestamp":"2025-11-12T10:59:49Z", "event":"Undocked", "StationName":"McDevitt Settlement", "StationType":"CraterPort", "MarketID":3507690240, "Taxi":false, "Multicrew":false }

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using ALICE_Ships_Datalink_Interface;
using ALICE_Command_Interface;
using ALICE_Internal;

namespace ALICE_Events
{
    public class Event_Undocked : Event_Base
    {
        public Event_Undocked()
        {
            Name = "Undocked";
        }

        public void Logic()
        {
            if (Manager.WriteVariables && WriteVariables)
            {
                try
                {
                    Variables_Clear();
                    Variables_Generate();
                    Variables_Write();
                }
                catch (Exception ex)
                {
                    Internal.Exception(Name, "An Exception Occured While Updating Variables");
                    Internal.Exception(Name, "Exception: " + ex);
                }
            }

            //GameState.Logic_Undocked((Undocked)GetEvent());

            TriggerEvent();
        }

        public void Variables_Generate()
        {
            Undocked Event = (Undocked)Manager.GetEvent(Name);

            Variables.Clear();

            #region Custom Variables

            #endregion

            #region Event Variables
            Variable_Craft("StationName", Event.StationName.ToString());
            Variable_Craft("StationType", Event.StationType.ToString());
            Variable_Craft("MarketID", Event.MarketID.ToString());
            Variable_Craft("Taxi", Event.Taxi.ToString());
            Variable_Craft("Multicrew", Event.Multicrew.ToString());
            #endregion
        }
    }

    #region Undocked Event
    public class Undocked : Base
    {
        public string StationName { get; set; }
        public string StationType { get; set; }
        public decimal MarketID { get; set; }
        public string Taxi { get; set; }
        public string Multicrew { get; set; }
    }
    #endregion
}


//Journal Reader Code Chunk.

// else if (EventName == "Undocked")
// {
//     var Event = JsonConvert.DeserializeObject<ALICE_Events.Undocked>(RawLine);
//     Manager.UpdateEvents(EventName, Event);
//     Manager.Undocked.Logic();
// }
