//Code Generated By Project A.L.I.C.E Developer Toolkit
//Class File Generated: 01/18/2026 4:27 PM
//Source Journal Line: { "timestamp":"2026-01-17T01:57:14Z", "event":"SupercruiseDestinationDrop", "Type":"$MULTIPLAYER_SCENARIO79_TITLE;", "Type_Localised":"Resource Extraction Site [Hazardous]", "Threat":4 }

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using ALICE_Ships_Datalink_Interface;
using ALICE_Command_Interface;
using ALICE_Internal;

namespace ALICE_Events
{
    public class Event_SupercruiseDestinationDrop : Event_Base
    {
        public Event_SupercruiseDestinationDrop()
        {
            Name = "SupercruiseDestinationDrop";
        }

        public void Logic()
        {
            if (Manager.WriteVariables && WriteVariables)
            {
                try
                {
                    Variables_Clear();
                    Variables_Generate();
                    Variables_Write();
                }
                catch (Exception ex)
                {
                    Internal.Exception(Name, "An Exception Occured While Updating Variables");
                    Internal.Exception(Name, "Exception: " + ex);
                }
            }

            //GameState.Logic_SupercruiseDestinationDrop((SupercruiseDestinationDrop)GetEvent());

            TriggerEvent();
        }

        public void Variables_Generate()
        {
            SupercruiseDestinationDrop Event = (SupercruiseDestinationDrop)Manager.GetEvent(Name);

            Variables.Clear();

            #region Custom Variables

            #endregion

            #region Event Variables
            Variable_Craft("Type", Event.Type.ToString());
            Variable_Craft("Type_Localised", Event.Type_Localised.ToString());
            Variable_Craft("Threat", Event.Threat.ToString());
            #endregion
        }
    }

    #region SupercruiseDestinationDrop Event
    public class SupercruiseDestinationDrop : Base
    {
        public string Type { get; set; }
        public string Type_Localised { get; set; }
        public decimal Threat { get; set; }
    }
    #endregion
}


//Journal Reader Code Chunk.

// else if (EventName == "SupercruiseDestinationDrop")
// {
//     var Event = JsonConvert.DeserializeObject<ALICE_Events.SupercruiseDestinationDrop>(RawLine);
//     Manager.UpdateEvents(EventName, Event);
//     Manager.SupercruiseDestinationDrop.Logic();
// }
