//Code Generated By Project A.L.I.C.E Developer Toolkit
//Class File Generated: 01/19/2026 11:54 AM
//Source Journal Line: { "timestamp":"2025-11-12T12:26:35Z", "event":"Shutdown" }

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using ALICE_Ships_Datalink_Interface;
using ALICE_Command_Interface;
using ALICE_Internal;

namespace ALICE_Events
{
    public class Event_Shutdown : Event_Base
    {
        public Event_Shutdown()
        {
            Name = "Shutdown";
        }

        public void Logic()
        {
            if (Manager.WriteVariables && WriteVariables)
            {
                try
                {
                    Variables_Clear();
                    Variables_Generate();
                    Variables_Write();
                }
                catch (Exception ex)
                {
                    Internal.Exception(Name, "An Exception Occured While Updating Variables");
                    Internal.Exception(Name, "Exception: " + ex);
                }
            }

            //GameState.Logic_Shutdown((Shutdown)GetEvent());

            TriggerEvent();
        }

        public void Variables_Generate()
        {
            Shutdown Event = (Shutdown)Manager.GetEvent(Name);

            Variables.Clear();

            #region Custom Variables

            #endregion

            #region Event Variables
            #endregion
        }
    }

    #region Shutdown Event
    public class Shutdown : Base
    {
    }
    #endregion
}


//Journal Reader Code Chunk.

// else if (EventName == "Shutdown")
// {
//     var Event = JsonConvert.DeserializeObject<ALICE_Events.Shutdown>(RawLine);
//     Manager.UpdateEvents(EventName, Event);
//     Manager.Shutdown.Logic();
// }
