//Code Generated By Project A.L.I.C.E Developer Toolkit
//Class File Generated: 01/18/2026 4:27 PM
//Source Journal Line: { "timestamp":"2026-01-15T17:59:13Z", "event":"Market", "MarketID":3714546688, "StationName":"FXBX", "StationType":"FleetCarrier", "CarrierDockingAccess":"all", "StarSystem":"Rho Ophiuchi Sector IH-U b3-1" }

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using ALICE_Ships_Datalink_Interface;
using ALICE_Command_Interface;
using ALICE_Internal;

namespace ALICE_Events
{
    public class Event_Market : Event_Base
    {
        public Event_Market()
        {
            Name = "Market";
        }

        public void Logic()
        {
            if (Manager.WriteVariables && WriteVariables)
            {
                try
                {
                    Variables_Clear();
                    Variables_Generate();
                    Variables_Write();
                }
                catch (Exception ex)
                {
                    Internal.Exception(Name, "An Exception Occured While Updating Variables");
                    Internal.Exception(Name, "Exception: " + ex);
                }
            }

            //GameState.Logic_Market((Market)GetEvent());

            TriggerEvent();
        }

        public void Variables_Generate()
        {
            Market Event = (Market)Manager.GetEvent(Name);

            Variables.Clear();

            #region Custom Variables

            #endregion

            #region Event Variables
            Variable_Craft("MarketID", Event.MarketID.ToString());
            Variable_Craft("StationName", Event.StationName.ToString());
            Variable_Craft("StationType", Event.StationType.ToString());
            Variable_Craft("CarrierDockingAccess", Event.CarrierDockingAccess.ToString());
            Variable_Craft("StarSystem", Event.StarSystem.ToString());
            #endregion
        }
    }

    #region Market Event
    public class Market : Base
    {
        public decimal MarketID { get; set; }
        public string StationName { get; set; }
        public string StationType { get; set; }
        public string CarrierDockingAccess { get; set; }
        public string StarSystem { get; set; }
    }
    #endregion
}


//Journal Reader Code Chunk.

// else if (EventName == "Market")
// {
//     var Event = JsonConvert.DeserializeObject<ALICE_Events.Market>(RawLine);
//     Manager.UpdateEvents(EventName, Event);
//     Manager.Market.Logic();
// }
