//Code Generated By Project A.L.I.C.E Developer Toolkit
//Class File Generated: 01/18/2026 4:27 PM
//Source Journal Line: { "timestamp":"2026-01-10T21:37:18Z", "event":"DropshipDeploy", "StarSystem":"Kurmodiae", "SystemAddress":5856221500130, "Body":"Kurmodiae A 1 a", "BodyID":14, "OnStation":false, "OnPlanet":true }

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using ALICE_Ships_Datalink_Interface;
using ALICE_Command_Interface;
using ALICE_Internal;

namespace ALICE_Events
{
    public class Event_DropshipDeploy : Event_Base
    {
        public Event_DropshipDeploy()
        {
            Name = "DropshipDeploy";
        }

        public void Logic()
        {
            if (Manager.WriteVariables && WriteVariables)
            {
                try
                {
                    Variables_Clear();
                    Variables_Generate();
                    Variables_Write();
                }
                catch (Exception ex)
                {
                    Internal.Exception(Name, "An Exception Occured While Updating Variables");
                    Internal.Exception(Name, "Exception: " + ex);
                }
            }

            //GameState.Logic_DropshipDeploy((DropshipDeploy)GetEvent());

            TriggerEvent();
        }

        public void Variables_Generate()
        {
            DropshipDeploy Event = (DropshipDeploy)Manager.GetEvent(Name);

            Variables.Clear();

            #region Custom Variables

            #endregion

            #region Event Variables
            Variable_Craft("StarSystem", Event.StarSystem.ToString());
            Variable_Craft("SystemAddress", Event.SystemAddress.ToString());
            Variable_Craft("Body", Event.Body.ToString());
            Variable_Craft("BodyID", Event.BodyID.ToString());
            Variable_Craft("OnStation", Event.OnStation.ToString());
            Variable_Craft("OnPlanet", Event.OnPlanet.ToString());
            #endregion
        }
    }

    #region DropshipDeploy Event
    public class DropshipDeploy : Base
    {
        public string StarSystem { get; set; }
        public decimal SystemAddress { get; set; }
        public string Body { get; set; }
        public decimal BodyID { get; set; }
        public string OnStation { get; set; }
        public string OnPlanet { get; set; }
    }
    #endregion
}


//Journal Reader Code Chunk.

// else if (EventName == "DropshipDeploy")
// {
//     var Event = JsonConvert.DeserializeObject<ALICE_Events.DropshipDeploy>(RawLine);
//     Manager.UpdateEvents(EventName, Event);
//     Manager.DropshipDeploy.Logic();
// }
