//Code Generated By Project A.L.I.C.E Developer Toolkit
//Class File Generated: 01/18/2026 4:27 PM
//Source Journal Line: { "timestamp":"2025-11-12T10:56:22Z", "event":"ApproachBody", "StarSystem":"HIP 9774", "SystemAddress":1659761559907, "Body":"HIP 9774 A 3 a", "BodyID":25 }

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using ALICE_Ships_Datalink_Interface;
using ALICE_Command_Interface;
using ALICE_Internal;

namespace ALICE_Events
{
    public class Event_ApproachBody : Event_Base
    {
        public Event_ApproachBody()
        {
            Name = "ApproachBody";
        }

        public void Logic()
        {
            if (Manager.WriteVariables && WriteVariables)
            {
                try
                {
                    Variables_Clear();
                    Variables_Generate();
                    Variables_Write();
                }
            }

            //GameState.Logic_ApproachBody((ApproachBody)GetEvent());

            TriggerEvent();
        }

        public void Variables_Generate()
        {
            ApproachBody Event = (ApproachBody)Manager.GetEvent(Name);

            Variables.Clear();

            #region Custom Variables

            #endregion

            #region Event Variables
            Variable_Craft("StarSystem", Event.StarSystem.ToString());
            Variable_Craft("SystemAddress", Event.SystemAddress.ToString());
            Variable_Craft("Body", Event.Body.ToString());
            Variable_Craft("BodyID", Event.BodyID.ToString());
            #endregion
        }
    }

    #region ApproachBody Event
    public class ApproachBody : Base
    {
        public string StarSystem { get; set; }
        public decimal SystemAddress { get; set; }
        public string Body { get; set; }
        public decimal BodyID { get; set; }
    }
    #endregion
}


//Journal Reader Code Chunk.

// else if (EventName == "ApproachBody")
// {
//     var Event = JsonConvert.DeserializeObject<ALICE_Events.ApproachBody>(RawLine);
//     Manager.UpdateEvents(EventName, Event);
//     Manager.ApproachBody.Logic();
// }
