//Code Generated By Project A.L.I.C.E Developer Toolkit
//Class File Generated: 01/18/2026 4:27 PM
//Source Journal Line: { "timestamp":"2025-11-12T09:35:22Z", "event":"Music", "MusicTrack":"DestinationFromSupercruise" }

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using ALICE_Ships_Datalink_Interface;
using ALICE_Command_Interface;
using ALICE_Internal;

namespace ALICE_Events
{
    public class Event_Music : Event_Base
    {
        public Event_Music()
        {
            Name = "Music";
        }

        public void Logic()
        {
            if (Manager.WriteVariables && WriteVariables)
            {
                try
                {
                    Variables_Clear();
                    Variables_Generate();
                    Variables_Write();
                }
                catch (Exception ex)
                {
                    Internal.Exception(Name, "An Exception Occured While Updating Variables");
                    Internal.Exception(Name, "Exception: " + ex);
                }
            }

            //GameState.Logic_Music((Music)GetEvent());

            TriggerEvent();
        }

        public void Variables_Generate()
        {
            Music Event = (Music)Manager.GetEvent(Name);

            Variables.Clear();

            #region Custom Variables

            #endregion

            #region Event Variables
            Variable_Craft("MusicTrack", Event.MusicTrack.ToString());
            #endregion
        }
    }

    #region Music Event
    public class Music : Base
    {
        public string MusicTrack { get; set; }
    }
    #endregion
}


//Journal Reader Code Chunk.

// else if (EventName == "Music")
// {
//     var Event = JsonConvert.DeserializeObject<ALICE_Events.Music>(RawLine);
//     Manager.UpdateEvents(EventName, Event);
//     Manager.Music.Logic();
// }
