//Code Generated By Project A.L.I.C.E Developer Toolkit
//Class File Generated: 01/18/2026 4:27 PM
//Source Journal Line: { "timestamp":"2026-01-17T19:45:37Z", "event":"MissionCompleted", "Faction":"Loan Sharks Mercenary Corps", "Name":"Mission_Massacre_RankFed_name", "LocalisedName":"Federal Navy Strike Contract", "MissionID":1042347155, "TargetType":"$MissionUtil_FactionTag_Pirate;", "TargetType_Localised":"Pirates", "TargetFaction":"GD 215 Blue Pirates", "KillCount":5, "DestinationSystem":"GD 215", "DestinationStation":"Faraday Orbital", "Reward":449602, "MaterialsReward":[ { "Name":"FocusCrystals", "Name_Localised":"Focus Crystals", "Category":"$MICRORESOURCE_CATEGORY_Manufactured;", "Category_Localised":"Manufactured", "Count":18 } ], "FactionEffects":[ { "Faction":"Loan Sharks Mercenary Corps", "Effects":[ { "Effect":"$MISSIONUTIL_Interaction_Summary_EP_up;", "Effect_Localised":"The economic status of $#MinorFaction; has improved in the $#System; system.", "Trend":"UpGood" } ], "Influence":[ { "SystemAddress":2278220106099, "Trend":"UpGood", "Influence":"++" } ], "ReputationTrend":"UpGood", "Reputation":"++" }, { "Faction":"GD 215 Blue Pirates", "Effects":[ { "Effect":"$MISSIONUTIL_Interaction_Summary_EP_down;", "Effect_Localised":"The economic status of $#MinorFaction; has declined in the $#System; system.", "Trend":"DownBad" } ], "Influence":[ { "SystemAddress":5361730210696, "Trend":"DownBad", "Influence":"+" } ], "ReputationTrend":"DownBad", "Reputation":"+" } ] }

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using ALICE_Ships_Datalink_Interface;
using ALICE_Command_Interface;
using ALICE_Internal;

namespace ALICE_Events
{
    public class Event_MissionCompleted : Event_Base
    {
        public Event_MissionCompleted()
        {
            Name = "MissionCompleted";
        }

        public void Logic()
        {
            if (Manager.WriteVariables && WriteVariables)
            {
                try
                {
                    Variables_Clear();
                    Variables_Generate();
                    Variables_Write();
                }
                catch (Exception ex)
                {
                    Internal.Exception(Name, "An Exception Occured While Updating Variables");
                    Internal.Exception(Name, "Exception: " + ex);
                }
            }

            //GameState.Logic_MissionCompleted((MissionCompleted)GetEvent());

            TriggerEvent();
        }

        public void Variables_Generate()
        {
            MissionCompleted Event = (MissionCompleted)Manager.GetEvent(Name);

            Variables.Clear();

            #region Custom Variables

            #endregion

            #region Event Variables
            Variable_Craft("Faction", Event.Faction.ToString());
            Variable_Craft("Name", Event.Name.ToString());
            Variable_Craft("LocalisedName", Event.LocalisedName.ToString());
            Variable_Craft("MissionID", Event.MissionID.ToString());
            Variable_Craft("TargetType", Event.TargetType.ToString());
            Variable_Craft("TargetType_Localised", Event.TargetType_Localised.ToString());
            Variable_Craft("TargetFaction", Event.TargetFaction.ToString());
            Variable_Craft("KillCount", Event.KillCount.ToString());
            Variable_Craft("DestinationSystem", Event.DestinationSystem.ToString());
            Variable_Craft("DestinationStation", Event.DestinationStation.ToString());
            Variable_Craft("Reward", Event.Reward.ToString());
            Variable_Craft("MaterialsReward", Event.MaterialsReward.ToString());
            Variable_Craft("FactionEffects", Event.FactionEffects.ToString());
            #endregion
        }
    }

    #region MissionCompleted Event
    public class MissionCompleted : Base
    {
        public string Faction { get; set; }
        public string Name { get; set; }
        public string LocalisedName { get; set; }
        public decimal MissionID { get; set; }
        public string TargetType { get; set; }
        public string TargetType_Localised { get; set; }
        public string TargetFaction { get; set; }
        public decimal KillCount { get; set; }
        public string DestinationSystem { get; set; }
        public string DestinationStation { get; set; }
        public decimal Reward { get; set; }
        public string MaterialsReward { get; set; }
        public string FactionEffects { get; set; }
    }
    #endregion
}


//Journal Reader Code Chunk.

// else if (EventName == "MissionCompleted")
// {
//     var Event = JsonConvert.DeserializeObject<ALICE_Events.MissionCompleted>(RawLine);
//     Manager.UpdateEvents(EventName, Event);
//     Manager.MissionCompleted.Logic();
// }
