//Code Generated By Project A.L.I.C.E Developer Toolkit
//Class File Generated: 01/18/2026 4:27 PM
//Source Journal Line: { "timestamp":"2026-01-10T14:34:02Z", "event":"SendText", "To":"starsystem", "Message":"hope is to get him sorted for the ptn booze cruise so he can go print credits to remove that hastle from the game and let him just have fun", "Sent":true }

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using ALICE_Ships_Datalink_Interface;
using ALICE_Command_Interface;
using ALICE_Internal;

namespace ALICE_Events
{
    public class Event_SendText : Event_Base
    {
        public Event_SendText()
        {
            Name = "SendText";
        }

        public void Logic()
        {
            if (Manager.WriteVariables && WriteVariables)
            {
                try
                {
                    Variables_Clear();
                    Variables_Generate();
                    Variables_Write();
                }
            }

            //GameState.Logic_SendText((SendText)GetEvent());

            TriggerEvent();
        }

        public void Variables_Generate()
        {
            SendText Event = (SendText)Manager.GetEvent(Name);

            Variables.Clear();

            #region Custom Variables

            #endregion

            #region Event Variables
            Variable_Craft("To", Event.To.ToString());
            Variable_Craft("Message", Event.Message.ToString());
            Variable_Craft("Sent", Event.Sent.ToString());
            #endregion
        }
    }

    #region SendText Event
    public class SendText : Base
    {
        public string To { get; set; }
        public string Message { get; set; }
        public string Sent { get; set; }
    }
    #endregion
}


//Journal Reader Code Chunk.

// else if (EventName == "SendText")
// {
//     var Event = JsonConvert.DeserializeObject<ALICE_Events.SendText>(RawLine);
//     Manager.UpdateEvents(EventName, Event);
//     Manager.SendText.Logic();
// }
