//Code Generated By Project A.L.I.C.E Developer Toolkit
//Class File Generated: 01/18/2026 4:27 PM
//Source Journal Line: { "timestamp":"2026-01-17T18:33:38Z", "event":"ShipTargeted", "TargetLocked":true, "Ship":"federation_dropship_mkii", "Ship_Localised":"Federal Assault Ship", "ScanStage":3, "PilotName":"$npc_name_decorate:#name=Douglas Alexander Frank Torrance;", "PilotName_Localised":"Douglas Alexander Frank Torrance", "PilotRank":"Dangerous", "ShieldHealth":100.000000, "HullHealth":100.000000, "Faction":"Kigah Drug Empire", "LegalStatus":"Wanted", "Bounty":416079 }

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using ALICE_Ships_Datalink_Interface;
using ALICE_Command_Interface;
using ALICE_Internal;

namespace ALICE_Events
{
    public class Event_ShipTargeted : Event_Base
    {
        public Event_ShipTargeted()
        {
            Name = "ShipTargeted";
        }

        public void Logic()
        {
            if (Manager.WriteVariables && WriteVariables)
            {
                try
                {
                    Variables_Clear();
                    Variables_Generate();
                    Variables_Write();
                }
            }

            //GameState.Logic_ShipTargeted((ShipTargeted)GetEvent());

            TriggerEvent();
        }

        public void Variables_Generate()
        {
            ShipTargeted Event = (ShipTargeted)Manager.GetEvent(Name);

            Variables.Clear();

            #region Custom Variables

            #endregion

            #region Event Variables
            Variable_Craft("TargetLocked", Event.TargetLocked.ToString());
            Variable_Craft("Ship", Event.Ship.ToString());
            Variable_Craft("Ship_Localised", Event.Ship_Localised.ToString());
            Variable_Craft("ScanStage", Event.ScanStage.ToString());
            Variable_Craft("PilotName", Event.PilotName.ToString());
            Variable_Craft("PilotName_Localised", Event.PilotName_Localised.ToString());
            Variable_Craft("PilotRank", Event.PilotRank.ToString());
            Variable_Craft("ShieldHealth", Event.ShieldHealth.ToString());
            Variable_Craft("HullHealth", Event.HullHealth.ToString());
            Variable_Craft("Faction", Event.Faction.ToString());
            Variable_Craft("LegalStatus", Event.LegalStatus.ToString());
            Variable_Craft("Bounty", Event.Bounty.ToString());
            #endregion
        }
    }

    #region ShipTargeted Event
    public class ShipTargeted : Base
    {
        public string TargetLocked { get; set; }
        public string Ship { get; set; }
        public string Ship_Localised { get; set; }
        public decimal ScanStage { get; set; }
        public string PilotName { get; set; }
        public string PilotName_Localised { get; set; }
        public string PilotRank { get; set; }
        public decimal ShieldHealth { get; set; }
        public decimal HullHealth { get; set; }
        public string Faction { get; set; }
        public string LegalStatus { get; set; }
        public decimal Bounty { get; set; }
    }
    #endregion
}


//Journal Reader Code Chunk.

// else if (EventName == "ShipTargeted")
// {
//     var Event = JsonConvert.DeserializeObject<ALICE_Events.ShipTargeted>(RawLine);
//     Manager.UpdateEvents(EventName, Event);
//     Manager.ShipTargeted.Logic();
// }
