//Code Generated By Project A.L.I.C.E Developer Toolkit
//Class File Generated: 01/18/2026 4:27 PM
//Source Journal Line: { "timestamp":"2026-01-11T00:26:14Z", "event":"LaunchSRV", "SRVType":"combat_multicrew_srv_01", "SRVType_Localised":"SRV Scorpion", "Loadout":"default", "ID":34, "PlayerControlled":true }

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using ALICE_Ships_Datalink_Interface;
using ALICE_Command_Interface;
using ALICE_Internal;

namespace ALICE_Events
{
    public class Event_LaunchSRV : Event_Base
    {
        public Event_LaunchSRV()
        {
            Name = "LaunchSRV";
        }

        public void Logic()
        {
            if (Manager.WriteVariables && WriteVariables)
            {
                try
                {
                    Variables_Clear();
                    Variables_Generate();
                    Variables_Write();
                }
                catch (Exception ex)
                {
                    Internal.Exception(Name, "An Exception Occured While Updating Variables");
                    Internal.Exception(Name, "Exception: " + ex);
                }
            }

            //GameState.Logic_LaunchSRV((LaunchSRV)GetEvent());

            TriggerEvent();
        }

        public void Variables_Generate()
        {
            LaunchSRV Event = (LaunchSRV)Manager.GetEvent(Name);

            Variables.Clear();

            #region Custom Variables

            #endregion

            #region Event Variables
            Variable_Craft("SRVType", Event.SRVType.ToString());
            Variable_Craft("SRVType_Localised", Event.SRVType_Localised.ToString());
            Variable_Craft("Loadout", Event.Loadout.ToString());
            Variable_Craft("ID", Event.ID.ToString());
            Variable_Craft("PlayerControlled", Event.PlayerControlled.ToString());
            #endregion
        }
    }

    #region LaunchSRV Event
    public class LaunchSRV : Base
    {
        public string SRVType { get; set; }
        public string SRVType_Localised { get; set; }
        public string Loadout { get; set; }
        public decimal ID { get; set; }
        public string PlayerControlled { get; set; }
    }
    #endregion
}


//Journal Reader Code Chunk.

// else if (EventName == "LaunchSRV")
// {
//     var Event = JsonConvert.DeserializeObject<ALICE_Events.LaunchSRV>(RawLine);
//     Manager.UpdateEvents(EventName, Event);
//     Manager.LaunchSRV.Logic();
// }
